import '../country_subdivision.dart';

const countrySubdivisionBIHBIH = CountrySubdivision(
  alpha2: 'BA',
  alpha3: 'BIH',
  code: 'BIH',
  name: 'Federacija Bosna i Hercegovina',
  unofficialNames: ['Federacija Bosna i Hercegovina'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: 43.8874897, longitude: 17.842793),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: 45.2271323, longitude: 19.0392512),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: 42.6075035, longitude: 15.7237473)),
  translations: {
    'en': 'Federation of Bosnia and Herzegovina',
    'ar': 'اتحاد البوسنة والهرسك',
    'az': 'Bosniya və Herseqovina Federasiyası',
    'be': 'Федэрацыя Босніі і Герцагавіны',
    'bg': 'Федерация Босна и Херцеговина',
    'ca': 'Federació de Bòsnia i Hercegovina',
    'cs': 'Federace Bosny a Hercegoviny',
    'de': 'Föderation Bosnien und Herzegowina',
    'el': 'Ομοσπονδία Βοσνίας-Ερζεγοβίνης',
    'es': 'Federación de Bosnia y Herzegovina',
    'et': 'Bosnia ja Hertsegoviina Föderatsioon',
    'eu': 'Bosnia-Herzegovinako Federazioa',
    'fa': 'فدراسیون بوسنی و هرزگوین',
    'fi': 'Bosnia ja Hertsegovinan federaatio',
    'fr': 'Fédération de Bosnie-et-Herzégovine',
    'gl': 'Federación de Bosnia e Hercegovina',
    'he': 'הפדרציה של בוסניה והרצגובינה',
    'hr': 'Federacija Bosne i Hercegovine',
    'hu': 'Bosznia-hercegovinai Föderáció',
    'id': 'Federasi Bosnia dan Herzegovina',
    'it': 'Federazione di Bosnia ed Erzegovina',
    'ja': 'ボスニア・ヘルツェゴビナ連邦',
    'ka': 'ბოსნია და ჰერცეგოვინის ფედერაცია',
    'ko': '보스니아 헤르체고비나 연방',
    'lt': 'Bosnijos ir Hercegovinos Federacija',
    'ms': 'Persekutuan Bosnia dan Herzegovina',
    'nb': 'Føderasjonen av Bosnia og Hercegovina',
    'nl': 'Federatie van Bosnië en Herzegovina',
    'pl': 'Federacja Bośni i Hercegowiny',
    'pt': 'Federação da Bósnia e Herzegovina',
    'ro': 'Federația Bosniei și Herțegovinei',
    'ru': 'Федерация Боснии и Герцеговины',
    'sl': 'Federacija Bosne in Hercegovine',
    'sr': 'Федерација Босне и Херцеговине',
    'sv': 'Federationen Bosnien och Hercegovina',
    'th': 'สหพันธรัฐบอสเนียและเฮอร์เซโกวีนา',
    'tk': 'Bosniýa we Gertsegowina Federasiýasy',
    'tr': 'Bosna-Hersek Federasyonu',
    'uk': 'Федерація Боснія і Герцеговина',
    'ur': 'وفاق بوسنیا و ہرزیگووینا',
    'vi': 'Liên bang Bosna và Hercegovina',
    'zh': '波士尼亞與赫塞哥維納聯邦',
    'ceb': 'Federation of Bosnia and Herzegovina',
    'sr_Latn': 'Federacija Bosne i Hercegovine',
    'jv': 'Federasi Bosnia Herzegovina',
    'sq': 'Federata e Bosnjës dhe Hercegovinës',
    'ccp':
        '𑄜𑄬𑄓𑄢𑄬𑄥𑄧𑄚𑄴 𑄃𑄧𑄛𑄴 𑄝𑄧𑄌𑄴𑄚𑄨𑄠 𑄃𑄬𑄚𑄳𑄓𑄴 𑄦𑄢𑄴𑄎𑄮𑄉𑄧𑄞𑄨𑄚',
    'hy': 'Բոսնիա և Հերցեգովինա ֆեդերացիա',
    'kk': 'Босния және Герцеговина федерациясы',
    'bs': 'Federacija Bosne i Hercegovine',
    'mk': 'Федерација Босна и Херцеговина',
    'no': 'Føderasjonen av Bosnia og Hercegovina',
    'da': 'Føderationen af Bosnien og Hercegovina',
    'ky': 'Босния жана Герцеговина Федерациясы',
    'lv': 'Bosnijas un Hercegovinas Federācija'
  },
  type: 'entity',
);
const countrySubdivisionBIHBRC = CountrySubdivision(
  alpha2: 'BA',
  alpha3: 'BIH',
  code: 'BRC',
  name: 'Brčko Distrikt',
  unofficialNames: [],
  geo: null,
  translations: {
    'ar': 'مقاطعة برتشو',
    'be': 'Акруга Брчко',
    'bg': 'Бръчко',
    'bn': 'বাক্কু জেলা',
    'ca': 'Districte de Brčko',
    'cs': 'Brčko',
    'da': 'Brčko',
    'de': 'Distrikt Brčko',
    'el': 'Μπρσκο',
    'en': 'Brčko District',
    'es': 'Distrito de Brčko',
    'et': 'Brčko ringkond',
    'eu': 'Brčkoko Barrutia',
    'fi': 'Brčkon kaupunginosa',
    'fr': 'District de Brčko',
    'gl': 'Distrito de Brčko',
    'gu': 'બ્રકો જિલ્લો',
    'he': 'מחוז ברצ׳קו',
    'hi': 'ब्राको जिला',
    'hr': 'Brčko Distrikt Bosne i Hercegovine',
    'hu': 'Brčkói Körzet',
    'id': 'Distrik Brčko',
    'it': 'Distretto di Brčko',
    'ja': 'ブルチコ行政区',
    'ka': 'ბრჩკოს ოლქი',
    'kn': 'ಬ್ರೆಸ್ಕೊ ಜಿಲ್ಲೆ',
    'ko': '브르치코 행정구',
    'lt': 'Brčko apygarda',
    'lv': 'Brčko apgabals',
    'mr': 'ब्रँचको जिल्हा',
    'ms': 'Brcko District',
    'nb': 'Brčko-distriktet',
    'nl': 'Brčko',
    'pl': 'Dystrykt Brczko',
    'pt': 'Distrito de Brčko',
    'ro': 'Districtul Brčko',
    'ru': 'Округ Брчко',
    'si': 'බ්ර්කෝ දිස්ත්‍රික්කය',
    'sk': 'Dištrikt Brčko',
    'sr': 'Брчко Дистрикт',
    'sv': 'Brčko',
    'ta': 'ப்ரக்க்கோ மாவட்டம்',
    'te': 'బ్రకో జిల్లా',
    'th': 'เขตบรึชโก',
    'tk': 'Brçko etraby',
    'tr': 'Brçko Bölgesi',
    'uk': 'Округ Брчко',
    'ur': 'ضلع برچکو',
    'vi': 'Quận Brčko',
    'ceb': 'Brčko (entidad)',
    'sr_Latn': 'Brčko Distrikt',
    'zh': '布爾奇科特區',
    'fa': 'بخش برچکو',
    'jv': 'Distrik Brčko',
    'sq': 'Distrikti i Brçkos',
    'ccp': '𑄝𑄳𑄢𑄧𑄇𑄴𑄇𑄮 𑄎𑄬𑄣',
    'sl': 'Distrikt Brčko',
    'bs': 'Brčko Distrikt',
    'mk': 'Брчко',
    'no': 'Brčko-distriktet'
  },
  type: 'district_with_special_status',
);
const countrySubdivisionBIHSRP = CountrySubdivision(
  alpha2: 'BA',
  alpha3: 'BIH',
  code: 'SRP',
  name: 'Republika Srpska',
  unofficialNames: ['Republika Srpska'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: 44.7280186, longitude: 17.3148136),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: 45.2737124, longitude: 19.6256174),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: 42.5561996, longitude: 16.1924385)),
  translations: {
    'en': 'Republika Srpska',
    'ar': 'جمهورية صرب البوسنة',
    'az': 'Bosniya Serb Respublikası',
    'be': 'Рэспубліка Сербская',
    'bg': 'Република Сръбска',
    'bn': 'রেপুবলিকা সর্পস্কা',
    'ca': 'República Sèrbia',
    'cs': 'Republika srbská',
    'da': 'Republika Srpska',
    'de': 'Republika Srpska',
    'el': 'Σερβική Δημοκρατία',
    'es': 'República Srpska',
    'et': 'Serblaste Vabariik',
    'eu': 'Bosniako Serbiar Errepublika',
    'fa': 'جمهوری صرب بوسنی',
    'fi': 'Serbitasavalta',
    'fr': 'République serbe de Bosnie',
    'gl': 'República Serbia - Republika Srpska',
    'he': 'רפובליקה סרפסקה',
    'hr': 'Republika Srpska',
    'hu': 'Boszniai Szerb Köztársaság',
    'hy': 'Սերբական Հանրապետություն',
    'id': 'Republik Srpska',
    'it': 'Repubblica Serba di Bosnia ed Erzegovina',
    'ja': 'スルプスカ共和国',
    'ka': 'ბოსნიელთა რესპუბლიკა',
    'ko': '스릅스카 공화국',
    'lt': 'Serbų respublika',
    'lv': 'Serbu Republika',
    'mr': 'स्राप्स्काचे प्रजासत्ताक',
    'ms': 'Republika Srpska',
    'nb': 'Republika Srpska',
    'nl': 'Servische Republiek',
    'pl': 'Republika Serbska',
    'pt': 'República Sérvia',
    'ro': 'Republika Srpska',
    'ru': 'Республика Сербская',
    'sk': 'Republika srbská',
    'sl': 'Republika srbska',
    'sr': 'Република Српска',
    'sv': 'Republika Srpska',
    'ta': 'சிறுப்ஸ்கா குடியரசு',
    'th': 'สาธารณรัฐเซิร์ปสกา',
    'tk': 'Serb Respublikasy',
    'tr': 'Sırp Cumhuriyeti',
    'uk': 'Республіка Сербська',
    'ur': 'سرپسکا',
    'vi': 'Cộng hòa Srpska',
    'ceb': 'Republika Srpska',
    'yo_BJ': 'Sérbíà Orílɛ̀-èdè Olómìnira',
    'sr_Latn': 'Republika Srpska',
    'zh': '塞族共和國',
    'jv': 'Republika Srpska',
    'sq': 'Republika Serbe',
    'ccp': '𑄢𑄬𑄛𑄛𑄴𑄣𑄨𑄇 𑄃𑄬𑄌𑄴𑄃𑄢𑄴𑄛𑄨𑄃𑄨𑄌𑄴𑄇𑄳𑄃',
    'ky': 'Серб Республикасы',
    'yo': 'Sérbíà Orílẹ̀-èdè Olómìnira',
    'bs': 'Republika Srpska',
    'mk': 'Република Српска',
    'no': 'Republika Srpska',
    'af': 'Serwiese Republiek',
    'my': 'ဆာ့ပ်စ်ကာသမ္မတနိုင်ငံ'
  },
  type: 'entity',
);
