import '../country_subdivision.dart';

const countrySubdivisionKMA = CountrySubdivision(
  countryCode: 'KM',
  code: 'A',
  name: 'Anjouan',
  unofficialNames: ['Anjouan', 'Ndzuwani', 'Nzwani'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -12.2138145, longitude: 44.4370606),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -12.069215, longitude: 44.5364756),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -12.3804607, longitude: 44.20471500000001)),
  translations: {
    'en': 'Anjouan',
    'ar': 'أنجوان',
    'az': 'Anjuan',
    'be': 'Востраў Анжуан',
    'bn': 'আঞ্জুয়ান',
    'ca': 'Anjouan',
    'cs': 'Nzwani',
    'da': 'Anjouan',
    'de': 'Anjouan',
    'el': 'Ανζουάν',
    'es': 'Anjouan',
    'et': 'Ndzwani',
    'eu': 'Anjouan',
    'fa': 'آنژوان',
    'fi': 'Anjouan',
    'fr': 'Anjouan',
    'gl': 'Anjouan',
    'gu': 'એન્જોઅન',
    'he': 'אנג׳ואן',
    'hi': 'अंजुअन',
    'hr': 'Anjouan',
    'hu': 'Anjouan',
    'id': 'Anjouan',
    'it': 'Anjouan',
    'ja': 'アンジュアン島',
    'ka': 'ნძუანი',
    'kn': 'ಅಂಜೌನ್',
    'ko': '앙주앙 섬',
    'lt': 'Anžuanas',
    'mr': 'अंजुआन',
    'ms': 'Anjouan',
    'nb': 'Anjouan',
    'nl': 'Anjouan',
    'pl': 'Anjouan',
    'pt': 'Anjouan',
    'ro': 'Anjouan',
    'ru': 'Анжуан',
    'si': 'අන්ජෝවාන්',
    'sr': 'Анжуан',
    'sv': 'Anjouan',
    'sw': 'Anjouan',
    'ta': 'அஞ்சொவன்',
    'te': 'అంజోవన్',
    'th': 'แอนโจแอน',
    'tr': 'Anjouan',
    'ur': 'انجوان',
    'vi': 'Anjouan',
    'zh': '昂儒昂岛',
    'lv': 'Anžuana',
    'ceb': 'Anjouan',
    'sr_Latn': 'Anžuan',
    'ccp': '𑄃𑄚𑄴𑄎𑄮𑄠𑄚𑄴',
    'uk': 'Анжуан',
    'no': 'Anjouan'
  },
  type: 'island',
);
const countrySubdivisionKMG = CountrySubdivision(
  countryCode: 'KM',
  code: 'G',
  name: 'Grande Comore',
  unofficialNames: ['Grande Comore', 'Njazídja'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -11.7167338, longitude: 43.3680788),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -11.3646394, longitude: 43.51371899999999),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -11.9393224, longitude: 43.2286278)),
  translations: {
    'en': 'Grande Comore',
    'ar': 'القمر الكبرى',
    'az': 'Qrand Komor',
    'be': 'Востраў Нгазіджа',
    'bn': 'গ্রান্ডে কোমোর',
    'ca': 'Grande Comore',
    'cs': 'Ngazidja',
    'da': 'Grande Comore',
    'de': 'Grande Comore',
    'el': 'Μεγάλη Κομόρα',
    'es': 'Gran Comora',
    'eu': 'Komora Handia',
    'fa': 'گرند کومور',
    'fi': 'Grande Comore',
    'fr': 'Grande Comore',
    'gl': 'Gran Comora',
    'gu': 'ગ્રાન્દે કોમોર',
    'he': 'גרנד קומורו',
    'hi': 'ग्रैंडे कोमोर',
    'hr': 'Grande Comore',
    'id': 'Komoro Besar',
    'it': 'Grande Comore',
    'ja': 'グランドコモロ島',
    'ka': 'ნგაზიჯა',
    'kn': 'ಗ್ರಾಂಡೆ ಕೊಮೊರ್',
    'ko': '그랑드코모르 섬',
    'lt': 'Grand Komoras',
    'mr': 'ग्रान्दे कोमोर',
    'ms': 'Grande Comore',
    'nb': 'Grande Comore',
    'nl': 'Grande Comore',
    'pl': 'Wielki Komor',
    'pt': 'Grande Comore',
    'ru': 'Нгазиджа',
    'si': 'ග්‍රන්ඩේ කොමෝර්',
    'sr': 'Велики Комори',
    'sv': 'Grande Comore',
    'sw': 'Ngazija',
    'ta': 'கிராண்டே காமோரே',
    'te': 'గ్రాండ్ కోమోర్',
    'th': 'เกาะกร็องด์กอมอร์',
    'tr': 'Grande Comore',
    'uk': 'Великий Комор',
    'ur': 'قمر الکبری',
    'vi': 'Grande Comore',
    'lv': 'Nazidža (Grankomora)',
    'ceb': 'Grande Comore',
    'sr_Latn': 'Veliki Komori',
    'zh': '大科摩罗岛',
    'ccp': '𑄉𑄳𑄢𑄚𑄳𑄓𑄴 𑄇𑄮𑄟𑄢𑄴',
    'no': 'Grande Comore',
    'ha': 'Grande Comore',
    'ha_NE': 'Grande Comore'
  },
  type: 'island',
);
const countrySubdivisionKMM = CountrySubdivision(
  countryCode: 'KM',
  code: 'M',
  name: 'Mohéli',
  unofficialNames: ['Mohilla', 'Mohéli', 'Moili'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -12.3377376, longitude: 43.7334089),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -12.2490952, longitude: 43.8763046),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -12.3899703, longitude: 43.6219025)),
  translations: {
    'en': 'Mohéli',
    'ar': 'موهيلي',
    'az': 'Moheli',
    'be': 'Востраў Мвалі',
    'bn': 'মুহেলি',
    'ca': 'Mohéli',
    'cs': 'Mwali',
    'da': 'Mohéli',
    'de': 'Mohéli',
    'el': 'Μοελί',
    'es': 'Mohéli',
    'eu': 'Moheli',
    'fi': 'Mohéli',
    'fr': 'Mohéli',
    'gl': 'Mohéli',
    'gu': 'મોહેલી',
    'he': 'מוהלי',
    'hi': 'मोहली',
    'hr': 'Mohéli',
    'id': 'Mohéli',
    'it': 'Mohéli',
    'ja': 'モヘリ島',
    'ka': 'მვალი',
    'kn': 'ಮೊಹೆಲಿ',
    'ko': '모엘리 섬',
    'lt': 'Mohelis',
    'mr': 'मोहीलि',
    'ms': 'Mohéli',
    'nb': 'Mohéli',
    'nl': 'Mohéli',
    'pl': 'Mohéli',
    'pt': 'Mohéli',
    'ro': 'Mohéli',
    'ru': 'Мвали',
    'si': 'මොහේලි',
    'sr': 'Мохели',
    'sv': 'Mohéli',
    'sw': 'Moheli',
    'ta': 'மொஹெலி',
    'te': 'మోహేలీ',
    'th': 'มอเอลี',
    'tr': 'Moheli',
    'ur': 'موہیلی',
    'vi': 'Mohéli',
    'lv': 'Mvali',
    'ceb': 'Mwali (distrito)',
    'sr_Latn': 'Moheli',
    'zh': '莫埃利島',
    'ccp': '𑄟𑄧𑄦𑄬𑄣𑄨',
    'uk': 'Мохелі',
    'no': 'Mohéli',
    'fa': 'موهلی',
    'hu': 'Mohéli'
  },
  type: 'island',
);
