import '../country_subdivision.dart';

const countrySubdivisionSHAc = CountrySubdivision(
  countryCode: 'SH',
  code: 'AC',
  name: 'Ascension',
  unofficialNames: ['Ascension'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -7.946716599999999, longitude: -14.3559158),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -7.888888, longitude: -14.2954026),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -7.9922519, longitude: -14.4202423)),
  translations: {
    'en': 'Ascension Island',
    'af': 'Ascension',
    'ar': 'جزيرة أسينشين',
    'az': 'Askenson adası',
    'be': 'Востраў Ушэсця',
    'bg': 'Възнесение',
    'bn': 'আসেনশন দ্বীপ',
    'ca': 'Illa de l’Ascensió',
    'cs': 'Ascension',
    'da': 'Ascension',
    'de': 'Ascension',
    'el': 'Νήσος Αναλήψεως',
    'es': 'Isla Ascensión',
    'et': 'Ascension',
    'eu': 'Ascension Uhartea',
    'fa': 'اسنشن',
    'fi': 'Ascension',
    'fr': 'île de l’Ascension',
    'gl': 'Illa de Ascensión',
    'gu': 'એસેન્શન આઇલેન્ડ',
    'he': 'אסנשן',
    'hi': 'असेन्शियन द्वीप',
    'hr': 'Otok Ascension',
    'hu': 'Ascension-sziget',
    'hy': 'Համբարձման կղզի',
    'id': 'Ascension',
    'it': 'Isola di Ascensione',
    'ja': 'アセンション島',
    'ka': 'ამაღლების კუნძული',
    'kn': 'ಅಸೆನ್ಶನ್ ದ್ವೀಪ',
    'ko': '어센션 섬',
    'lt': 'Dangun Žengimo sala',
    'lv': 'Debesbraukšanas sala',
    'ml': 'അസെൻഷൻ ദ്വീപ്',
    'mr': 'असेन्शन द्वीप',
    'ms': 'Pulau Ascension',
    'nb': 'Ascension',
    'nl': 'Ascension',
    'or': 'ଆସେନ୍ସନ ଦ୍ଵୀପ',
    'pl': 'Wyspa Wniebowstąpienia',
    'pt': 'Ilha de Ascensão',
    'ro': 'Ascension',
    'ru': 'Остров Вознесения',
    'si': 'අස්සෙන්ෂන් දුපත',
    'sk': 'Ascension',
    'sl': 'Ascension',
    'sr': 'Асенсион',
    'sv': 'Ascension',
    'ta': 'அசென்சன் தீவு',
    'te': 'అసెన్షన్ దీవులు',
    'th': 'อัสเซนชัน',
    'tr': 'Ascension Adası',
    'uk': 'Острів Вознесіння',
    'ur': 'جزیرہ اسینشن',
    'vi': 'Đảo Ascension',
    'zh': '阿森松岛',
    'cy': 'Ynys Ascension',
    'ceb': 'Ascension Island',
    'yo_BJ': 'Erékùshù Ascension',
    'sr_Latn': 'Asension',
    'yue_Hans': '亚森松岛',
    'jv': 'Pulo Ascension',
    'ccp': '𑄃𑄌𑄴𑄥𑄬𑄚𑄴𑄥𑄨𑄠𑄧𑄚𑄴 𑄃𑄨𑄌𑄴𑄣𑄳𑄠𑄚𑄳𑄓𑄴',
    'ga': 'Oileán na Deascabhála',
    'ig': 'Ascension Island',
    'kk': 'Әскенжін Аралы',
    'yue': '亞森松島',
    'yo': 'Erékùṣù Ascension',
    'uz': 'Vozneseniye oroli',
    'bs': 'Ascension',
    'mk': 'Вознесение',
    'no': 'Ascension',
    'pa': 'ਅਸੈਂਸ਼ਨ',
    'sw': 'Ascension'
  },
  type: 'geographical_entity',
);
const countrySubdivisionSHHl = CountrySubdivision(
  countryCode: 'SH',
  code: 'HL',
  name: 'Saint Helena',
  unofficialNames: [],
  geo: null,
  translations: {
    'af': 'Sint Helena',
    'am': 'ሴይንት ህሊና ደሴት',
    'ar': 'سانت هيلينا',
    'az': 'Müqəddəs Yelena adası',
    'be': 'Востраў Святой Алены',
    'bg': 'Света Елена',
    'bn': 'সেন্ট হেলেনা',
    'ca': 'Santa Helena',
    'cs': 'Svatá Helena',
    'da': 'Sankt Helena',
    'de': 'St. Helena',
    'el': 'Νήσος Αγίας Ελένης',
    'en': 'Saint Helena',
    'es': 'Isla Santa Elena',
    'et': 'Saint Helena',
    'eu': 'Santa Helena',
    'fa': 'سینت هلینا',
    'fi': 'Saint Helena',
    'fr': 'Sainte-Hélène',
    'gl': 'Santa Helena',
    'gu': 'સેન્ટ હેલેના',
    'he': 'סנט הלנה',
    'hi': 'सन्त हेलेना',
    'hr': 'Sveta Helena',
    'hu': 'Szent Ilona',
    'hy': 'Սուրբ Հեղինեի կղզի',
    'id': 'Saint Helena',
    'is': 'Sankti Helena',
    'it': 'Sant’Elena',
    'ja': 'セントヘレナ',
    'ka': 'წმინდა ელენეს კუნძული',
    'kn': 'ಸೇಂಟ್ ಹೆಲೆನಾ',
    'ko': '세인트헬레나',
    'lt': 'Šv. Elenos sala',
    'lv': 'Svētās Helēnas Sala',
    'ml': 'സൈന്റ് ഹെലേന',
    'mr': 'सेंट हेलेना',
    'ms': 'Saint Helena',
    'nb': 'St. Helena',
    'nl': 'Sint-Helena',
    'pl': 'Wyspa Świętej Heleny',
    'pt': 'Santa Helena',
    'ro': 'Insula Sfânta Elena',
    'ru': 'Остров Святой Елены',
    'si': 'ශාන්ත හෙලේනා',
    'sk': 'Svätá Helena',
    'sl': 'Sveta Helena',
    'sr': 'Света Јелена',
    'sv': 'Sankta Helena',
    'sw': 'Saint Helena',
    'ta': 'செயிண்ட் எலனா',
    'te': 'సెయింట్ హెలెనా',
    'th': 'เซนต์เฮเลนา',
    'tr': 'Saint Helena',
    'uk': 'Острів Святої Єлени',
    'ur': 'سینٹ ہلینا',
    'vi': 'Saint Helena',
    'cy': 'Saint Helena',
    'sr_Latn': 'Sveta Jelena',
    'zh': '圣赫勒拿岛',
    'yue_Hans': '圣海伦娜岛',
    'jv': 'Saint Helena',
    'sq': 'Ishulli Shën Elena',
    'ccp': '𑄥𑄬𑄚𑄴𑄑𑄴 𑄦𑄬𑄣𑄬𑄚',
    'ga': 'San Héilin',
    'ig': 'Saint Helena',
    'pa': 'ਸੇਂਟ ਹੇਲੇਨਾ',
    'kk': 'Сент-Хелена',
    'yue': '聖海倫娜島',
    'yo': 'Saint Helena',
    'bs': 'Sveta Helena',
    'mk': 'Света Елена',
    'no': 'St. Helena',
    'yo_BJ': 'Saint Helena',
    'ceb': 'Saint Helena Island',
    'ky': 'Ыйык Елена аралы',
    'ps': 'سنت هلن'
  },
  type: 'geographical_entity',
);
const countrySubdivisionSHTa = CountrySubdivision(
  countryCode: 'SH',
  code: 'TA',
  name: 'Tristan da Cunha',
  unofficialNames: ['Tristan da Cunha'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -37.1052489, longitude: -12.2776838),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -37.0621779, longitude: -12.2167732),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -37.1702333, longitude: -12.3511792)),
  translations: {
    'en': 'Tristan da Cunha',
    'ccp': '𑄑𑄳𑄢𑄨𑄌𑄴𑄑𑄚𑄴 𑄓 𑄇𑄪𑄚𑄴𑄦',
    'ja': 'トリスタンダクーニャ'
  },
  type: 'geographical_entity',
);
