import '../country_subdivision.dart';

const countrySubdivisionSTP01 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '01',
  name: 'Água Grande',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Água Grande',
    'ar': 'مقاطعة أجوا غراندي',
    'bg': 'Агуа Гранде',
    'ca': 'Água Grande',
    'ceb': 'Água Grande District',
    'da': 'Água Grande',
    'de': 'Água Grande',
    'es': 'Distrito de Água Grande',
    'fr': 'district d’Água Grande',
    'gl': 'Distrito de Água Grande',
    'id': 'Distrik Água Grande',
    'it': 'Distretto di Água Grande',
    'ja': 'アグア・グランデ県',
    'ka': 'აგუა-გრანდე',
    'ko': '아구아그란드현',
    'mk': 'Агва Гранде',
    'nl': 'Água Grande',
    'pl': 'Água Grande',
    'pt': 'Água Grande',
    'ru': 'Агуа-Гранде',
    'sr': 'Агва Гранде',
    'sr_Latn': 'Agva Grande',
    'sv': 'Água Grande',
    'uk': 'Агуа-Гранде',
    'zh': '阿瓜格蘭德縣'
  },
  type: 'district',
);
const countrySubdivisionSTP02 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '02',
  name: 'Cantagalo',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Cantagalo',
    'ar': 'مقاطعة كانتاغالو',
    'bg': 'Кантагало',
    'ca': 'Cantagalo',
    'ceb': 'Cantagalo District',
    'de': 'Cantagalo',
    'es': 'Distrito de Cantagalo',
    'fr': 'district de Cantagalo',
    'id': 'Distrik Cantagalo',
    'it': 'Distretto di Cantagalo',
    'ja': 'カンタガロ県',
    'ka': 'კანტაგალუ',
    'ko': '칸타갈루현',
    'mk': 'Кантагало',
    'nl': 'Cantagalo',
    'pt': 'Cantagalo (São Tomé e Príncipe)',
    'ru': 'Кантагалу',
    'sr': 'Кантагало',
    'sr_Latn': 'Kantagalo',
    'sv': 'Cantagalo',
    'uk': 'Кантагалу'
  },
  type: 'district',
);
const countrySubdivisionSTP03 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '03',
  name: 'Caué',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Caué',
    'ar': 'مقاطعة كاوي',
    'bg': 'Кауе',
    'ca': 'Caué',
    'de': 'Caué',
    'es': 'Distrito de Caué',
    'fr': 'district de Caué',
    'id': 'Distrik Caué',
    'it': 'Distretto di Caué',
    'ja': 'カウエ県',
    'ka': 'კაუი',
    'ko': '카우에현',
    'mk': 'Кауе',
    'nl': 'Caué',
    'pt': 'Caué',
    'ru': 'Кауи',
    'sr': 'Каје',
    'sr_Latn': 'Kaje',
    'sv': 'Caué',
    'uk': 'Кауї'
  },
  type: 'district',
);
const countrySubdivisionSTP04 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '04',
  name: 'Lembá',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Lembá',
    'ar': 'مقاطعة ليمبا',
    'bg': 'Лемба',
    'ca': 'Lembá',
    'ceb': 'Lemba District',
    'de': 'Lembá',
    'es': 'Distrito de Lembá',
    'fr': 'district de Lembá',
    'id': 'Distrik Lembá',
    'it': 'Distretto di Lembá',
    'ja': 'レンバ県',
    'ka': 'ლემბა',
    'ko': '렘바현',
    'mk': 'Лемба',
    'ml': 'ലെംബ ജില്ല',
    'nl': 'Lembá',
    'pl': 'Lembá',
    'pt': 'Lembá',
    'ru': 'Лемба',
    'sr': 'Лемба',
    'sr_Latn': 'Lemba',
    'sv': 'Lembá',
    'uk': 'Лемба'
  },
  type: 'district',
);
const countrySubdivisionSTP05 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '05',
  name: 'Lobata',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Lobata',
    'ar': 'مقاطعة لوبانا',
    'bg': 'Лобата',
    'ca': 'Lobata',
    'ceb': 'Lobata District',
    'de': 'Lobata',
    'es': 'Distrito de Lobata',
    'fr': 'district de Lobata',
    'id': 'Distrik Lobata',
    'it': 'distretto di Lobata',
    'ja': 'ロバタ県',
    'ka': 'ლობატა',
    'ko': '로바타현',
    'mk': 'Лобата',
    'nl': 'Lobata',
    'pt': 'Lobata',
    'ru': 'Лобата',
    'sr': 'Лобата',
    'sr_Latn': 'Lobata',
    'sv': 'Lobata',
    'uk': 'Лобата'
  },
  type: 'district',
);
const countrySubdivisionSTP06 = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: '06',
  name: 'Mé-Zóchi',
  unofficialNames: [],
  geo: null,
  translations: {
    'en': 'Mé-Zóchi',
    'ar': 'مقاطعة مي زوتشي',
    'bg': 'Ме-Зоши',
    'ca': 'Mé-Zóchi',
    'ceb': 'Mé-Zóchi District',
    'de': 'Mé-Zóchi',
    'es': 'Distrito de Mé-Zóchi',
    'fr': 'district de Mé-Zóchi',
    'id': 'Distrik Mé-Zóchi',
    'it': 'Distretto di Mé-Zóchi',
    'ja': 'メ＝ゾシ県',
    'ka': 'მი-სოჩი',
    'ko': '메조시현',
    'mk': 'Ме-Зочи',
    'nl': 'Mé-Zóchi',
    'pt': 'Mé-Zóchi',
    'ru': 'Ми-Сочи',
    'sr': 'Ме-Зочи',
    'sr_Latn': 'Me-Zoči',
    'sv': 'Mé-Zóchi',
    'uk': 'Мі-Зочі'
  },
  type: 'district',
);
const countrySubdivisionSTPP = CountrySubdivision(
  alpha2: 'ST',
  alpha3: 'STP',
  code: 'P',
  name: 'Príncipe',
  unofficialNames: ['Príncipe'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: 1.6139381, longitude: 7.4056928),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: 1.6929356, longitude: 7.462463499999999),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: 1.35852, longitude: 7.2647591)),
  translations: {
    'en': 'Príncipe',
    'ca': 'Regió Autònoma de Príncipe',
    'fi': 'Príncipe',
    'fr': 'province de Principe',
    'it': 'Provincia di Príncipe',
    'ja': 'プリンシペ州',
    'nb': 'Príncipe',
    'pt': 'Príncipe',
    'ur': 'پرنسپے صوبہ',
    'ccp': '𑄛𑄳𑄢𑄨𑄚𑄴𑄥𑄨𑄛𑄴',
    'ka': 'პრინსიპის პროვინცია',
    'mk': 'Принсипе',
    'no': 'Príncipe',
    'ceb': 'Príncipe',
    'cy': 'Talaith Príncipe'
  },
  type: 'autonomous_region',
);
