import '../country_subdivision.dart';

const countrySubdivisionTO01 = CountrySubdivision(
  countryCode: 'TO',
  code: '01',
  name: '\'Eua',
  unofficialNames: ['Middleburg Island', 'ʿEua'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -21.3631956, longitude: -174.9297206),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -21.2833727, longitude: -174.9043558),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -21.455057, longitude: -174.9722574)),
  translations: {
    'en': 'ʻEua',
    'bn': 'ইঊয়া',
    'ca': '‘Eua',
    'da': 'Eua',
    'de': 'ʻEua',
    'el': 'Έουα',
    'es': '‘Eua',
    'fa': 'ائوآ',
    'fi': 'ʻEua',
    'gl': '‘Eua',
    'gu': 'ઇઆ',
    'hi': 'युआ',
    'id': 'ʻEua',
    'ja': 'エウア島',
    'ka': 'ეუა',
    'kn': 'ಯುವಾ',
    'ko': '에우아 섬',
    'mr': 'ईआ',
    'ms': 'ʻEua',
    'nl': '‘Eua',
    'pl': 'ʻEua',
    'pt': 'ʻEua',
    'ru': 'Эуа',
    'si': 'ඉයුවා',
    'sv': '‘Eua',
    'te': 'యూవా',
    'th': 'เออัว',
    'tr': 'Eua',
    'uk': 'Еуа (острів)',
    'ur': 'یوا',
    'vi': 'Eua',
    'zh': '埃瓦島',
    'lv': 'Euva',
    'ceb': 'Eua',
    'lt': 'Eva',
    'ccp': '𑄃𑄨𑄅𑄪𑄠'
  },
  type: 'division',
);
const countrySubdivisionTO02 = CountrySubdivision(
  countryCode: 'TO',
  code: '02',
  name: 'Ha\'apai',
  unofficialNames: ['Ha\'apai'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -19.7506337, longitude: -175.0545197),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -19.5930023, longitude: -174.268463),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -20.5583992, longitude: -175.417755)),
  translations: {
    'en': 'Haʻapai',
    'ar': 'هاباي',
    'ca': 'Ha’apai',
    'da': 'Haʻapai',
    'de': 'Haʻapai',
    'el': 'Χαγιαπέι',
    'es': 'Grupo Gálvez',
    'fa': 'هاآپایی',
    'fi': 'Haʻapai',
    'fr': 'Ha’apai',
    'gl': 'Ha’apai',
    'gu': 'હાપેઇ',
    'hi': 'हापाई',
    'id': 'Haʻapai',
    'it': 'Haʻapai',
    'ja': 'ハアパイ諸島',
    'ka': 'ჰააპაის კუნძულები',
    'kn': 'ಹ್ಯಾಪಾಯಿ',
    'ko': '하파이 제도',
    'lt': 'Ha’apai',
    'mr': 'हापाई',
    'ms': 'Haʻapai',
    'nb': 'Ha’apai',
    'nl': 'Ha’apai',
    'pl': 'Archipelag Ha’apai',
    'pt': 'Ha’apai',
    'ru': 'Острова Хаапай',
    'si': 'හා ‘අපායි',
    'sv': 'Ha’apai',
    'te': 'హా‘అపేయ్',
    'th': 'ฮาอะไป',
    'tr': 'Haʻapai',
    'uk': 'Хаʼапаї (острови)',
    'ur': 'ہآپائی',
    'vi': 'Haʻapai',
    'lv': 'Haapai',
    'ceb': 'Ha‘apai',
    'zh': '哈派群島',
    'bn': 'হা‘আপাই',
    'ccp': '𑄦‘𑄃𑄬𑄛𑄭',
    'no': 'Ha’apai'
  },
  type: 'division',
);
const countrySubdivisionTO03 = CountrySubdivision(
  countryCode: 'TO',
  code: '03',
  name: 'Niuas',
  unofficialNames: ['Niuas'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -15.6097616, longitude: -175.6332093),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -15.5663927, longitude: -173.7024841),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -15.9637832, longitude: -175.6796157)),
  translations: {
    'en': 'Niuas',
    'ar': 'نيواس',
    'bn': 'নিউয়াস',
    'ca': 'Niuas',
    'da': 'Niuas',
    'de': 'Niuas',
    'el': 'Νιούας',
    'es': 'Grupo Niuas',
    'fi': 'Niuas',
    'fr': 'Niuas',
    'gl': 'Grupo Niuas',
    'gu': 'નિઉઆસ',
    'hi': 'निउआस',
    'id': 'Niuas',
    'it': 'Niuas',
    'ja': 'ニウアス諸島',
    'ka': 'ნიუასის კუნძულები',
    'kn': 'ನಿಯೋವಾಸ್',
    'ko': '니우아스 제도',
    'mr': 'निऊअसं',
    'ms': 'Niuas',
    'nb': 'Niuas',
    'nl': 'Niuas',
    'pl': 'Niuas',
    'pt': 'Niuas',
    'ru': 'Острова Ниуас',
    'si': 'නියුවාස්',
    'sv': 'Niuas',
    'ta': 'னியஸ்',
    'te': 'నియువస్',
    'th': 'นีอูอาส',
    'tr': 'Niuas',
    'uk': 'Ніуас (острови)',
    'ur': 'نیواس',
    'vi': 'Niuas',
    'lv': 'Niuasa',
    'ceb': 'Niuas',
    'lt': 'Niuasas',
    'zh': '紐阿斯群島',
    'ccp': '𑄚𑄨𑄅𑄪𑄠𑄌𑄴',
    'no': 'Niuas',
    'fa': 'جزایر نیوآ'
  },
  type: 'division',
);
const countrySubdivisionTO04 = CountrySubdivision(
  countryCode: 'TO',
  code: '04',
  name: 'Tongatapu',
  unofficialNames: ['Tongatapu'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -21.1465968, longitude: -175.2515482),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -21.061676, longitude: -175.0285149),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -21.278193, longitude: -175.3613689)),
  translations: {
    'en': 'Tongatapu',
    'ar': 'تونغاتابو',
    'be': 'Востраў Тангатапу',
    'bn': 'টোঙ্গাটাপু',
    'ca': 'Tongatapu',
    'da': 'Tongatapu',
    'de': 'Tongatapu',
    'el': 'Τονγκατάπου',
    'es': 'Tongatapu',
    'fa': 'تونگاتاپو',
    'fi': 'Tongatapu',
    'fr': 'Tongatapu',
    'gl': 'Tongatapu',
    'gu': 'ટોંગાટાપુ',
    'he': 'נוקואלופה',
    'hi': 'टोंगटापू',
    'id': 'Tongatapu',
    'it': 'Tongatapu',
    'ja': 'トンガタプ島',
    'ka': 'ტონგატაპუ',
    'kn': 'ಟೋಂಗಟಾಪು',
    'ko': '통가타푸 섬',
    'lt': 'Tongatapu',
    'mr': 'टोंगाटापू',
    'ms': 'Tongatapu',
    'nb': 'Tongatapu',
    'nl': 'Tongatapu',
    'pl': 'Tongatapu',
    'pt': 'Tongatapu',
    'ro': 'Tongatapu',
    'ru': 'Тонгатапу',
    'si': 'ටොන්ගටපු',
    'sv': 'Tongatapu',
    'ta': 'தொங்கட்டாப்பு',
    'te': 'టోంగాటాపు',
    'th': 'โตงาตาปู',
    'tr': 'Tongatapu',
    'uk': 'Тонгатапу (острови)',
    'ur': 'ٹونگاٹاپو',
    'vi': 'Tongatapu',
    'ceb': 'Tongatapu',
    'zh': '汤加塔布岛',
    'ccp': '𑄑𑄧𑄁𑄉𑄑𑄛𑄪',
    'no': 'Tongatapu'
  },
  type: 'division',
);
const countrySubdivisionTO05 = CountrySubdivision(
  countryCode: 'TO',
  code: '05',
  name: 'Vava\'u',
  unofficialNames: ['Vava\'u'],
  geo: CountrySubdivisionGeoData(
      coordinate: CountrySubdivisionCoordinate(
          latitude: -18.5811962, longitude: -173.985008),
      maxCoordinate: CountrySubdivisionCoordinate(
          latitude: -18.0082895, longitude: -173.907578),
      minCoordinate: CountrySubdivisionCoordinate(
          latitude: -19.180176, longitude: -174.8671875)),
  translations: {
    'en': 'Vavaʻu',
    'ar': 'فافاو',
    'bg': 'Вавау',
    'bn': 'ভাভাউ',
    'ca': 'Vava’u',
    'da': 'Vavaʻu',
    'de': 'Vava’u',
    'el': 'Βαβάου',
    'es': 'Vava’u',
    'fa': 'جزیره واوائو',
    'fi': 'Vavaʻu',
    'fr': 'Vava’u',
    'gl': 'Grupo Vava’u',
    'gu': 'વાવાઉ',
    'hi': 'वावाउ',
    'id': 'Vava’u',
    'it': 'Vava’u',
    'ja': 'ヴァヴァウ諸島',
    'ka': 'ვავაუს კუნძულები',
    'kn': 'ವವಾವು',
    'ko': '바바우 제도',
    'lt': 'Vava’u',
    'mr': 'वावाऊ',
    'ms': 'Vavaʻu',
    'nb': 'Vava’u',
    'nl': 'Vava’u',
    'pl': 'Vava’u',
    'pt': 'Vava’u',
    'ru': 'Вавау',
    'si': 'වවා ‘උ',
    'sv': 'Vava’u',
    'te': 'వావాయు',
    'th': 'วาวาอู',
    'tr': 'Vava’u',
    'uk': 'Ваваʼу',
    'ur': 'واواؤ',
    'vi': 'Vavaʻu',
    'lv': 'Vavaʻu',
    'ceb': 'Vava‘u',
    'zh': '瓦瓦烏群島',
    'ccp': '𑄞𑄞‘𑄅𑄪',
    'no': 'Vava’u'
  },
  type: 'division',
);
