import '../country.dart';

const countryARE = Country(
  alpha2: 'AE',
  alpha3: 'ARE',
  continent: Continent.asia,
  countryCode: '971',
  currencyCode: 'AED',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'AE',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 23.424076,
      longitude: 53.847818,
    ),
    maxCoordinate: Coordinate(
      latitude: 26.0765,
      longitude: 56.4395001,
    ),
    minCoordinate: Coordinate(
      latitude: 22.6315138,
      longitude: 51.4723,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 26.0765,
        longitude: 56.4395001,
      ),
      southwest: Coordinate(
        latitude: 22.6315138,
        longitude: 51.4723,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'UAE',
  isoLongName: 'The United Arab Emirates',
  isoShortName: 'United Arab Emirates',
  isoShortNameLowerCase: 'United Arab Emirates (the)',
  languagesOfficial: ['ar'],
  languagesSpoken: ['ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8, 9],
  nationalPrefix: '0',
  nationality: 'Emirian',
  number: '784',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Western Asia',
  unLocode: 'AE',
  unMember: true,
  unofficialNames: [
    'United Arab Emirates',
    'الإمارات العربية المتحدة',
    'Vereinigte Arabische Emirate',
    'Émirats Arabes Unis',
    'Emiratos Árabes Unidos',
    'アラブ首長国連邦',
    'Verenigde Arabische Emiraten'
  ],
  vehicleRegistrationCode: 'UAE',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 5,
    reduced: [],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'United Arab Emirates',
    'af': 'Verenigde Arabiese Emirate',
    'ak': 'United Arab Emirates',
    'am': 'ፘተባበሩት ጐረብ ጔሤሳትስ',
    'an': 'Emiratos Arabes Unius',
    'ar': 'الإمارات العربيّة المتّحدة',
    'as': 'ইউনাইটেড আৰৱ ইমিৰেটছ',
    'ay': 'United Arab Emirates',
    'az': 'Birləşmiş Ərəb Əmirlikləri',
    'ba': 'United Arab Emirates',
    'be': 'Аб\'яднаныя Арабскія Эміраты',
    'bg': 'Обединени арабски емирства',
    'bi': 'United Arab Emirates',
    'bn': 'সংযুক্ত আরব আমিরশাহী',
    'bn_IN': 'সংযুক্ত আরব আমিরশাহী',
    'br': 'Emirelezhioù Arab Unanet',
    'bs': 'Ujedinjeni Arapski Emirati',
    'ca': 'Unió dels Emirats Àrabs',
    'ce': 'Iаьрбийн Цхьаьнакхетта Эмираташ',
    'ch': 'United Arab Emirates',
    'cs': 'Spojené arabské emiráty',
    'cv': 'Iаьрбийн Цхьаьнакхетта Эмираташ',
    'cy': 'Emiriaethau Arabaidd Unedig',
    'da': 'Forenede Arabiske Emirater',
    'de': 'Vereinigte Arabische Emirate',
    'dv': 'އެކުވެރި ޢަރަބި އިމާރާތު',
    'dz': 'ཡུ་ནའི་ཊེཊ་ ཨ་རབ་ ཨི་མི་རེཊིསི།',
    'ee': 'United Arab Emirates',
    'el': 'Ηνωμένα Αραβικά Εμιράτα',
    'en': 'United Arab Emirates',
    'eo': 'Unuiĝintaj Arabaj Emirlandoj',
    'es': 'Emiratos Árabes Unidos',
    'et': 'Araabia Ühendemiraadid',
    'eu': 'Arabiar Emirerri Batuak',
    'fa': 'امارات متحده عربی',
    'ff': 'United Arab Emirates',
    'fi': 'Yhdistyneet arabiemiirikunnat',
    'fo': 'Sameindu arabisku emiratini',
    'fr': 'Émirats arabes unis',
    'fy': 'Feriene Arabyske Emiraten',
    'ga': 'Aontas na nÉimíríochtaí Arabacha',
    'gl': 'Emiratos Árabes Unidos',
    'gn': 'United Arab Emirates',
    'gu': 'યુનાઇટેડ આરબ અમીરાત',
    'gv': 'Ny h-Emmiraidyn Arabagh Unnaneysit',
    'ha': 'Taraiyar larabawa',
    'he': 'איחוד האמירויות הערביות',
    'hi': 'संयुक्त अरब अमीरात',
    'hr': 'Ujedinjeni Arapski Emirati',
    'ht': 'Emira Arab Ini',
    'hu': 'Egyesült Arab Emírségek',
    'hy': 'Միացյալ Արաբական Էմիրաթներ',
    'ia': 'Emiratos Arabe Unite',
    'id': 'Uni Emirat Arab',
    'io': 'Unionita Araba Emirati',
    'is': 'Sameinuðu arabísku furstadæmin',
    'it': 'Emirati Arabi Uniti',
    'iu': 'United Arab Emirates',
    'ja': 'アラブ首長国連邦',
    'ka': 'არაბეთის გაერთიანებული ემირატები',
    'ki': 'United Arab Emirates',
    'kk': 'Біріккен Араб Әмірліктері',
    'kl': 'United Arab Emirates',
    'km': 'អារ៉ាប់​រួម',
    'kn': 'ಯುನೈಟೆಡ್ ಅರಬ್ ಎಮಿರೇಟ್ಸ್',
    'ko': '아랍에미리트',
    'ku': 'Mîrtiyên Ereb ên Yekbuyî',
    'kv': 'Ӧтувтчӧм Араб Эмиратъяс',
    'kw': 'Pennternasedh Unys Arabek',
    'ky': 'Бириккен Араб Эмирликтери',
    'lo': 'United Arab Emirates',
    'lt': 'Jungtiniai Arabų Emyratai',
    'lv': 'Apvienotie Arābu Emirāti',
    'mi': 'United Arab Emirates',
    'mk': 'Обединети арапски емирати',
    'ml': 'ഐക്യ അറബ് എമിറേറ്റുകള്‍',
    'mn': 'Арабын нэгдсэн имерат',
    'mr': 'संयुक्त अरब अमिराती',
    'ms': 'Emiriah Arab Bersatu',
    'mt': 'Emirati Għarab Maqgħuda',
    'my': 'အာရပ်စော်ဘွားများပြည်ထောင်စု',
    'na': 'Emireitit Arabiya',
    'nb': 'De forente arabiske emirater',
    'ne': 'संयुक्त अरब इमिरेट्स',
    'nl': 'Verenigde Arabische Emiraten',
    'nn': 'Dei sameinte arabiske emirata',
    'nv': 'Ásáí Dineʼé Bikéyah Yázhí Ałhidadiidzooígíí',
    'oc': 'Emirats Arabs Units',
    'or': 'ସଂଯୁକ୍ତ ଆରବ ଏମିରେଟ',
    'pa': 'ਸੰਯੁਕਤ ਰਾਜ ਅਮੀਰਾਤ',
    'pi': 'United Arab Emirates',
    'pl': 'Zjednoczone Emiraty Arabskie',
    'ps': 'عربي متحده امارات',
    'pt': 'Emirados Árabes Unidos',
    'pt_BR': 'Emirados Árabes Unidos',
    'ro': 'Emiratele Arabe Unite',
    'ru': 'Объединённые Арабские Эмираты',
    'rw': 'Repubulika Nyarabu Zunze Ubumwe',
    'sc': 'Emiratos Àrabos Unidos',
    'sd': 'گڏيل عرب امارات',
    'si': 'එක්සත් අරාබි එමීර්',
    'sk': 'Spojené arabské emiráty',
    'sl': 'Združeni Arabski emirati',
    'so': 'Imaaraadka Carabta ee Midoobay',
    'sq': 'Emiratet e Bashkuara Arabe',
    'sr': 'Уједињени Арапски Емирати',
    'sv': 'Förenade Arabemiraten',
    'sw': 'Falme za Kiarabu',
    'ta': 'ஐக்கிய அராபிய எமிரேட்சு',
    'te': 'యునైటెడ్ అరబ్ ఎమిరేట్స్',
    'tg': 'Амороти Муттаҳидаи Араб',
    'th': 'สหรัฐอาหรับเอมิเรตส์',
    'ti': 'የተባበሩት አረብ ኤምሬትስ',
    'tk': 'Birleşen Arap Emirlikleri',
    'tl': 'Mga Pinag-isang Arabong Emirado',
    'tr': 'Birleşik Arap Emirlikleri',
    'tt': 'Берләшкән Гәрәп Әмирлекләре',
    'ug': 'ئەرەب بىرلەشمە خەلىپىلىكى',
    'uk': 'Об’єднані Арабські Емірати',
    'ur': 'متحدہ عرب امارات',
    'uz': 'Birlashgan Arab Amirliklari',
    've': 'United Arab Emirates',
    'vi': 'Các Tiểu Vương Quốc A-rập Thống Nhất',
    'wa': 'Emirats Arabes Unis',
    'wo': 'Imaarati Araab yu Bennoo',
    'xh': 'United Arab Emirates',
    'yo': 'Àwọn Ẹ́mírétì Árábù Aṣọ̀kan',
    'zh_CN': '阿联酋',
    'zh_HK': '阿拉伯聯合酋長國',
    'zh_TW': '阿拉伯聯合大公國',
    'zu': 'United Arab Emirates'
  },
);
