import '../country.dart';

const countryBEL = Country(
  alpha2: 'BE',
  alpha3: 'BEL',
  continent: Continent.europe,
  countryCode: '32',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'BE',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 50.503887,
      longitude: 4.469936,
    ),
    maxCoordinate: Coordinate(
      latitude: 51.5051449,
      longitude: 6.408124099999999,
    ),
    minCoordinate: Coordinate(
      latitude: 49.497013,
      longitude: 2.5240999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 51.5051449,
        longitude: 6.408124099999999,
      ),
      southwest: Coordinate(
        latitude: 49.497013,
        longitude: 2.5240999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'BEL',
  isoLongName: 'The Kingdom of Belgium',
  isoShortName: 'Belgium',
  isoShortNameLowerCase: null,
  languagesOfficial: ['nl', 'fr', 'de'],
  languagesSpoken: ['nl', 'fr', 'de'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9],
  nationalPrefix: '0',
  nationality: 'Belgian',
  number: '056',
  postalCode: true,
  postalCodeFormat: r'\d{4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Western Europe',
  unLocode: 'BE',
  unMember: true,
  unofficialNames: [
    'Belgium',
    'Belgien',
    'Belgique',
    'Bélgica',
    'ベルギー',
    'België'
  ],
  vehicleRegistrationCode: 'B',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 21.0,
    reduced: [6.0, 12.0],
    superReduced: null,
    parking: 12.0,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Belgium",
    "af": "België",
    "ak": "Belgium",
    "am": "ቤሔጄሤ",
    "an": "Belchica",
    "ar": "بلجيكا",
    "as": "বেলজিয়াম",
    "ay": "Belgium",
    "az": "Belçika",
    "ba": "Belgium",
    "be": "Бельгія",
    "bg": "Белгия",
    "bi": "Belgium",
    "bn": "বেলজিয়াম",
    "bn_IN": "বেলজিয়াম",
    "br": "Belgia",
    "bs": "Belgija",
    "ca": "Bèlgica",
    "ce": "Бельги",
    "ch": "Belgium",
    "cs": "Belgie",
    "cv": "Бельги",
    "cy": "Gwlad Belg",
    "da": "Belgien",
    "de": "Belgien",
    "dv": "ބެލްޖިއަމް",
    "dz": "བེལ་ཇི་ཡམ།",
    "ee": "Belgium",
    "el": "Βέλγιο",
    "en": "Belgium",
    "eo": "Belgio",
    "es": "Bélgica",
    "et": "Belgia",
    "eu": "Belgika",
    "fa": "بلژیک",
    "ff": "Beljik",
    "fi": "Belgia",
    "fo": "Belgia",
    "fr": "Belgique",
    "fy": "Belgje",
    "ga": "An Bheilg",
    "gl": "Bélxica",
    "gn": "Belgium",
    "gu": "બેલ્જીયમ",
    "gv": "Yn Velg",
    "ha": "Beljik",
    "he": "בלגיה",
    "hi": "बेल्जियम",
    "hr": "Belgija",
    "ht": "Bèljik",
    "hu": "Belgium",
    "hy": "Բելգիա",
    "ia": "Belgica",
    "id": "Belgia",
    "io": "Belgia",
    "is": "Belgía",
    "it": "Belgio",
    "iu": "Belgium",
    "ja": "ベルギー",
    "ka": "ბელგია",
    "ki": "Belgium",
    "kk": "Бельгия",
    "kl": "Belgium",
    "km": "បែល​ហ្ស៊ិក",
    "kn": "ಬೆಲ್ಜಿಯಂ",
    "ko": "벨기에",
    "ku": "Belçîka",
    "kv": "Бельгия",
    "kw": "Pow Belg",
    "ky": "Бельгия",
    "lo": "ປະເທດແບນຊິກ",
    "lt": "Belgija",
    "lv": "Beļģija",
    "mi": "Pehiamu",
    "mk": "Белгија",
    "ml": "ബെല്‍ജിയം",
    "mn": "Белги",
    "mr": "बेल्जियम",
    "ms": "Belgium",
    "mt": "Belġju",
    "my": "ဘယ်လ်ဂျီယမ်နိုင်ငံ",
    "na": "Berdjiyum",
    "nb": "Belgia",
    "ne": "बेल्जियम",
    "nl": "België",
    "nn": "Belgia",
    "nv": "Bélgii Bikéyah",
    "oc": "Belgica",
    "or": "ବେଲଜିୟମ",
    "pa": "ਬੈਲਜੀਅਮ",
    "pi": "बेल्जियम",
    "pl": "Belgia",
    "ps": "بلجیم",
    "pt": "Bélgica",
    "pt_BR": "Bélgica",
    "ro": "Belgia",
    "ru": "Бельгия",
    "rw": "Ububiligi",
    "sc": "Bèlgiu",
    "sd": "بيلجيم",
    "si": "බෙල්ජියම",
    "sk": "Belgicko",
    "sl": "Belgija",
    "so": "Beljiyam",
    "sq": "Belgjikë",
    "sr": "Белгија",
    "sv": "Belgien",
    "sw": "Ubelgiji",
    "ta": "பெல்ஜியம்",
    "te": "బెల్జియమ్",
    "tg": "Белгия",
    "th": "เบลเยียม",
    "ti": "ቤልጄም",
    "tk": "Belgiýa",
    "tl": "Belhika",
    "tr": "Belçika",
    "tt": "Белgиа",
    "ug": "بېلگىيە",
    "uk": "Бельгія",
    "ur": "بلجئیم",
    "uz": "Belgiya",
    "ve": "Belgium",
    "vi": "Bỉ",
    "wa": "Beldjike",
    "wo": "Beljik",
    "xh": "Belgium",
    "yo": "Bẹ́ljíọ̀m",
    "zh_CN": "比利时",
    "zh_HK": "比利時",
    "zh_TW": "比利時",
    "zu": "Isi-Bhelijiyamu"
  },
);
