import '../country.dart';

const countryBFA = Country(
  alpha2: 'BF',
  alpha3: 'BFA',
  continent: Continent.africa,
  countryCode: '226',
  currencyCode: 'XOF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'UV',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 12.238333,
      longitude: -1.561593,
    ),
    maxCoordinate: Coordinate(
      latitude: 15.0840397,
      longitude: 2.4043596,
    ),
    minCoordinate: Coordinate(
      latitude: 9.4104717,
      longitude: -5.5132416,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 15.0840397,
        longitude: 2.4043596,
      ),
      southwest: Coordinate(
        latitude: 9.4104717,
        longitude: -5.5132416,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'BUR',
  isoLongName: 'Burkina Faso',
  isoShortName: 'Burkina Faso',
  isoShortNameLowerCase: null,
  languagesOfficial: ['fr', 'ff'],
  languagesSpoken: ['fr', 'ff'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Burkinabe',
  number: '854',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Western Africa',
  unLocode: 'BF',
  unMember: true,
  unofficialNames: ['Burkina Faso', 'ブルキナファソ'],
  vehicleRegistrationCode: 'BF',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Burkina Faso",
    "af": "Burkina Faso",
    "ak": "Burkina Faso",
    "am": "Burkina Faso",
    "an": "Burkina Faso",
    "ar": "بوركينا فاصو",
    "as": "বুৰ্কিনা ফাসো",
    "ay": "Burkina Faso",
    "az": "Burkina Faso",
    "ba": "Burkina Faso",
    "be": "Буркіна-Фасо",
    "bg": "Буркина Фасо",
    "bi": "Burkina Faso",
    "bn": "বুর্কিনা ফাসো",
    "bn_IN": "বুর্কিনা ফাসো",
    "br": "Burkina Faso",
    "bs": "Burkina Faso",
    "ca": "Burkina Faso",
    "ce": "Буркина Фасо",
    "ch": "Burkina Faso",
    "cs": "Burkina Faso",
    "cv": "Буркина Фасо",
    "cy": "Burkina Faso",
    "da": "Burkina Faso",
    "de": "Burkina Faso",
    "dv": "ބުރުކީނާ ފާސޯ",
    "dz": "བུར་ཀི་ན་ ཕ་སོ།",
    "ee": "Burkina Faso",
    "el": "Μπουρκίνα Φάσο",
    "en": "Burkina Faso",
    "eo": "Burkino",
    "es": "Burquina Faso",
    "et": "Burkina Faso",
    "eu": "Burkina Faso",
    "fa": "بورکینافاسو",
    "ff": "Burkina Faso",
    "fi": "Burkina Faso",
    "fo": "Burkina Faso",
    "fr": "Burkina Faso",
    "fy": "Bûrkina Faso",
    "ga": "Buircíne Fasó",
    "gl": "Burquina Faso",
    "gn": "Burkina Faso",
    "gu": "બુર્કિના ફાસો",
    "gv": "Burkina Faso",
    "ha": "Burkina faso",
    "he": "בורקינה פאסו",
    "hi": "बुर्किना फासो",
    "hr": "Burkina Faso",
    "ht": "Boukinafaso",
    "hu": "Burkina Faso",
    "hy": "Բուրկինա Ֆասո",
    "ia": "Burkina Faso",
    "id": "Burkina Faso",
    "io": "Burkina Faso",
    "is": "Búrkína Fasó",
    "it": "Burkina Faso",
    "iu": "Burkina Faso",
    "ja": "ブルキナファソ",
    "ka": "ბურკინა-ფასო",
    "ki": "Burkina Faso",
    "kk": "Буркина-Фасо",
    "kl": "Burkina Faso",
    "km": "ប៊ូរគីណាហ្វាសូ",
    "kn": "ಬರ್ಕಿನಾ ಫಾಸೋ",
    "ko": "부르키나파소",
    "ku": "Burkîna Faso",
    "kv": "Burkina Faso",
    "kw": "Burkina Faso",
    "ky": "Буркина Фасо",
    "lo": "Burkina Faso",
    "lt": "Burkina Fasas",
    "lv": "Burkinafaso",
    "mi": "Burkina Faso",
    "mk": "Буркина Фасо",
    "ml": "ബുര്‍ക്കിന ഫാസോ",
    "mn": "Буркина Фасо",
    "mr": "बर्किना फासो",
    "ms": "Burkina Faso",
    "mt": "Burkina Faso",
    "my": "ဘာကီးနားဖားဆိုနိုင်ငံ",
    "na": "Burkinabato",
    "nb": "Burkina Faso",
    "ne": "बुर्किना फासो",
    "nl": "Burkina Faso",
    "nn": "Burkina Faso",
    "nv": "Burkina Faso",
    "oc": "Burkina Faso",
    "or": "ବୁର୍କିନା ଫାସୋ",
    "pa": "ਬੂਪਕੀਨਾ ਫਾਸੋ",
    "pi": "बुर्कीना-फासो",
    "pl": "Burkina Faso",
    "ps": "بورکینا فاسو",
    "pt": "Burkina Faso",
    "pt_BR": "Burquina",
    "ro": "Burkina Faso",
    "ru": "Буркина-Фасо",
    "rw": "Burukina Faso",
    "sc": "Burkina Faso",
    "sd": "Burkina Faso",
    "si": "බර්කිනා ෆාසෝ",
    "sk": "Burkina Faso",
    "sl": "Burkina Faso",
    "so": "Burkina Faso",
    "sq": "Burkina Faso",
    "sr": "Буркина Фасо",
    "sv": "Burkina Faso",
    "sw": "Burkina Faso",
    "ta": "பர்கினோ பாஸோ",
    "te": "బర్కినా ఫాసో",
    "tg": "Буркина Фасо",
    "th": "บูร์กินาฟาโซ",
    "ti": "ቡርኪና ፋሶ",
    "tk": "Burkina-Faso",
    "tl": "Burkina Faso",
    "tr": "Burkina Faso",
    "tt": "Буркина Фасо",
    "ug": "بۇركىنا-فاسو",
    "uk": "Буркіна-Фасо",
    "ur": "برکینا فاسو",
    "uz": "Burkina Faso",
    "ve": "Burkina Faso",
    "vi": "Buốc-khi-na Pha-xô",
    "wa": "Bourkina Fasso",
    "wo": "Burkina Faso",
    "xh": "Burkina Faso",
    "yo": "Bùrkínà Fasò",
    "zh_CN": "布基纳法索",
    "zh_HK": "布基納法索",
    "zh_TW": "布吉納法索",
    "zu": "IBukhina Faso"
  },
);
