import '../country.dart';

const countryBHS = Country(
  alpha2: 'BS',
  alpha3: 'BHS',
  continent: Continent.northAmerica,
  countryCode: '1',
  currencyCode: 'BSD',
  distanceUnit: DistanceUnit.miles,
  gec: 'BF',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 25.03428,
      longitude: -77.39627999999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 27.263412,
      longitude: -72.70975390000001,
    ),
    minCoordinate: Coordinate(
      latitude: 20.9082735,
      longitude: -80.4775603,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 27.263412,
        longitude: -72.70975390000001,
      ),
      southwest: Coordinate(
        latitude: 20.9082735,
        longitude: -80.4775603,
      ),
    ),
  ),
  internationalPrefix: '011',
  ioc: 'BAH',
  isoLongName: 'The Commonwealth of The Bahamas',
  isoShortName: 'Bahamas',
  isoShortNameLowerCase: 'Bahamas (the)',
  languagesOfficial: ['en'],
  languagesSpoken: ['en'],
  nationalDestinationCodeLengths: [3],
  nationalNumberLengths: [10],
  nationalPrefix: '1',
  nationality: 'Bahamian',
  number: '044',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.americas,
  startOfWeek: Week.monday,
  subregion: 'Caribbean',
  unLocode: 'BS',
  unMember: true,
  unofficialNames: ['Bahamas', 'The Bahamas', 'バハマ'],
  vehicleRegistrationCode: 'BS',
  worldRegion: WorldRegion.amer,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: '1242',
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Bahamas",
    "af": "Bahamas",
    "ak": "Bahamas",
    "am": "Bahamas",
    "an": "Bahamas",
    "ar": "جزر البهاما",
    "as": "বাহামাছ",
    "ay": "Bahamas",
    "az": "Bahama",
    "ba": "Bahamas",
    "be": "Багамскія астравы",
    "bg": "Бахами",
    "bi": "Bahamas",
    "bn": "বাহামাস",
    "bn_IN": "বাহামাস",
    "br": "Bahamas",
    "bs": "Bahami",
    "ca": "Bahames",
    "ce": "Bahamas",
    "ch": "Bahamas",
    "cs": "Bahamy",
    "cv": "Bahamas",
    "cy": "Y Bahamas",
    "da": "Bahamas",
    "de": "Bahamas",
    "dv": "Bahamas",
    "dz": "བ་ཧ་མཱསི།",
    "ee": "Bahamas",
    "el": "Μπαχάμες",
    "en": "Bahamas",
    "eo": "Bahamoj",
    "es": "Bahamas",
    "et": "Bahama",
    "eu": "Bahamak",
    "fa": "باهاما",
    "ff": "Bahamas",
    "fi": "Bahama",
    "fo": "Bahamas",
    "fr": "Bahamas",
    "fy": "Bahamas",
    "ga": "Na Bahámaí",
    "gl": "Bahamas",
    "gn": "Bahamas",
    "gu": "બહામાસ",
    "gv": "Bahamas",
    "ha": "Bahamas",
    "he": "בהמאס",
    "hi": "बहामास",
    "hr": "Bahami",
    "ht": "Bahamas",
    "hu": "Bahama-szigetek",
    "hy": "Բահամներ",
    "ia": "Bahamas",
    "id": "Bahama",
    "io": "Bahamas",
    "is": "Bahamaeyjar",
    "it": "Bahamas",
    "iu": "Bahamas",
    "ja": "バハマ",
    "ka": "ბაჰამის კუნძულები",
    "ki": "Bahamas",
    "kk": "Багам аралдары",
    "kl": "Bahamas",
    "km": "បាហាម៉ាស",
    "kn": "ಬಹಾಮಾಸ್",
    "ko": "바하마",
    "ku": "Giravên Bahama",
    "kv": "Bahamas",
    "kw": "Bahamas",
    "ky": "Багама аралдары",
    "lo": "Bahamas",
    "lt": "Bahamos",
    "lv": "Bahamas",
    "mi": "Bahamas",
    "mk": "Бахами",
    "ml": "ബഹാമാസ്",
    "mn": "Bahamas",
    "mr": "बहामाज्",
    "ms": "Bahamas",
    "mt": "Bahamas",
    "my": "Bahamas",
    "na": "Bahamas",
    "nb": "Bahamas",
    "ne": "बहामास",
    "nl": "Bahama's",
    "nn": "Bahamas",
    "nv": "Bahamas",
    "oc": "Bahamas",
    "or": "ବାହାମା",
    "pa": "ਬਾਹਾਮਾਸ",
    "pi": "Bahamas",
    "pl": "Bahamy",
    "ps": "Bahamas",
    "pt": "Bahamas",
    "pt_BR": "Bahamas",
    "ro": "Bahamas",
    "ru": "Багамы",
    "rw": "Bahamasi",
    "sc": "Bahamas",
    "sd": "Bahamas",
    "si": "බහමාස්",
    "sk": "Bahamy",
    "sl": "Bahami",
    "so": "Bahamas",
    "sq": "Bahamas",
    "sr": "Бахами",
    "sv": "Bahamas",
    "sw": "Bahama",
    "ta": "பஹாமாஸ்",
    "te": "బహామాజ్",
    "tg": "Ҷазираҳои Баҳама",
    "th": "บาฮามาส",
    "ti": "ባሃማስ",
    "tk": "Bagama adalary",
    "tl": "Bahamas",
    "tr": "Bahamalar",
    "tt": "Баһамас",
    "ug": "باھاما ئاراللىرى",
    "uk": "Багамські острови",
    "ur": "Bahamas",
    "uz": "Bahamas",
    "ve": "Bahamas",
    "vi": "Ba-ha-ma",
    "wa": "Bahamas",
    "wo": "Bahamas",
    "xh": "Bahamas",
    "yo": "Bahamas",
    "zh_CN": "巴哈马",
    "zh_HK": "巴哈馬",
    "zh_TW": "巴哈馬",
    "zu": "Bahamas"
  },
);
