import '../country.dart';

const countryBOL = Country(
  alpha2: 'BO',
  alpha3: 'BOL',
  continent: Continent.southAmerica,
  countryCode: '591',
  currencyCode: 'BOB',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'BL',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -16.290154,
      longitude: -63.58865299999999,
    ),
    maxCoordinate: Coordinate(
      latitude: -9.669323,
      longitude: -57.453803,
    ),
    minCoordinate: Coordinate(
      latitude: -22.8980899,
      longitude: -69.64498999999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: -9.669323,
        longitude: -57.453803,
      ),
      southwest: Coordinate(
        latitude: -22.8980899,
        longitude: -69.64498999999999,
      ),
    ),
  ),
  internationalPrefix: '0010',
  ioc: 'BOL',
  isoLongName: 'The Plurinational State of Bolivia',
  isoShortName: 'Bolivia (Plurinational State of)',
  isoShortNameLowerCase: null,
  languagesOfficial: ['es', 'ay', 'qu'],
  languagesSpoken: ['es', 'ay', 'qu'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '010',
  nationality: 'Bolivian',
  number: '068',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.americas,
  startOfWeek: Week.monday,
  subregion: 'South America',
  unLocode: 'BO',
  unMember: true,
  unofficialNames: ['Bolivia', 'Bolivien', 'Bolivie', 'ボリビア多民族国'],
  vehicleRegistrationCode: 'BOL',
  worldRegion: WorldRegion.amer,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Bolivia',
    'af': 'Bolivië',
    'ak': 'Bolivia',
    'am': 'ቦሑቱ።',
    'an': 'Bolivia',
    'ar': 'بوليفيا',
    'as': 'বলীভিয়া',
    'ay': 'Bolivia',
    'az': 'Boliviya',
    'ba': 'Bolivia',
    'be': 'Балівія',
    'bg': 'Боливия',
    'bi': 'Bolivia',
    'bn': 'বোলিভিয়া',
    'bn_IN': 'বোলিভিয়া',
    'br': 'Bolivia',
    'bs': 'Bolivija',
    'ca': 'Bolívia',
    'ce': 'Боливи',
    'ch': 'Bolivia',
    'cs': 'Bolívie',
    'cv': 'Боливи',
    'cy': 'Bolifia',
    'da': 'Bolivia',
    'de': 'Bolivien',
    'dv': 'ބޮލީވިއާ',
    'dz': 'བོ་ལི་བི་ཡ།',
    'ee': 'Bolivia',
    'el': 'Βολιβία',
    'en': 'Bolivia',
    'eo': 'Bolivio',
    'es': 'Bolivia',
    'et': 'Boliivia',
    'eu': 'Bolivia',
    'fa': 'بولیوی',
    'ff': 'Bolivia',
    'fi': 'Bolivia',
    'fo': 'Bolivia',
    'fr': 'Bolivie',
    'fy': 'Bolivia',
    'ga': 'An Bholaiv',
    'gl': 'Bolivia',
    'gn': 'Bolivia',
    'gu': 'બોલિવિયા',
    'gv': 'Yn Volivia',
    'ha': 'Bolivia',
    'he': 'בוליביה',
    'hi': 'बोलिविया',
    'hr': 'Bolivija',
    'ht': 'Bolivi',
    'hu': 'Bolívia',
    'hy': 'Բոլիվիա',
    'ia': 'Bolivia',
    'id': 'Bolivia',
    'io': 'Bolivia',
    'is': 'Bólivía',
    'it': 'Bolivia',
    'iu': 'Bolivia',
    'ja': 'ボリビア',
    'ka': 'ბოლივია',
    'ki': 'Bolivia',
    'kk': 'Боливия',
    'kl': 'Bolivia',
    'km': 'បូលីវី',
    'kn': 'ಬೊಲಿವಿಯಾ',
    'ko': '볼리비아',
    'ku': 'Bolîvya',
    'kv': 'Bolivia',
    'kw': 'Bolivi',
    'ky': 'Боливия',
    'lo': 'ປະເທດໂບລີວີ',
    'lt': 'Bolivija',
    'lv': 'Bolīvija',
    'mi': 'Poriwia',
    'mk': 'Боливија',
    'ml': 'ബൊളീവിയ',
    'mn': 'Боливи',
    'mr': 'बोलिव्हिये',
    'ms': 'Bolivia',
    'mt': 'Bolivja',
    'my': 'ဘိုလီးဗီးယားနိုင်ငံ',
    'na': 'Boribiya',
    'nb': 'Bolivia',
    'ne': 'बोलिभिया',
    'nl': 'Bolivia',
    'nn': 'Bolivia',
    'nv': 'Ałhidadiikʼą́ Dineʼé Bikéyah',
    'oc': 'Bolivia',
    'or': 'ବୋଲିଭିଆ',
    'pa': 'ਬੋਲੋਵੀਆ',
    'pi': 'बोलिविया',
    'pl': 'Boliwia',
    'ps': 'بولېویا',
    'pt': 'Bolívia',
    'pt_BR': 'Bolívia',
    'ro': 'Bolivia',
    'ru': 'Боливия',
    'rw': 'Boliviya',
    'sc': 'Bolìvia',
    'sd': 'Bolivia',
    'si': 'බොලීවියාව',
    'sk': 'Bolívia',
    'sl': 'Bolivija',
    'so': 'Boliifia',
    'sq': 'Bolivi',
    'sr': 'Боливија',
    'sv': 'Bolivia',
    'sw': 'Bolivia',
    'ta': 'பொலிவியா',
    'te': 'బోలివియ',
    'tg': 'Боливия',
    'th': 'โบลิเวีย',
    'ti': 'ቦሊቭያ',
    'tk': 'Boliwiýa',
    'tl': 'Bolivia',
    'tr': 'Bolivya',
    'tt': 'Боливиа',
    'ug': 'بولىۋىيە',
    'uk': 'Болівія',
    'ur': 'بولیویا',
    'uz': 'Boliviya',
    've': 'Bolivia',
    'vi': 'Bô-li-vi-a',
    'wa': 'Boliveye',
    'wo': 'Boliibi',
    'xh': 'Bolivia',
    'yo': 'Bòlífíà',
    'zh_CN': '波利维亚',
    'zh_HK': '玻利維亞',
    'zh_TW': '玻利維亞',
    'zu': 'I Boliviya'
  },
);
