import '../country.dart';

const countryCAF = Country(
  alpha2: 'CF',
  alpha3: 'CAF',
  continent: Continent.africa,
  countryCode: '236',
  currencyCode: 'XAF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CT',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 6.611110999999999,
      longitude: 20.939444,
    ),
    maxCoordinate: Coordinate(
      latitude: 11.0179569,
      longitude: 27.4583049,
    ),
    minCoordinate: Coordinate(
      latitude: 2.2230529,
      longitude: 14.4150981,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 11.0179569,
        longitude: 27.4583049,
      ),
      southwest: Coordinate(
        latitude: 2.2230529,
        longitude: 14.4150981,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CAF',
  isoLongName: 'The Central African Republic',
  isoShortName: 'Central African Republic',
  isoShortNameLowerCase: 'Central African Republic (the)',
  languagesOfficial: ['fr', 'sg'],
  languagesSpoken: ['fr', 'sg'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Central African',
  number: '140',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Middle Africa',
  unLocode: 'CF',
  unMember: true,
  unofficialNames: [
    'Central African Republic',
    'Zentralafrikanische Republik',
    'République Centrafricaine',
    'República Centroafricana',
    '中央アフリカ共和国',
    'Centraal-Afrikaanse Republiek'
  ],
  vehicleRegistrationCode: 'RCA',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Central African Republic",
    "af": "Sentraal-Afrikaanse Republiek",
    "ak": "Central African Republic",
    "am": "ፘመጢጘለኢፄ ጐፔሱጢ ሱፐብሑጤ",
    "an": "Republica Centroafricana",
    "ar": "جمهورية إفريقيّا الوسطى",
    "as": "মধ্য আফ্ৰিকান প্ৰজাতন্ত্ৰ",
    "ay": "Central African Republic",
    "az": "Mərkəzi Afrika Respublikası",
    "ba": "Central African Republic",
    "be": "Цэнтральна-Афрыканская Рэспубліка",
    "bg": "Централноафриканска Република",
    "bi": "Central African Republic",
    "bn": "মধ্য আফ্রিকান প্রজাতন্ত্র",
    "bn_IN": "মধ্য আফ্রিকান প্রজাতন্ত্র",
    "br": "Republik Kreizafrikan",
    "bs": "Centralnoafrička Republika",
    "ca": "República Centreafricana",
    "ce": "Африкан Юккъера Пачхьалкх",
    "ch": "Central African Republic",
    "cs": "Středoafrická republika",
    "cv": "Африкан Юккъера Пачхьалкх",
    "cy": "Gweriniaeth Canol Affrica",
    "da": "Centralafrikanske Republik",
    "de": "Zentralafrikanische Republik",
    "dv": "މެދުތެރޭ އެފްރިކާގެ ޖުމްހޫރިއްޔާ",
    "dz": "དབུས་ ཨཕ་རི་ཀཱན་ རི་པཔ་ལིཀ།",
    "ee": "Central African Republic",
    "el": "Δημοκρατία Κεντρικής Αφρικής",
    "en": "Central African Republic",
    "eo": "Centr-Afrika Respubliko",
    "es": "República Centroafricana",
    "et": "Kesk-Aafrika Vabariik",
    "eu": "Afrika Erdiko Errepublika",
    "fa": "جمهوری آفریقای مرکزی",
    "ff": "Central African Republic",
    "fi": "Keski-Afrikan tasavalta",
    "fo": "Miðafrikalýðveldið",
    "fr": "République centrafricaine",
    "fy": "Sintraal-Afrikaanske Republyk",
    "ga": "Poblacht na hAfraice Láir",
    "gl": "República Centroafricana",
    "gn": "Central African Republic",
    "gu": "સેન્ટ્રલ આફ્રિકન રીપબ્લિક",
    "gv": "Pobblaght yn Affrick Veanagh",
    "ha": "Central African Republic",
    "he": "הרפובליקה המרכז־אפריקאית",
    "hi": "मध्य अफ़्रीकी गणराज्य",
    "hr": "Srednjoafrička Republika",
    "ht": "Repiblik santafrik",
    "hu": "Közép-afrikai Köztársaság",
    "hy": "Կենտրոնական Աֆրիկյան Հանրապետություն",
    "ia": "Republica African Central",
    "id": "Republik Afrika Tengah",
    "io": "Centrafrika",
    "is": "Miðafríkulýðveldið",
    "it": "Repubblica Centrafricana",
    "iu": "Central African Republic",
    "ja": "中央アフリカ共和国",
    "ka": "ცენტრალური აფრიკის რესპუბლიკა",
    "ki": "Central African Republic",
    "kk": "Орталық Африка Республикасы",
    "kl": "Central African Republic",
    "km": "សាធារណរដ្ឋ​អាហ្វ្រិក​កណ្ដាល",
    "kn": "ಮಧ್ಯ ಆಫ್ರಿಕನ್ ಗಣರಾಜ್ಯ",
    "ko": "중앙아프리카 공화국",
    "ku": "Komara Afrikaya Navîn",
    "kv": "Central African Republic",
    "kw": "Centrafrika",
    "ky": "Борбордук-Африка Республикасы",
    "lo": "Central African Republic",
    "lt": "Centrinės Afrikos Respublika",
    "lv": "Centrālāfrikas Republika",
    "mi": "Central African Republic",
    "mk": "Централно афричка република",
    "ml": "മദ്ധ്യ അഫ്രിക്കന്‍ റിപ്പബ്ലിക്",
    "mn": "Төв африкын ард улс",
    "mr": "सेंट्रल आफ्रिकन रिपब्लिक",
    "ms": "Republik Afrika Tengah",
    "mt": "Repubblika Afrikana Ċentrali",
    "my": "ဗဟိုအာဖရိကသမ္မတနိုင်ငံ",
    "na": "Ripubrikin Aprika Yugaga",
    "nb": "Den sentralafrikanske republikk",
    "ne": "केन्द्रिय अफ्रिकी गणराज्य",
    "nl": "Centraal-Afrikaanse Republiek",
    "nn": "Den sentralafrikanske republikken",
    "nv": "Naakaii Łizhinii Bikéyah Beʼałnííʼ",
    "oc": "Republica de Centrafrica",
    "or": "ମଦ୍ଦ୍ଯବର୍ତ୍ତୀ ଆଫ୍ରୀକିୟ ସାଧାରଣତନ୍ତ୍ର",
    "pa": "ਕੇਂਦਰੀ ਅਫਰੀਕਾ ਗਣਰਾਜ",
    "pi": "केन्द्रीय अफ्रीका गणराज्य",
    "pl": "Republika Środkowoafrykańska",
    "ps": "د منځنی افريقا ولسمشريزه",
    "pt": "República Centro-Africana",
    "pt_BR": "República Centro-Africana",
    "ro": "Republica Central Africană",
    "ru": "Центрально-африканская республика",
    "rw": "Repubulika ya Santara Afurika",
    "sc": "Repùblica Tzentrafricana",
    "sd": "Central African Republic",
    "si": "මධ්‍යම අප්‍රිකානු ජනරජය",
    "sk": "Stredoafrická republika",
    "sl": "Srednjeafriška republika",
    "so": "Jamhuuriyadda Bartamaha Afrika",
    "sq": "Republika e Afrikës Qendrore",
    "sr": "Централноафричка Република",
    "sv": "Centralafrikanska republiken",
    "sw": "Jamhuri ya Afrika ya Kati",
    "ta": "மத்திய ஆப்ரிக்க குடியரசு",
    "te": "సేంట్రల్ ఆఫ్రికన్ రిపబ్లిక్",
    "tg": "Ҷумҳурии Африкаи Марказӣ",
    "th": "สาธารณรัฐแอฟริกากลาง",
    "ti": "ሪፓብሊክ ማእከላይ ኣፍሪቃ",
    "tk": "Merkezi afrika respublikasy",
    "tl": "Republikang Panggitnang Aprika",
    "tr": "Orta Afrika Cumhuriyeti",
    "tt": "Үзәк Африка Җөмһүриәте",
    "ug": "ئوتتۇرا ئافرىقا جۇمھۇرىيىتى",
    "uk": "Центральноафриканська Республіка",
    "ur": "وسطی افریقی جمہوریہ",
    "uz": "Markaziy Afrika Respublikasi",
    "ve": "Central African Republic",
    "vi": "Nước Cộng Hoà Trung Phi",
    "wa": "Cintrafrike",
    "wo": "Republik bu Santar Afrik",
    "xh": "Central African Republic",
    "yo": "Orílẹ̀-èdè Olómìnira Àrin Áfríkà",
    "zh_CN": "中非",
    "zh_HK": "中非共和國",
    "zh_TW": "中非共和國",
    "zu": "Central African Republic"
  },
);
