import '../country.dart';

const countryCHN = Country(
  alpha2: 'CN',
  alpha3: 'CHN',
  continent: Continent.asia,
  countryCode: '86',
  currencyCode: 'CNY',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CH',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 35.86166,
      longitude: 104.195397,
    ),
    maxCoordinate: Coordinate(
      latitude: 53.5609739,
      longitude: 134.7754563,
    ),
    minCoordinate: Coordinate(
      latitude: 17.9996,
      longitude: 73.4994136,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 53.5609739,
        longitude: 134.7754563,
      ),
      southwest: Coordinate(
        latitude: 17.9996,
        longitude: 73.4994136,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CHN',
  isoLongName: 'The People\'s Republic of China',
  isoShortName: 'China',
  isoShortNameLowerCase: null,
  languagesOfficial: ['zh'],
  languagesSpoken: ['zh'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8, 9, 10, 11],
  nationalPrefix: '0',
  nationality: 'Chinese',
  number: '156',
  postalCode: true,
  postalCodeFormat: r'\d{6}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Eastern Asia',
  unLocode: 'CN',
  unMember: true,
  unofficialNames: ['China', 'Chine', '中国'],
  vehicleRegistrationCode: 'CHN*',
  worldRegion: WorldRegion.apac,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}} {{region_short}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: true,
  isoShortNameByLocale: {
    "ab": "China",
    "af": "Sjina",
    "ak": "China",
    "am": "ኂ፤ና",
    "an": "China",
    "ar": "الصّين",
    "as": "চীন",
    "ay": "China",
    "az": "Çin",
    "ba": "China",
    "be": "Кітай",
    "bg": "Китай",
    "bi": "China",
    "bn": "চীন",
    "bn_IN": "চীন",
    "br": "Sina",
    "bs": "Kina",
    "ca": "Xina",
    "ce": "China",
    "ch": "China",
    "cs": "Čína",
    "cv": "China",
    "cy": "Tsieina",
    "da": "Kina",
    "de": "China",
    "dv": "China",
    "dz": "ཅ་ཡེ་ན།(རྒྱ་ནག)",
    "ee": "China",
    "el": "Κίνα",
    "en": "China",
    "eo": "Ĉinio",
    "es": "China",
    "et": "Hiina",
    "eu": "Txina",
    "fa": "چین",
    "ff": "China",
    "fi": "Kiina",
    "fo": "Kina",
    "fr": "Chine",
    "fy": "China",
    "ga": "An tSín",
    "gl": "China",
    "gn": "China",
    "gu": "ચીન",
    "gv": "China",
    "ha": "China",
    "he": "סין",
    "hi": "चीन",
    "hr": "Kina",
    "ht": "Chin",
    "hu": "Kína",
    "hy": "Չինաստան",
    "ia": "China",
    "id": "Cina",
    "io": "China",
    "is": "Kína",
    "it": "Cina",
    "iu": "China",
    "ja": "中国",
    "ka": "ჩინეთი",
    "ki": "China",
    "kk": "Қытай",
    "kl": "China",
    "km": "ចិន",
    "kn": "ಚೈನಾ",
    "ko": "중국",
    "ku": "Çîn",
    "kv": "China",
    "kw": "China",
    "ky": "Кытай",
    "lo": "China",
    "lt": "Kinija",
    "lv": "Ķīna",
    "mi": "Haina",
    "mk": "Кина",
    "ml": "ചൈന",
    "mn": "Хятад",
    "mr": "चीन",
    "ms": "China",
    "mt": "Ċina",
    "my": "China",
    "na": "China",
    "nb": "Kina",
    "ne": "चीन",
    "nl": "China",
    "nn": "Kina",
    "nv": "China",
    "oc": "China",
    "or": "ଚୀନ",
    "pa": "ਚੀਨ",
    "pi": "China",
    "pl": "Chiny",
    "ps": "چین",
    "pt": "China",
    "pt_BR": "China",
    "ro": "China",
    "ru": "Китай",
    "rw": "Ubushinwa",
    "sc": "Tzina",
    "sd": "China",
    "si": "චීනය",
    "sk": "Čína",
    "sl": "Kitajska",
    "so": "Shiinaha",
    "sq": "Kinë",
    "sr": "Кина",
    "sv": "Kina",
    "sw": "China",
    "ta": "சீனா",
    "te": "చైనా",
    "tg": "Чин",
    "th": "จีน",
    "ti": "ቻይና",
    "tk": "Hytaý",
    "tl": "Tsina",
    "tr": "Çin",
    "tt": "Чин",
    "ug": "جۇڭگو",
    "uk": "Китай",
    "ur": "China",
    "uz": "China",
    "ve": "China",
    "vi": "Trung Quốc",
    "wa": "Chine",
    "wo": "Ciin",
    "xh": "Tshayina",
    "yo": "China",
    "zh_CN": "中国",
    "zh_HK": "中國",
    "zh_TW": "中國",
    "zu": "Isi-Shayina"
  },
);
