import '../country.dart';

const countryCIV = Country(
  alpha2: 'CI',
  alpha3: 'CIV',
  continent: Continent.africa,
  countryCode: '225',
  currencyCode: 'XOF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'IV',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 7.539988999999999,
      longitude: -5.547079999999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 10.7400149,
      longitude: -2.493031,
    ),
    minCoordinate: Coordinate(
      latitude: 4.193,
      longitude: -8.6020589,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 10.7400149,
        longitude: -2.493031,
      ),
      southwest: Coordinate(
        latitude: 4.193,
        longitude: -8.6020589,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CIV',
  isoLongName: 'The Republic of Côte d\'Ivoire',
  isoShortName: 'Côte d\'Ivoire',
  isoShortNameLowerCase: null,
  languagesOfficial: ['fr'],
  languagesSpoken: ['fr'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '0',
  nationality: 'Ivorian',
  number: '384',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Western Africa',
  unLocode: 'CI',
  unMember: true,
  unofficialNames: [
    'Côte D\'Ivoire',
    'Elfenbeinküste',
    'コートジボワール',
    'Ivoorkust',
    'Cote D\'Ivoire (Ivory Coast)',
    'Cote d Ivoire (Ivory Coast)',
    'Ivory Coast'
  ],
  vehicleRegistrationCode: 'CI',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Côte d\'Ivoire',
    'af': 'Ivoorkus',
    'ak': 'Côte d\'Ivoire',
    'am': 'Côte d\'Ivoire',
    'an': 'Côte d\'Ivoire',
    'ar': 'ساحل العاج',
    'as': 'আইভৰি কোস্ট',
    'ay': 'Côte d\'Ivoire',
    'az': 'Kot Divuar',
    'ba': 'Côte d\'Ivoire',
    'be': 'Кот д\'Івуар',
    'bg': 'Кот д\'Ивоар',
    'bi': 'Côte d\'Ivoire',
    'bn': 'আইভরি কোস্ট',
    'bn_IN': 'আইভরি কোস্ট',
    'br': 'Côte d\'Ivoire',
    'bs': 'Obala Slonovače',
    'ca': 'Costa de Vori',
    'ce': 'Côte d\'Ivoire',
    'ch': 'Côte d\'Ivoire',
    'cs': 'Pobřeží slonoviny',
    'cv': 'Côte d\'Ivoire',
    'cy': 'Côte d\'Ivoire',
    'da': 'Elfenbenskysten',
    'de': 'Elfenbeinküste',
    'dv': 'Côte d\'Ivoire',
    'dz': 'ཀོཊི་ ཌི་ཨའི་བོ་རི།',
    'ee': 'Côte d\'Ivoire',
    'el': 'Ακτή Ελεφαντοστού',
    'en': 'Côte d\'Ivoire',
    'eo': 'Ebur-Bordo',
    'es': 'Costa de Marfíl',
    'et': 'Elevandiluurannik (Côte d\'Ivoire)',
    'eu': 'Boli Kosta',
    'fa': 'ساحل عاج',
    'ff': 'Côte d\'Ivoire',
    'fi': 'Norsunluurannikko',
    'fo': 'Côte d\'Ivoire',
    'fr': 'Côte d\'Ivoire',
    'fy': 'Côte d\'Ivoire',
    'ga': 'An Cósta Eabhair',
    'gl': 'Costa de Marfín',
    'gn': 'Côte d\'Ivoire',
    'gu': 'કોટે ડીઆઇવરી',
    'gv': 'Côte d\'Ivoire',
    'ha': 'Côte d\'Ivoire',
    'he': 'חוף השנהב',
    'hi': 'कोयटे डी वोयरे',
    'hr': 'Obala Bjelokosti',
    'ht': 'Côte d\'Ivoire',
    'hu': 'Elefántcsontpart',
    'hy': 'Կոտ դ\'Իվուար',
    'ia': 'Costa de Ebore',
    'id': 'Pantai Gading',
    'io': 'Côte d\'Ivoire',
    'is': 'Fílabeinsströnd',
    'it': 'Costa d\'Avorio',
    'iu': 'Côte d\'Ivoire',
    'ja': 'コートジボワール',
    'ka': 'კოტ-დ\'ივუარი',
    'ki': 'Côte d\'Ivoire',
    'kk': 'Кот д\'Ивуар',
    'kl': 'Côte d\'Ivoire',
    'km': 'កូតេឌីវ័រ',
    'kn': 'Côte d\'Ivoire',
    'ko': '코트디부아르',
    'ku': 'Sahila Diranên Fîlan',
    'kv': 'Côte d\'Ivoire',
    'kw': 'Côte d\'Ivoire',
    'ky': 'Кот-д\'Ивуар',
    'lo': 'Côte d\'Ivoire',
    'lt': 'Dramblio Kaulo Krantas',
    'lv': 'Kotdivuāra',
    'mi': 'Côte d\'Ivoire',
    'mk': 'Брег на слонова коста',
    'ml': 'കോട്ടെ ഡി ലവര്‍',
    'mn': 'Côte d\'Ivoire',
    'mr': 'कोत द आयव्होर',
    'ms': 'Côte d\'Ivoire',
    'mt': 'Côte d\'Ivoire',
    'my': 'Côte d\'Ivoire',
    'na': 'Côte d\'Ivoire',
    'nb': 'Elfenbenskysten',
    'ne': 'Côte d\'Ivoire',
    'nl': 'Ivoorkust',
    'nn': 'Elfenbeinskysten',
    'nv': 'Côte d\'Ivoire',
    'oc': 'Còsta d\'Evòri',
    'or': 'କୋଟ ଡି\'ଭୋର',
    'pa': 'ਕੋਟ ਡੀਵੋਈਰੀ',
    'pi': 'Côte d\'Ivoire',
    'pl': 'Wybrzeże Kości Słoniowej',
    'ps': 'Côte d\'Ivoire',
    'pt': 'Costa do Marfim',
    'pt_BR': 'Costa do Marfim',
    'ro': 'Coasta de Fildeș',
    'ru': 'Кот-д\'Ивуар',
    'rw': 'Kote Divuwari',
    'sc': 'Costa de Avòriu',
    'sd': 'Côte d\'Ivoire',
    'si': 'කෝටේ ඩ්ලවොයිරා',
    'sk': 'Pobrežie Slonoviny',
    'sl': 'Slonokoščena obala',
    'so': 'Côte d\'Ivoire',
    'sq': 'Kepi i Fildishtë',
    'sr': 'Обала Слоноваче',
    'sv': 'Elfenbenskusten',
    'sw': 'Ivorycoast',
    'ta': 'கோத் ட்லவோர்',
    'te': 'కోత్ ద ఆయవ్హోర',
    'tg': 'Кот-д’Ивуар',
    'th': 'โกตดิวัวร์',
    'ti': 'Côte d\'Ivoire',
    'tk': 'Kot-D’’iwuar',
    'tl': 'Côte d\'Ivoire',
    'tr': 'Fildişi Sahili',
    'tt': 'Җôте д\'Ивоире',
    'ug': 'كوتىدىۋور',
    'uk': 'Кот-д\'Івуар',
    'ur': 'Côte d\'Ivoire',
    'uz': 'Côte d\'Ivoire',
    've': 'Côte d\'Ivoire',
    'vi': 'Cốt đi-vouă',
    'wa': 'Coisse d\' Ivwere',
    'wo': 'Kot diwaar',
    'xh': 'Côte d\'Ivoire',
    'yo': 'Côte d\'Ivoire',
    'zh_CN': '科特迪瓦',
    'zh_HK': '科特迪瓦',
    'zh_TW': '象牙海岸',
    'zu': 'Côte d\'Ivoire'
  },
);
