import '../country.dart';

const countryCMR = Country(
  alpha2: 'CM',
  alpha3: 'CMR',
  continent: Continent.africa,
  countryCode: '237',
  currencyCode: 'XAF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CM',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 7.369721999999999,
      longitude: 12.354722,
    ),
    maxCoordinate: Coordinate(
      latitude: 13.083335,
      longitude: 16.1944081,
    ),
    minCoordinate: Coordinate(
      latitude: 1.6559,
      longitude: 8.3936001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 13.083335,
        longitude: 16.1944081,
      ),
      southwest: Coordinate(
        latitude: 1.6559,
        longitude: 8.3936001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CMR',
  isoLongName: 'The Republic of Cameroon',
  isoShortName: 'Cameroon',
  isoShortNameLowerCase: null,
  languagesOfficial: ['en', 'fr'],
  languagesSpoken: ['en', 'fr'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Cameroonian',
  number: '120',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Middle Africa',
  unLocode: 'CM',
  unMember: true,
  unofficialNames: [
    'Cameroon',
    'Kamerun',
    'Cameroun',
    'Camerún',
    'カメルーン',
    'Kameroen'
  ],
  vehicleRegistrationCode: 'CAM',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Cameroon',
    'af': 'Kameroen',
    'ak': 'Cameroon',
    'am': 'ጢሣሩን',
    'an': 'Cameroon',
    'ar': 'الكاميرون',
    'as': 'কেমেৰুণ',
    'ay': 'Cameroon',
    'az': 'Kamerun',
    'ba': 'Cameroon',
    'be': 'Камерун',
    'bg': 'Камерун',
    'bi': 'Cameroon',
    'bn': 'ক্যামেরুণ',
    'bn_IN': 'ক্যামেরুণ',
    'br': 'Kameroun',
    'bs': 'Kamerun',
    'ca': 'Camerun',
    'ce': 'Камерун',
    'ch': 'Cameroon',
    'cs': 'Kamerun',
    'cv': 'Камерун',
    'cy': 'Cameroon',
    'da': 'Cameroun',
    'de': 'Kamerun',
    'dv': 'ކެމަރޫން',
    'dz': 'ཀེ་མི་རཱུན།',
    'ee': 'Cameroon',
    'el': 'Καμερούν',
    'en': 'Cameroon',
    'eo': 'Kameruno',
    'es': 'Camerún',
    'et': 'Kamerun',
    'eu': 'Kamerun',
    'fa': 'کامرون',
    'ff': 'Kamerun',
    'fi': 'Kamerun',
    'fo': 'Kamerun',
    'fr': 'Cameroun',
    'fy': 'Kameroen',
    'ga': 'Camarún',
    'gl': 'Camerún',
    'gn': 'Cameroon',
    'gu': 'કેમેરુન',
    'gv': 'Cameroon',
    'ha': 'Kameru',
    'he': 'קמרון',
    'hi': 'कैमरुन',
    'hr': 'Kamerun',
    'ht': 'Kamewoun',
    'hu': 'Kamerun',
    'hy': 'Կամերուն',
    'ia': 'Camerun',
    'id': 'Kamerun',
    'io': 'Kamerun',
    'is': 'Kamerún',
    'it': 'Camerun',
    'iu': 'Cameroon',
    'ja': 'カメルーン',
    'ka': 'კამერუნი',
    'ki': 'Cameroon',
    'kk': 'Камерун',
    'kl': 'Cameroon',
    'km': 'កាមេរ៉ូន',
    'kn': 'ಕ್ಯಾಮರೂನ್',
    'ko': '카메룬',
    'ku': 'Kamerûn',
    'kv': 'Cameroon',
    'kw': 'Kameroun',
    'ky': 'Камерун',
    'lo': 'Cameroon',
    'lt': 'Kamerūnas',
    'lv': 'Kamerūna',
    'mi': 'Kamarūna',
    'mk': 'Камерун',
    'ml': 'കാമറൂണ്‍',
    'mn': 'Камерун',
    'mr': 'कॅमेरून',
    'ms': 'Kamerun',
    'mt': 'Kamerun',
    'my': 'ကင်မရွန်းနိုင်ငံ',
    'na': 'Kamerun',
    'nb': 'Kamerun',
    'ne': 'क्यामरुन',
    'nl': 'Kameroen',
    'nn': 'Kamerun',
    'nv': 'Táłtłʼááh Chʼosh Daadánígíí Bitooh',
    'oc': 'Cameron',
    'or': 'କାମେଋନ',
    'pa': 'ਕੈਮਰੂਨ',
    'pi': 'केमेरून',
    'pl': 'Kamerun',
    'ps': 'کامرون',
    'pt': 'Camarões',
    'pt_BR': 'Camarões',
    'ro': 'Camerun',
    'ru': 'Камерун',
    'rw': 'Kameruni',
    'sc': 'Camerùn',
    'sd': 'Cameroon',
    'si': 'කැමරූන්',
    'sk': 'Kamerun',
    'sl': 'Kamerun',
    'so': 'Kameruun',
    'sq': 'Kamerun',
    'sr': 'Камерун',
    'sv': 'Kamerun',
    'sw': 'Kamerun',
    'ta': 'கேமரூன்',
    'te': 'కేమరూన్',
    'tg': 'Камерун',
    'th': 'แคเมอรูน',
    'ti': 'ካሜሩን',
    'tk': 'Kamerun',
    'tl': 'Kamerun',
    'tr': 'Kamerun',
    'tt': 'Камероон',
    'ug': 'كامېرون',
    'uk': 'Камерун',
    'ur': 'کیمرون',
    'uz': 'Kamerun',
    've': 'Cameroon',
    'vi': 'Ca-mơ-runh',
    'wa': 'Camrone',
    'wo': 'Kameroon',
    'xh': 'Cameroon',
    'yo': 'Kamẹrúùnù',
    'zh_CN': '喀麦隆',
    'zh_HK': '喀麥隆',
    'zh_TW': '喀麥隆',
    'zu': 'IKamerooni'
  },
);
