import '../country.dart';

const countryCOD = Country(
  alpha2: 'CD',
  alpha3: 'COD',
  continent: Continent.africa,
  countryCode: '243',
  currencyCode: 'CDF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CG',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -4.038333,
      longitude: 21.758664,
    ),
    maxCoordinate: Coordinate(
      latitude: 5.3920029,
      longitude: 31.314612,
    ),
    minCoordinate: Coordinate(
      latitude: -13.4590349,
      longitude: 12.1454,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 5.3920029,
        longitude: 31.314612,
      ),
      southwest: Coordinate(
        latitude: -13.4590349,
        longitude: 12.1454,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'COD',
  isoLongName: 'The Democratic Republic of the Congo',
  isoShortName: 'Congo (Democratic Republic of the)',
  isoShortNameLowerCase: 'Congo (the Democratic Republic of the)',
  languagesOfficial: ['fr', 'ln', 'kg', 'sw', 'lu'],
  languagesSpoken: ['fr', 'ln', 'kg', 'sw', 'lu'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: 'None',
  nationality: 'Congolese',
  number: '180',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Middle Africa',
  unLocode: 'CD',
  unMember: true,
  unofficialNames: [
    'Congo (Democratic Republic of the)',
    'Congo (Dem. Rep.)',
    'Kongo (Dem. Rep.)',
    'Congo (Rep. Dem.)',
    'コンゴ民主共和国',
    'Congo [DRC]',
    'Democratic Republic of the Congo',
    'Congo, Democratic Republic of',
    'Congo (Kinshasa)'
  ],
  vehicleRegistrationCode: 'CGO',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Congo, The Democratic Republic of the',
    'af': 'Kongo, Die Demokratiese Republiek van die',
    'ak': 'Congo, The Democratic Republic of the',
    'am': 'Congo, The Democratic Republic of the',
    'an': 'Congo, The Democratic Republic of the',
    'ar': 'الكونغو، جمهوريّة الكونغو الدّيموقراطيّة',
    'as': 'কঙ্গো, গণতান্ত্ৰিক প্ৰজাতন্ত্ৰ',
    'ay': 'Congo, The Democratic Republic of the',
    'az': 'Congo, The Democratic Republic of the',
    'ba': 'Congo, The Democratic Republic of the',
    'be': 'Конга, Дэмакратычная Рэспубліка',
    'bg': 'Конго, Демократична република',
    'bi': 'Congo, The Democratic Republic of the',
    'bn': 'কঙ্গো, গণতান্ত্রিক প্রজাতন্ত্র',
    'bn_IN': 'কঙ্গো, গণতান্ত্রিক প্রজাতন্ত্র',
    'br': 'Congo, The Democratic Republic of the',
    'bs': 'Demokratska Republika Kongo',
    'ca': 'Congo, La República Democràtica del',
    'ce': 'Congo, The Democratic Republic of the',
    'ch': 'Congo, The Democratic Republic of the',
    'cs': 'Konžská demokratická republika',
    'cv': 'Congo, The Democratic Republic of the',
    'cy': 'Congo, Gweriniaeth Ddemocrataidd y',
    'da': 'Den Demokratiske Republik Congo',
    'de': 'Demokratische Republik Kongo',
    'dv': 'Congo, The Democratic Republic of the',
    'dz': 'ཀོང་གོ་ མི་སེར་དམང་གཙོའི་ རྒྱལ་ཁབ།',
    'ee': 'Congo, The Democratic Republic of the',
    'el': 'Κονγκό, Λαϊκή Δημοκρατία του',
    'en': 'Congo, The Democratic Republic of the',
    'eo': 'Demokratia Respubliko Kongo',
    'es': 'Congo, República Democrática del',
    'et': 'Kongo Demokraatlik Vabariik',
    'eu': 'Kongoko Herri Errepublika Demokratikoa',
    'fa': 'جمهوری دموکراتیک کنگو',
    'ff': 'Congo, The Democratic Republic of the',
    'fi': 'Kongon demokraattinen tasavalta',
    'fo': 'Congo, The Democratic Republic of the',
    'fr': 'République démocratique du Congo',
    'fy': 'Congo, The Democratic Republic of the',
    'ga': 'Poblacht Dhaonlathach an Chongó',
    'gl': 'Congo, República Democrática do',
    'gn': 'Congo, The Democratic Republic of the',
    'gu': 'કોન્ગો, ડેમોક્રેટિક રીપબ્લિક ઓફ',
    'gv': 'Congo, The Democratic Republic of the',
    'ha': 'Congo, The Democratic Republic of the',
    'he': 'קונגו, הרפובליקה הדמוקרטית של',
    'hi': 'कांगो, द डेमोक्रेटिक रिपब्लिक ऑफ द',
    'hr': 'Kongo, Demokratska Repubilika',
    'ht': 'Congo, The Democratic Republic of the',
    'hu': 'Kongói Demokratikus Köztársaság',
    'hy': 'Կոնգո, -ի Դեմոկրատական Հանրապետություն',
    'ia': 'Congo, Republica Democratic del',
    'id': 'Republik Demokrat Congo',
    'io': 'Congo, The Democratic Republic of the',
    'is': 'Kongó, sambandslýðveldið',
    'it': 'Repubblica democratica del Congo',
    'iu': 'Congo, The Democratic Republic of the',
    'ja': 'コンゴ民主共和国',
    'ka': 'კონგო, დემოკრატიული რესპუბლიკა',
    'ki': 'Congo, The Democratic Republic of the',
    'kk': 'Конго Демократиялық Республикасы',
    'kl': 'Congo, The Democratic Republic of the',
    'km': 'សាធារណរដ្ឋ​ប្រជាធិបតេយ្យ​កុងហ្គោ',
    'kn': 'ಕಾಂಗೋ ಪ್ರಜಾಸತ್ತಾತ್ಮಕ ಗಣರಾಜ್ಯ',
    'ko': '콩고 민주 공화국',
    'ku': 'Komara Demokratîk a Kongo',
    'kv': 'Congo, The Democratic Republic of the',
    'kw': 'Congo, The Democratic Republic of the',
    'ky': 'Конго Республикасы',
    'lo': 'Congo, The Democratic Republic of the',
    'lt': 'Kongo Demokratinė Respublika',
    'lv': 'Kongo Demokrātiskā Republika',
    'mi': 'Congo, The Democratic Republic of the',
    'mk': 'Конго, демократска република',
    'ml': 'കോംഗോ ഡെമോക്രാറ്റിക് റിപ്പബ്ലിക്',
    'mn': 'Congo, The Democratic Republic of the',
    'mr': 'कॉंगो, दि डेमोक्रॅटिक रिपब्लिक ऑफ दि',
    'ms': 'Congo, The Democratic Republic of the',
    'mt': 'Congo, The Democratic Republic of the',
    'my': 'Congo, The Democratic Republic of the',
    'na': 'Congo, The Democratic Republic of the',
    'nb': 'Kongo, Den demokratiske republikk',
    'ne': 'कोङ्गो को प्रजातन्त्रिक गणराज्य',
    'nl': 'Congo, Democratische Republiek',
    'nn': 'Den demokratiske republikken Kongo',
    'nv': 'Congo, The Democratic Republic of the',
    'oc': 'Còngo, Republica Democratica de',
    'or': 'କୋଙ୍ଗୋ, ମଧ୍ଯ ଆଫ୍ରିକାର',
    'pa': 'ਕੌਂਗੋ, ਇਸ ਦਾ ਜਮਹੂਰੀ ਲੋਕਤੰਤਰ',
    'pi': 'Congo, The Democratic Republic of the',
    'pl': 'Kongo, Demokratyczna Republika Konga',
    'ps': 'Congo, The Democratic Republic of the',
    'pt': 'República Democrática do Congo',
    'pt_BR': 'República Democrática do Congo',
    'ro': 'Congo, Republica democrată',
    'ru': 'Демократическая Республика Конго',
    'rw': 'Repubulika Iharanira Demokarasi ya Kongo',
    'sc': 'Congo, Repùblica Democràtica de su',
    'sd': 'Congo, The Democratic Republic of the',
    'si': 'කොන්ගෝ ප්‍රජාතන්ත්‍රවාදී ජනරජය',
    'sk': 'Konžská demokratická republika',
    'sl': 'Demokratična republika Kongo',
    'so': 'Congo, The Democratic Republic of the',
    'sq': 'Kongo, Republika Demokratike e',
    'sr': 'Конго, Демократска Република',
    'sv': 'Kongo, demokratiska republiken',
    'sw': 'Congo, The Democratic Republic of the',
    'ta': 'காங்கோ குடியரசு',
    'te': 'కాంగో, ది డెమోక్రటిక్ రిపబ్లిక్ ఆఫ్ ది',
    'tg': 'Ҷумҳурии Демократии Конго',
    'th': 'คองโก, สาธารณรัฐประชาธิปไตย',
    'ti': 'ደሞክራስያዊት ሪፓብሊክ ኮንጎ',
    'tk': 'Kongo demokratik respublikasy',
    'tl': 'Congo, Ang Demokratikong Republika ng',
    'tr': 'Kongo Demokratik Cumhuriyeti',
    'tt': 'Конgо, Демократ Җөмһүриәте',
    'ug': 'كونگو دېموكراتىك جۇمھۇرىيىتى',
    'uk': 'Конго, демократична республіка',
    'ur': 'Congo, The Democratic Republic of the',
    'uz': 'Congo, The Democratic Republic of the',
    've': 'Congo, The Democratic Republic of the',
    'vi': 'Cộng hoà Dân chủ Công-gô',
    'wa': 'Congo-Kinshasa, Republike Democratike do Congo',
    'wo': 'Kongóo, Republik Demokaraatik bu',
    'xh': 'Congo, The Democratic Republic of the',
    'yo': 'Congo, The Democratic Republic of the',
    'zh_CN': '刚果民主共和国',
    'zh_HK': '剛果民主共和國',
    'zh_TW': '剛果民主共和國',
    'zu': 'Congo, The Democratic Republic of the'
  },
);
