import '../country.dart';

const countryCOG = Country(
  alpha2: 'CG',
  alpha3: 'COG',
  continent: Continent.africa,
  countryCode: '242',
  currencyCode: 'XAF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CF',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -0.228021,
      longitude: 15.827659,
    ),
    maxCoordinate: Coordinate(
      latitude: 3.707791,
      longitude: 18.650421,
    ),
    minCoordinate: Coordinate(
      latitude: -5.0964,
      longitude: 11.1182001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 3.707791,
        longitude: 18.650421,
      ),
      southwest: Coordinate(
        latitude: -5.0964,
        longitude: 11.1182001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CGO',
  isoLongName: 'The Republic of the Congo',
  isoShortName: 'Congo',
  isoShortNameLowerCase: 'Congo (the)',
  languagesOfficial: ['fr', 'ln'],
  languagesSpoken: ['fr', 'ln'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7],
  nationalPrefix: 'None',
  nationality: 'Congolese',
  number: '178',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Middle Africa',
  unLocode: 'CG',
  unMember: true,
  unofficialNames: [
    'Congo',
    'Kongo',
    'コンゴ共和国',
    'Congo [Republiek]',
    'Congo, Republic of',
    'Congo (Brazzaville)'
  ],
  vehicleRegistrationCode: 'RCB',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Congo',
    'af': 'Kongo',
    'ak': 'Congo',
    'am': 'ኮንጎ',
    'an': 'Congo',
    'ar': 'الكونغو',
    'as': 'কঙ্গো',
    'ay': 'Congo',
    'az': 'Konqo',
    'ba': 'Congo',
    'be': 'Конга',
    'bg': 'Конго',
    'bi': 'Congo',
    'bn': 'কঙ্গো',
    'bn_IN': 'কঙ্গো',
    'br': 'Congo',
    'bs': 'Kongo',
    'ca': 'Congo',
    'ce': 'Congo',
    'ch': 'Congo',
    'cs': 'Kongo',
    'cv': 'Congo',
    'cy': 'Congo',
    'da': 'Congo',
    'de': 'Kongo',
    'dv': 'Congo',
    'dz': 'ཀོང་གོ།',
    'ee': 'Congo',
    'el': 'Κονγκό',
    'en': 'Congo',
    'eo': 'Kongo',
    'es': 'Congo',
    'et': 'Kongo Vabariik',
    'eu': 'Kongo',
    'fa': 'کونگو',
    'ff': 'Congo',
    'fi': 'Kongo',
    'fo': 'Kongo',
    'fr': 'République du Congo',
    'fy': 'Congo',
    'ga': 'An Congó',
    'gl': 'Congo',
    'gn': 'Congo',
    'gu': 'કોન્ગો',
    'gv': 'Congo',
    'ha': 'Congo',
    'he': 'קונגו',
    'hi': 'कॉंगो',
    'hr': 'Kongo',
    'ht': 'Congo',
    'hu': 'Kongó',
    'hy': 'Կոնգո',
    'ia': 'Congo',
    'id': 'Congo',
    'io': 'Congo',
    'is': 'Kongó',
    'it': 'Congo',
    'iu': 'Congo',
    'ja': 'コンゴ',
    'ka': 'კონგო',
    'ki': 'Congo',
    'kk': 'Конго',
    'kl': 'Congo',
    'km': 'កុងហ្គោ',
    'kn': 'ಕಾಂಗೋ',
    'ko': '콩고',
    'ku': 'Kongo',
    'kv': 'Congo',
    'kw': 'Congo',
    'ky': 'Конго',
    'lo': 'Congo',
    'lt': 'Kongas',
    'lv': 'Kongo',
    'mi': 'Kōngo',
    'mk': 'Конго',
    'ml': 'കോംഗോ',
    'mn': 'Конго',
    'mr': 'कॉंगो',
    'ms': 'Kongo',
    'mt': 'Kongo',
    'my': 'Congo',
    'na': 'Congo',
    'nb': 'Kongo',
    'ne': 'कोङ्गो',
    'nl': 'Congo',
    'nn': 'Kongo',
    'nv': 'Congo',
    'oc': 'Còngo',
    'or': 'କଙ୍ଗୋ',
    'pa': 'ਕਾਂਗੋ',
    'pi': 'Congo',
    'pl': 'Kongo',
    'ps': 'Congo',
    'pt': 'Congo',
    'pt_BR': 'Congo',
    'ro': 'Congo',
    'ru': 'Конго',
    'rw': 'Kongo',
    'sc': 'Congo',
    'sd': 'Congo',
    'si': 'කොන්ගෝව',
    'sk': 'Kongo',
    'sl': 'Kongo',
    'so': 'Congo',
    'sq': 'Kongo',
    'sr': 'Конго',
    'sv': 'Kongo',
    'sw': 'Congo',
    'ta': 'காங்கோ',
    'te': 'కాంగో',
    'tg': 'Конго',
    'th': 'คองโก',
    'ti': 'ኮንጎ',
    'tk': 'Kongo',
    'tl': 'Congo',
    'tr': 'Kongo',
    'tt': 'Конgо',
    'ug': 'كونگو',
    'uk': 'Конго',
    'ur': 'Congo',
    'uz': 'Congo',
    've': 'Congo',
    'vi': 'Công-gô',
    'wa': 'Congo-Brazza',
    'wo': 'Kongóo',
    'xh': 'Congo',
    'yo': 'Congo',
    'zh_CN': '刚果',
    'zh_HK': '剛果',
    'zh_TW': '剛果',
    'zu': 'Congo'
  },
);
