import '../country.dart';

const countryCZE = Country(
  alpha2: 'CZ',
  alpha3: 'CZE',
  continent: Continent.europe,
  countryCode: '420',
  currencyCode: 'CZK',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'EZ',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 49.81749199999999,
      longitude: 15.472962,
    ),
    maxCoordinate: Coordinate(
      latitude: 51.0557185,
      longitude: 18.8592361,
    ),
    minCoordinate: Coordinate(
      latitude: 48.5518081,
      longitude: 12.090589,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 51.0557185,
        longitude: 18.8592361,
      ),
      southwest: Coordinate(
        latitude: 48.5518081,
        longitude: 12.090589,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'CZE',
  isoLongName: 'The Czech Republic',
  isoShortName: 'Czechia',
  isoShortNameLowerCase: null,
  languagesOfficial: ['cs'],
  languagesSpoken: ['cs'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: 'None',
  nationality: 'Czech',
  number: '203',
  postalCode: true,
  postalCodeFormat: '\\d{3} ?\\d{2}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Eastern Europe',
  unLocode: 'CZ',
  unMember: true,
  unofficialNames: [
    'Czech Republic',
    'Tschechische Republik',
    'République Tchèque',
    'República Checa',
    'チェコ',
    'Tsjechië',
    'Czechia',
    'Česká republika'
  ],
  vehicleRegistrationCode: 'CZ',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 21,
    reduced: [12],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Czechia',
    'af': 'Tsjeggië',
    'ak': 'Czechia',
    'am': 'Czechia',
    'an': 'Czechia',
    'ar': 'التشيك',
    'as': 'Czechia',
    'ay': 'Czechia',
    'az': 'Czechia',
    'ba': 'Czechia',
    'be': 'Чэхія',
    'bg': 'Чехия',
    'bi': 'Czechia',
    'bn': 'চেকিয়া',
    'bn_IN': 'চেচিয়া',
    'br': 'Czechia',
    'bs': 'Czechia',
    'ca': 'Txèquia',
    'ce': 'Czechia',
    'ch': 'Czechia',
    'cs': 'Česko',
    'cv': 'Czechia',
    'cy': 'Tsiecia',
    'da': 'Tjekkiet',
    'de': 'Tschechien',
    'dv': 'Czechia',
    'dz': 'Czechia',
    'ee': 'Czechia',
    'el': 'Τσεχία',
    'en': 'Czechia',
    'eo': 'Ĉeĥio',
    'es': 'Chequia',
    'et': 'Tšehhi',
    'eu': 'Txekia',
    'fa': 'چک',
    'ff': 'Czechia',
    'fi': 'Czechia',
    'fo': 'Czechia',
    'fr': 'Tchéquie',
    'fy': 'Czechia',
    'ga': 'Czechia',
    'gl': 'Chequia',
    'gn': 'Czechia',
    'gu': 'ચેકિયા',
    'gv': 'Czechia',
    'ha': 'Czechia',
    'he': 'צ\'כיה',
    'hi': 'चेकिया',
    'hr': 'Češka',
    'ht': 'Tchèki',
    'hu': 'Csehország',
    'hy': 'Czechia',
    'ia': 'Cechia',
    'id': 'Czechia',
    'io': 'Czechia',
    'is': 'Tékkland',
    'it': 'Cechia',
    'iu': 'Czechia',
    'ja': 'チェコ共和国',
    'ka': 'Czechia',
    'ki': 'Czechia',
    'kk': 'Czechia',
    'kl': 'Czechia',
    'km': 'ឆេក',
    'kn': 'Czechia',
    'ko': '체코',
    'ku': 'Çekistan',
    'kv': 'Czechia',
    'kw': 'Czechia',
    'ky': 'Чехия Республикасы',
    'lo': 'Czechia',
    'lt': 'Čekija',
    'lv': 'Czechia',
    'mi': 'Czechia',
    'mk': 'Czechia',
    'ml': 'Czechia',
    'mn': 'Czechia',
    'mr': 'झेकिया',
    'ms': 'Czechia',
    'mt': 'Czechia',
    'my': 'Czechia',
    'na': 'Czechia',
    'nb': 'Tsjekkia',
    'ne': 'Czechia',
    'nl': 'Tsjechië',
    'nn': 'Czechia',
    'nv': 'Czechia',
    'oc': 'Chequia',
    'or': 'ଚେସିଆ',
    'pa': 'ਚੇਚੀਆ',
    'pi': 'Czechia',
    'pl': 'Czechy',
    'ps': 'Czechia',
    'pt': 'República Checa',
    'pt_BR': 'Chéquia',
    'ro': 'Cehia',
    'ru': 'Чехия',
    'rw': 'Czechia',
    'sc': 'Tzèchia',
    'sd': 'Czechia',
    'si': 'Czechia',
    'sk': 'Česko',
    'sl': 'Czechia',
    'so': 'Czechia',
    'sq': 'Çeki',
    'sr': 'Чешка',
    'sv': 'Tjeckien',
    'sw': 'Czechia',
    'ta': 'Czechia',
    'te': 'Czechia',
    'tg': 'Чехия',
    'th': 'ประเทศเช็กเกีย',
    'ti': 'Czechia',
    'tk': 'Çehiýa',
    'tl': 'Czechia',
    'tr': 'Çekya',
    'tt': 'Czechia',
    'ug': 'چېخ',
    'uk': 'Чехія',
    'ur': 'Czechia',
    'uz': 'Czechia',
    've': 'Czechia',
    'vi': 'Czechia',
    'wa': 'Czechia',
    'wo': 'Czechia',
    'xh': 'Czechia',
    'yo': 'Czechia',
    'zh_CN': '捷克',
    'zh_HK': '捷克',
    'zh_TW': '捷克',
    'zu': 'Czechia'
  },
);
