import '../country.dart';

const countryDNK = Country(
  alpha2: 'DK',
  alpha3: 'DNK',
  continent: Continent.europe,
  countryCode: '45',
  currencyCode: 'DKK',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'DA',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 56.26392,
      longitude: 9.501785,
    ),
    maxCoordinate: Coordinate(
      latitude: 58.02846,
      longitude: 15.2298,
    ),
    minCoordinate: Coordinate(
      latitude: 54.4317001,
      longitude: 7.855200099999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 58.02846,
        longitude: 15.2298,
      ),
      southwest: Coordinate(
        latitude: 54.4317001,
        longitude: 7.855200099999999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'DEN',
  isoLongName: 'The Kingdom of Denmark',
  isoShortName: 'Denmark',
  isoShortNameLowerCase: null,
  languagesOfficial: ['da'],
  languagesSpoken: ['da'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Danish',
  number: '208',
  postalCode: true,
  postalCodeFormat: '\\d{4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Northern Europe',
  unLocode: 'DK',
  unMember: true,
  unofficialNames: [
    'Denmark',
    'Dänemark',
    'Danemark',
    'Dinamarca',
    'デンマーク',
    'Denemarken'
  ],
  vehicleRegistrationCode: 'DK',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 25,
    reduced: [],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Denmark',
    'af': 'Denemarke',
    'ak': 'Denmark',
    'am': '፤ንሢሴጤ',
    'an': 'Denmark',
    'ar': 'الدّنمارك',
    'as': 'ডেনমাৰ্ক',
    'ay': 'Denmark',
    'az': 'Danimarka',
    'ba': 'Denmark',
    'be': 'Данія',
    'bg': 'Дания',
    'bi': 'Denmark',
    'bn': 'ডেনমার্ক',
    'bn_IN': 'ডেনমার্ক',
    'br': 'Danmark',
    'bs': 'Denmark',
    'ca': 'Dinamarca',
    'ce': 'Дани',
    'ch': 'Denmark',
    'cs': 'Dánsko',
    'cv': 'Дани',
    'cy': 'Denmarc',
    'da': 'Danmark',
    'de': 'Dänemark',
    'dv': 'ޑެންމާކު',
    'dz': 'ཌེན་མཱརཀ།',
    'ee': 'Denmark',
    'el': 'Δανία',
    'en': 'Denmark',
    'eo': 'Danio',
    'es': 'Dinamarca',
    'et': 'Taani',
    'eu': 'Danimarka',
    'fa': 'دانمارک',
    'ff': 'Danemark',
    'fi': 'Tanska',
    'fo': 'Danmørk',
    'fr': 'Danemark',
    'fy': 'Denemark',
    'ga': 'An Danmhairg',
    'gl': 'Dinamarca',
    'gn': 'Denmark',
    'gu': 'ડેનમાર્ક',
    'gv': 'Yn Danvarg',
    'ha': 'Denmark',
    'he': 'דנמרק',
    'hi': 'डेनमार्क',
    'hr': 'Danska',
    'ht': 'Danmak',
    'hu': 'Dánia',
    'hy': 'Դանիա',
    'ia': 'Danmark',
    'id': 'Denmark',
    'io': 'Dania',
    'is': 'Danmörk',
    'it': 'Danimarca',
    'iu': 'Denmark',
    'ja': 'デンマーク',
    'ka': 'დანია',
    'ki': 'Denmark',
    'kk': 'Дания',
    'kl': 'Denmark',
    'km': 'ដាណឺម៉ាក',
    'kn': 'ಡೆನ್ಮಾರ್ಕ್',
    'ko': '덴마크',
    'ku': 'Danîmarka',
    'kv': 'Дания',
    'kw': 'Danmark',
    'ky': 'Дания',
    'lo': 'ປະເທດດານມາກ',
    'lt': 'Danija',
    'lv': 'Dānija',
    'mi': 'Tenemāka',
    'mk': 'Данска',
    'ml': 'ഡെന്മാര്‍ക്ക്',
    'mn': 'Дани',
    'mr': 'डेन्मार्क',
    'ms': 'Denmark',
    'mt': 'Danimarka',
    'my': 'ဒိန်းမတ်နိုင်ငံ',
    'na': 'Denemark',
    'nb': 'Danmark',
    'ne': 'डेनमार्क',
    'nl': 'Denemarken',
    'nn': 'Danmark',
    'nv': 'Denmark',
    'oc': 'Danemarc',
    'or': 'ଡେନମାର୍କ',
    'pa': 'ਡੈਨਮਾਰਕ',
    'pi': 'डेनमार्क',
    'pl': 'Dania',
    'ps': 'ډنمارک',
    'pt': 'Dinamarca',
    'pt_BR': 'Dinamarca',
    'ro': 'Danemarca',
    'ru': 'Дания',
    'rw': 'Danimarike',
    'sc': 'Danimarca',
    'sd': 'Denmark',
    'si': 'ඩෙන්මාකය',
    'sk': 'Dánsko',
    'sl': 'Danska',
    'so': 'Danmaark',
    'sq': 'Danimarkë',
    'sr': 'Данска',
    'sv': 'Danmark',
    'sw': 'Denmark',
    'ta': 'டென்மார்க்',
    'te': 'డెన్మార్క్',
    'tg': 'Дания',
    'th': 'เดนมาร์ก',
    'ti': 'ዴንማርክ',
    'tk': 'Daniýa',
    'tl': 'Denmark',
    'tr': 'Danimarka',
    'tt': 'Даниа',
    'ug': 'دانىيە',
    'uk': 'Данія',
    'ur': 'ڈنمارک',
    'uz': 'Daniya',
    've': 'Denmark',
    'vi': 'Đan Mạch',
    'wa': 'Daenmåtche',
    'wo': 'Danmaark',
    'xh': 'Denmark',
    'yo': 'Dẹ́nmárkì',
    'zh_CN': '丹麦',
    'zh_HK': '丹麥',
    'zh_TW': '丹麥',
    'zu': 'IDenimaki'
  },
);
