import '../country.dart';

const countryDZA = Country(
  alpha2: 'DZ',
  alpha3: 'DZA',
  continent: Continent.africa,
  countryCode: '213',
  currencyCode: 'DZD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'AG',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 28.033886,
      longitude: 1.659626,
    ),
    maxCoordinate: Coordinate(
      latitude: 37.2216,
      longitude: 11.9999992,
    ),
    minCoordinate: Coordinate(
      latitude: 18.9681469,
      longitude: -8.6676111,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 37.2216,
        longitude: 11.9999992,
      ),
      southwest: Coordinate(
        latitude: 18.9681469,
        longitude: -8.6676111,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ALG',
  isoLongName: 'The People\'s Democratic Republic of Algeria',
  isoShortName: 'Algeria',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar'],
  languagesSpoken: ['ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '7',
  nationality: 'Algerian',
  number: '012',
  postalCode: true,
  postalCodeFormat: r'\d{5}',
  region: Region.africa,
  startOfWeek: Week.sunday,
  subregion: 'Northern Africa',
  unLocode: 'DZ',
  unMember: true,
  unofficialNames: [
    'Algeria',
    'الجزائر',
    'Algerien',
    'Algérie',
    'Argelia',
    'アルジェリア',
    'Algerije'
  ],
  vehicleRegistrationCode: 'DZ',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Algeria",
    "af": "Algerië",
    "ak": "Algeria",
    "am": "ጐሔጄሱ።",
    "an": "Algeria",
    "ar": "الجزائر",
    "as": "আলজেৰিযা",
    "ay": "Algeria",
    "az": "Əlcəzair",
    "ba": "Algeria",
    "be": "Алжыр",
    "bg": "Алжир",
    "bi": "Algeria",
    "bn": "অ্যালজিরিয়া",
    "bn_IN": "অ্যালজিরিয়া",
    "br": "Aljeria",
    "bs": "Alžir",
    "ca": "Algèria",
    "ce": "Алжир",
    "ch": "Algeria",
    "cs": "Alžírsko",
    "cv": "Алжир",
    "cy": "Algeria",
    "da": "Algeriet",
    "de": "Algerien",
    "dv": "ޖަޒާއިރު",
    "dz": "ཨཱལ་ཇི་རི་ཡ།",
    "ee": "Algeria",
    "el": "Αλγερία",
    "en": "Algeria",
    "eo": "Alĝerio",
    "es": "Argelia",
    "et": "Alžeeria",
    "eu": "Aljeria",
    "fa": "الجزایر",
    "ff": "Aljeri",
    "fi": "Algeria",
    "fo": "Algeria",
    "fr": "Algérie",
    "fy": "Algerije",
    "ga": "An Ailgéir",
    "gl": "Alxeria",
    "gn": "Algeria",
    "gu": "અલ્જેરિયા",
    "gv": "Yn Algear",
    "ha": "Aljeriya",
    "he": "אלג'יריה",
    "hi": "अल्जीरिया",
    "hr": "Alžir",
    "ht": "Aljeri",
    "hu": "Algéria",
    "hy": "Ալժիր",
    "ia": "Algeria",
    "id": "Aljazair",
    "io": "Aljeria",
    "is": "Alsír",
    "it": "Algeria",
    "iu": "Algeria",
    "ja": "アルジェリア",
    "ka": "ალჟირი",
    "ki": "Algeria",
    "kk": "Алжир",
    "kl": "Algeria",
    "km": "អាល់ហ្សេរី",
    "kn": "ಅಲ್ಜೀರಿಯ",
    "ko": "알제리",
    "ku": "Cezayîr",
    "kv": "Algeria",
    "kw": "Aljeri",
    "ky": "Алжир",
    "lo": "Algeria",
    "lt": "Alžyras",
    "lv": "Alžīrija",
    "mi": "Algeria",
    "mk": "Алжир",
    "ml": "അള്‍ജീരിയ",
    "mn": "Алжир",
    "mr": "अल्जिरिया",
    "ms": "Algeria",
    "mt": "Alġerija",
    "my": "အယ်လ်ဂျီးရီးယားနိုင်ငံ",
    "na": "Ardjiriya",
    "nb": "Algerie",
    "ne": "अल्जेरिया",
    "nl": "Algerije",
    "nn": "Algerie",
    "nv": "Ghą́ą́ʼaskʼidii Biłikahii Bikéyah Ntsaaígíí",
    "oc": "Argeria",
    "or": "ଆଲଜେରିୟା",
    "pa": "ਅਲਜੀਰੀਆ",
    "pi": "अल्जीरिया",
    "pl": "Algieria",
    "ps": "الجزایر",
    "pt": "Argélia",
    "pt_BR": "Argélia",
    "ro": "Algeria",
    "ru": "Алжир",
    "rw": "Aligeriya",
    "sc": "Algeria",
    "sd": "الجزائر",
    "si": "ඇල්ජීරියා",
    "sk": "Alžírsko",
    "sl": "Alžirija",
    "so": "Aljeeriya",
    "sq": "Algjeri",
    "sr": "Алжир",
    "sv": "Algeriet",
    "sw": "Aljeria",
    "ta": "அல்ஜீரியா",
    "te": "అల్జిరియా",
    "tg": "Алҷазоир",
    "th": "แอลจีเรีย",
    "ti": "አልጄሪያ",
    "tk": "Alžyr",
    "tl": "Alheriya",
    "tr": "Cezayir",
    "tt": "Алжыр",
    "ug": "ئالجىرىيە",
    "uk": "Алжир",
    "ur": "الجزائر",
    "uz": "Jazoir",
    "ve": "Algeria",
    "vi": "An-giê-ri",
    "wa": "Aldjereye",
    "wo": "Aljeeri",
    "xh": "Algeria",
    "yo": "Àlgéríà",
    "zh_CN": "阿尔及利亚",
    "zh_HK": "阿爾及利亞",
    "zh_TW": "阿爾及利亞",
    "zu": "IAljiriya"
  },
);
