import '../country.dart';

const countryESP = Country(
  alpha2: 'ES',
  alpha3: 'ESP',
  continent: Continent.europe,
  countryCode: '34',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'SP',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 40.46366700000001,
      longitude: -3.74922,
    ),
    maxCoordinate: Coordinate(
      latitude: 43.8504,
      longitude: 4.6362,
    ),
    minCoordinate: Coordinate(
      latitude: 27.4985,
      longitude: -18.2648001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 43.8504,
        longitude: 4.6362,
      ),
      southwest: Coordinate(
        latitude: 27.4985,
        longitude: -18.2648001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ESP',
  isoLongName: 'The Kingdom of Spain',
  isoShortName: 'Spain',
  isoShortNameLowerCase: null,
  languagesOfficial: ['es'],
  languagesSpoken: ['es', 'ca', 'gl', 'eu', 'an', 'ast', 'fax', 'rif', 'rmq'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: 'None',
  nationality: 'Spanish',
  number: '724',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Southern Europe',
  unLocode: 'ES',
  unMember: true,
  unofficialNames: ['Spain', 'Spanien', 'Espagne', 'España', 'スペイン', 'Spanje'],
  vehicleRegistrationCode: 'E',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{region}}\n{{country}}',
  vatRates: VatRates(
    standard: 21,
    reduced: [10],
    superReduced: 4,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Spain',
    'af': 'Spanje',
    'ak': 'Spain',
    'am': 'ስፔን',
    'an': 'Spain',
    'ar': 'إسبانيا',
    'as': 'স্পেইন',
    'ay': 'Spain',
    'az': 'İspaniya',
    'ba': 'Spain',
    'be': 'Іспанія',
    'bg': 'Испания',
    'bi': 'Spain',
    'bn': 'স্পেন',
    'bn_IN': 'স্পেন',
    'br': 'Spagn',
    'bs': 'Španija',
    'ca': 'Espanya',
    'ce': 'Испани',
    'ch': 'España',
    'cs': 'Španělsko',
    'cv': 'Испани',
    'cy': 'Sbaen',
    'da': 'Spanien',
    'de': 'Spanien',
    'dv': 'އިސްޕެއިން',
    'dz': 'སིཔེན།',
    'ee': 'Spain',
    'el': 'Ισπανία',
    'en': 'Spain',
    'eo': 'Hispanio',
    'es': 'España',
    'et': 'Hispaania',
    'eu': 'Espainia',
    'fa': 'اسپانیا',
    'ff': 'Hispaanya',
    'fi': 'Espanja',
    'fo': 'Spania',
    'fr': 'Espagne',
    'fy': 'Spanje',
    'ga': 'An Spáinn',
    'gl': 'España',
    'gn': 'Spain',
    'gu': 'સ્પેન',
    'gv': 'Yn Spaainey',
    'ha': 'An Spàinn',
    'he': 'ספרד',
    'hi': 'स्पेन',
    'hr': 'Španjolska',
    'ht': 'Espay',
    'hu': 'Spanyolország',
    'hy': 'Իսպանիա',
    'ia': 'Espania',
    'id': 'Spanyol',
    'io': 'Hispania',
    'is': 'Spánn',
    'it': 'Spagna',
    'iu': 'ᓯᐸᐃᓐ',
    'ja': 'スペイン',
    'ka': 'ესპანეთი',
    'ki': 'Spain',
    'kk': 'Испания',
    'kl': 'Spain',
    'km': 'អេស្ប៉ាញ',
    'kn': 'ಸ್ಪೇನ್',
    'ko': '스페인',
    'ku': 'Spanya',
    'kv': 'Испания',
    'kw': 'Spayn',
    'ky': 'Испания',
    'lo': 'ປະເທດແອສະປາຍ',
    'lt': 'Ispanija',
    'lv': 'Spānija',
    'mi': 'Pāniora',
    'mk': 'Шпанија',
    'ml': 'സ്പെയിന്‍',
    'mn': 'Испани',
    'mr': 'स्पेन',
    'ms': 'Sepanyol',
    'mt': 'Spanja',
    'my': 'စပိန်နိုင်ငံ',
    'na': 'Pain',
    'nb': 'Spania',
    'ne': 'स्पेन',
    'nl': 'Spanje',
    'nn': 'Spania',
    'nv': 'Dibé Diníí Bikéyah',
    'oc': 'Espanha',
    'or': 'ସ୍ପେନ',
    'pa': 'ਸਪੇਨ',
    'pi': 'स्पेन',
    'pl': 'Hiszpania',
    'ps': 'هسپانیه',
    'pt': 'Espanha',
    'pt_BR': 'Espanha',
    'ro': 'Spania',
    'ru': 'Испания',
    'rw': 'Esipanye',
    'sc': 'Ispagna',
    'sd': 'اسپين',
    'si': 'ස්පාඤ්ඤය',
    'sk': 'Španielsko',
    'sl': 'Španija',
    'so': 'Isbeyn',
    'sq': 'Spanjë',
    'sr': 'Шпанија',
    'sv': 'Spanien',
    'sw': 'Spain',
    'ta': 'ஸ்பெயின்',
    'te': 'స్పెయిన్',
    'tg': 'Испания',
    'th': 'สเปน',
    'ti': 'ስጳኛ',
    'tk': 'Ispaniýa',
    'tl': 'Espanya',
    'tr': 'İspanya',
    'tt': 'İспаниа',
    'ug': 'ئىسپانىيە',
    'uk': 'Іспанія',
    'ur': 'ہسپانیہ',
    'uz': 'Ispaniya',
    've': 'Spain',
    'vi': 'Tây Ban Nha',
    'wa': 'Espagne',
    'wo': 'Ispaañ',
    'xh': 'Spain',
    'yo': 'Spéìn',
    'zh_CN': '西班牙',
    'zh_HK': '西班牙',
    'zh_TW': '西班牙',
    'zu': 'ISpeyini'
  },
);
