import '../country.dart';

const countryETH = Country(
  alpha2: 'ET',
  alpha3: 'ETH',
  continent: Continent.africa,
  countryCode: '251',
  currencyCode: 'ETB',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'ET',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 9.145000000000001,
      longitude: 40.489673,
    ),
    maxCoordinate: Coordinate(
      latitude: 14.8942141,
      longitude: 48.0010561,
    ),
    minCoordinate: Coordinate(
      latitude: 3.4041369,
      longitude: 32.997734,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 14.8942141,
        longitude: 48.0010561,
      ),
      southwest: Coordinate(
        latitude: 3.4041369,
        longitude: 32.997734,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ETH',
  isoLongName: 'The Federal Democratic Republic of Ethiopia',
  isoShortName: 'Ethiopia',
  isoShortNameLowerCase: null,
  languagesOfficial: ['am'],
  languagesSpoken: ['am'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '0',
  nationality: 'Ethiopian',
  number: '231',
  postalCode: true,
  postalCodeFormat: '\\d{4}',
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Eastern Africa',
  unLocode: 'ET',
  unMember: true,
  unofficialNames: [
    'Ethiopia',
    'Äthiopien',
    'Éthiopie',
    'Etiopía',
    'エチオピア',
    'Ethiopië'
  ],
  vehicleRegistrationCode: 'ETH',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Ethiopia',
    'af': 'Etiopië',
    'ak': 'Ethiopia',
    'am': 'ጒት፥ጵ።',
    'an': 'Ethiopia',
    'ar': 'إثيوبيا',
    'as': 'ইথিওপিয়া',
    'ay': 'Ethiopia',
    'az': 'Efiopiya',
    'ba': 'Ethiopia',
    'be': 'Эфіопія',
    'bg': 'Етиопия',
    'bi': 'Ethiopia',
    'bn': 'ইথিওপিয়া',
    'bn_IN': 'ইথিওপিয়া',
    'br': 'Etiopia',
    'bs': 'Etiopija',
    'ca': 'Etiòpia',
    'ce': 'Эфиопи',
    'ch': 'Ethiopia',
    'cs': 'Etiopie',
    'cv': 'Эфиопи',
    'cy': 'Ethiopia',
    'da': 'Etiopien',
    'de': 'Äthiopien',
    'dv': 'ޙަބުޝްކަރަ',
    'dz': 'ཨི་ཐོ་པི་ཡ།',
    'ee': 'Ethiopia',
    'el': 'Αιθιοπία',
    'en': 'Ethiopia',
    'eo': 'Etiopio',
    'es': 'Etiopía',
    'et': 'Etioopia',
    'eu': 'Etiopia',
    'fa': 'اتیوپی',
    'ff': 'Ethiopia',
    'fi': 'Etiopia',
    'fo': 'Etiopia',
    'fr': 'Éthiopie',
    'fy': 'Etioopje',
    'ga': 'An Aetóip',
    'gl': 'Etiopía',
    'gn': 'Ethiopia',
    'gu': 'ઇથોપિયા',
    'gv': 'Yn Eetoip',
    'ha': 'Ethiopia',
    'he': 'אתיופיה',
    'hi': 'इथियोपिया',
    'hr': 'Etiopija',
    'ht': 'Etyopi',
    'hu': 'Etiópia',
    'hy': 'Եթովպիա',
    'ia': 'Ethiopia',
    'id': 'Ethiopia',
    'io': 'Etiopia',
    'is': 'Eþíópía',
    'it': 'Etiopia',
    'iu': 'Ethiopia',
    'ja': 'エチオピア',
    'ka': 'ეთიოპია',
    'ki': 'Ethiopia',
    'kk': 'Эфиопия',
    'kl': 'Ethiopia',
    'km': 'អេត្យូពី',
    'kn': 'ಎಥಿಯೋಪಿಯಾ',
    'ko': '에티오피아',
    'ku': 'Etîyopya',
    'kv': 'Эфиопия',
    'kw': 'Ethiopi',
    'ky': 'Эфиопия',
    'lo': 'ເອທິໂອເປຍ',
    'lt': 'Etiopija',
    'lv': 'Etiopija',
    'mi': 'Etiopia',
    'mk': 'Етиопија',
    'ml': 'എത്യോപ്യ',
    'mn': 'Этопи',
    'mr': 'इथिओपिया',
    'ms': 'Ethiopia',
    'mt': 'Etjopja',
    'my': 'အီသီယိုးပီးယားနိုင်ငံ',
    'na': 'Itiyopiya',
    'nb': 'Etiopia',
    'ne': 'इथियोपिया',
    'nl': 'Ethiopië',
    'nn': 'Etiopia',
    'nv': 'Ethiopia',
    'oc': 'Etiopia',
    'or': 'ଇଥୋପିୟା',
    'pa': 'ਈਥੋਪਈਆ',
    'pi': 'ईथ्योपिया',
    'pl': 'Etiopia',
    'ps': 'حبشه',
    'pt': 'Etiópia',
    'pt_BR': 'Etiópia',
    'ro': 'Etiopia',
    'ru': 'Эфиопия',
    'rw': 'Etiyopiya',
    'sc': 'Etiòpia',
    'sd': 'Ethiopia',
    'si': 'ඉතියෝපියාව',
    'sk': 'Etiópia',
    'sl': 'Etiopija',
    'so': 'Itoobiya',
    'sq': 'Etiopi',
    'sr': 'Етиопија',
    'sv': 'Etiopien',
    'sw': 'Ethiopia',
    'ta': 'எதியோப்பியா',
    'te': 'ఇథియోపియా',
    'tg': 'Ҳабашистон',
    'th': 'เอธิโอเปีย',
    'ti': 'ኢትዮጵያ',
    'tk': 'Efiopiýa',
    'tl': 'Ethiopia',
    'tr': 'Etiyopya',
    'tt': 'Ефиопиа',
    'ug': 'ئېفىيوپىيە',
    'uk': 'Ефіопія',
    'ur': 'ایتھوپیا',
    'uz': 'Efiopiya',
    've': 'Ethiopia',
    'vi': 'Ê-ti-ô-pi-a',
    'wa': 'Etiopeye',
    'wo': 'Ecoopi',
    'xh': 'Ethiopia',
    'yo': 'Ethiópíà',
    'zh_CN': '埃塞俄比亚',
    'zh_HK': '埃塞俄比亞',
    'zh_TW': '衣索比亞',
    'zu': 'I-Ithiopia'
  },
);
