import '../country.dart';

const countryFIN = Country(
  alpha2: 'FI',
  alpha3: 'FIN',
  continent: Continent.europe,
  countryCode: '358',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'FI',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 61.92410999999999,
      longitude: 25.7481511,
    ),
    maxCoordinate: Coordinate(
      latitude: 70.0922932,
      longitude: 31.5870999,
    ),
    minCoordinate: Coordinate(
      latitude: 59.693623,
      longitude: 20.4565002,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 70.0922932,
        longitude: 31.5870999,
      ),
      southwest: Coordinate(
        latitude: 59.693623,
        longitude: 20.4565002,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'FIN',
  isoLongName: 'The Republic of Finland',
  isoShortName: 'Finland',
  isoShortNameLowerCase: null,
  languagesOfficial: ['fi', 'sv'],
  languagesSpoken: ['fi', 'sv'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '0',
  nationality: 'Finnish',
  number: '246',
  postalCode: true,
  postalCodeFormat: r'\d{5}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Northern Europe',
  unLocode: 'FI',
  unMember: true,
  unofficialNames: ['Finland', 'Finnland', 'Finlande', 'Finlandia', 'フィンランド'],
  vehicleRegistrationCode: 'FIN',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 25.5,
    reduced: [10.0, 14.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Finland",
    "af": "Finland",
    "ak": "Finland",
    "am": "ፑንሒን፥",
    "an": "Finland",
    "ar": "فنلندا",
    "as": "ফিনলেণ্ড",
    "ay": "Finland",
    "az": "Finlandiya",
    "ba": "Finland",
    "be": "Фінляндыя",
    "bg": "Финландия",
    "bi": "Finland",
    "bn": "ফিনল্যান্ড",
    "bn_IN": "ফিনল্যান্ড",
    "br": "Finland",
    "bs": "Finska",
    "ca": "Finlàndia",
    "ce": "Финлянди",
    "ch": "Finlandia",
    "cs": "Finsko",
    "cv": "Финлянди",
    "cy": "Y Ffindir",
    "da": "Finland",
    "de": "Finnland",
    "dv": "ފިންލޭންޑު",
    "dz": "ཕིན་ལེནཌི།",
    "ee": "Finland",
    "el": "Φινλανδία",
    "en": "Finland",
    "eo": "Finnlando",
    "es": "Finlandia",
    "et": "Soome",
    "eu": "Finlandia",
    "fa": "فنلاند",
    "ff": "Finland",
    "fi": "Suomi",
    "fo": "Finnland",
    "fr": "Finlande",
    "fy": "Finlân",
    "ga": "An Fhionlainn",
    "gl": "Finlandia",
    "gn": "Finland",
    "gu": "ફિનલેન્ડ",
    "gv": "Finnlynn",
    "ha": "Finland",
    "he": "פינלנד",
    "hi": "फ़िनलैण्ड",
    "hr": "Finska",
    "ht": "Fenlann",
    "hu": "Finnország",
    "hy": "Ֆինլանդիա",
    "ia": "Finlandia",
    "id": "Finlandia",
    "io": "Finlando",
    "is": "Finnland",
    "it": "Finlandia",
    "iu": "ᐃᓐᓚᓐᑦ",
    "ja": "フィンランド",
    "ka": "ფინეთი",
    "ki": "Finland",
    "kk": "Финляндия",
    "kl": "Finland",
    "km": "ហ្វាំងឡង់",
    "kn": "ಫಿನ್ಲಂಡ್",
    "ko": "핀란드",
    "ku": "Fînlandiya",
    "kv": "Суоми Му",
    "kw": "Pow Finn",
    "ky": "Финляндия",
    "lo": "ປະເທດແຟງລັງ",
    "lt": "Suomija",
    "lv": "Somija",
    "mi": "Hinerangi",
    "mk": "Финска",
    "ml": "ഫിന്‍ലന്‍ഡ്",
    "mn": "Финнлянд",
    "mr": "फिनलॅंड",
    "ms": "Finland",
    "mt": "Finlandja",
    "my": "ဖင်လန်နိုင်ငံ",
    "na": "Pinrand",
    "nb": "Finland",
    "ne": "फिन्ल्यान्ड",
    "nl": "Finland",
    "nn": "Finland",
    "nv": "Nahoditsʼǫʼłání Dineʼé Bikéyah",
    "oc": "Finlàndia",
    "or": "ଫିନଲ୍ଯାଣ୍ଡ",
    "pa": "ਫ਼ਿਨਲੈਂਡ",
    "pi": "फिन्लैंड",
    "pl": "Finlandia",
    "ps": "فنلینډ",
    "pt": "Finlândia",
    "pt_BR": "Finlândia",
    "ro": "Finlanda",
    "ru": "Финляндия",
    "rw": "Finilande",
    "sc": "Finlàndia",
    "sd": "فن لينڊ",
    "si": "ෆින්ලන්තය",
    "sk": "Fínsko",
    "sl": "Finska",
    "so": "Fiinlaand",
    "sq": "Finlandë",
    "sr": "Финска",
    "sv": "Finland",
    "sw": "Finland",
    "ta": "பின்லாந்து",
    "te": "ఫిన్‌లాండ్",
    "tg": "Финляндия",
    "th": "ฟินแลนด์",
    "ti": "ፊንላንድ",
    "tk": "Finlýandiýa",
    "tl": "Finland",
    "tr": "Finlandiya",
    "tt": "Финланд (Суоми)",
    "ug": "فىنلاندىيە",
    "uk": "Фінляндія",
    "ur": "فن لینڈ",
    "uz": "Finlandiya",
    "ve": "Finland",
    "vi": "Phần Lan",
    "wa": "Finlande",
    "wo": "Finlaand",
    "xh": "Finland",
    "yo": "Fínlándì",
    "zh_CN": "芬兰",
    "zh_HK": "芬蘭",
    "zh_TW": "芬蘭",
    "zu": "IFinlandi"
  },
);
