import '../country.dart';

const countryGBR = Country(
  alpha2: 'GB',
  alpha3: 'GBR',
  continent: Continent.europe,
  countryCode: '44',
  currencyCode: 'GBP',
  distanceUnit: DistanceUnit.miles,
  gec: 'UK',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 55.378051,
      longitude: -3.435973,
    ),
    maxCoordinate: Coordinate(
      latitude: 60.91569999999999,
      longitude: 1.68153079591,
    ),
    minCoordinate: Coordinate(
      latitude: 49.959999905,
      longitude: -7.57216793459,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 60.91569999999999,
        longitude: 1.68153079591,
      ),
      southwest: Coordinate(
        latitude: 49.959999905,
        longitude: -7.57216793459,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'GBR',
  isoLongName: 'The United Kingdom of Great Britain and Northern Ireland',
  isoShortName: 'United Kingdom of Great Britain and Northern Ireland',
  isoShortNameLowerCase:
      'United Kingdom of Great Britain and Northern Ireland (the)',
  languagesOfficial: ['en'],
  languagesSpoken: ['en'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10, 11],
  nationalPrefix: '0',
  nationality: 'British',
  number: '826',
  postalCode: true,
  postalCodeFormat:
      'GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Northern Europe',
  unLocode: 'GB',
  unMember: true,
  unofficialNames: [
    'United Kingdom',
    'The United Kingdom',
    'United Kingdom of Great Britain and Northern Ireland',
    'England',
    'Großbritannien',
    'Vereinigtes Königreich',
    'Royaume-Uni',
    'Reino Unido',
    'イギリス',
    'Verenigd Koninkrijk',
    'Great Britain (UK)',
    'UK',
    'Великобритания',
    'Velká Británie',
    'İngiltere',
    'Великобританія',
    'Great Britain'
  ],
  vehicleRegistrationCode: 'UK',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{city}}\n{{region}}\n{{postalcode}}\n{{country}}',
  vatRates: VatRates(
    standard: 20,
    reduced: [5],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: true,
  g20Member: true,
  isoShortNameByLocale: {
    'ab': 'United Kingdom',
    'af': 'Verenidge Koninkryk',
    'ak': 'United Kingdom',
    'am': 'ጕንጔሑፔ',
    'an': 'United Kingdom',
    'ar': 'المملكة المتحدة',
    'as': 'যুক্তৰাজ্য',
    'ay': 'United Kingdom',
    'az': 'United Kingdom',
    'ba': 'United Kingdom',
    'be': 'Злучанае Каралеўства',
    'bg': 'Обединено кралство',
    'bi': 'United Kingdom',
    'bn': 'যুক্তরাজ্য',
    'bn_IN': 'যুক্তরাজ্য',
    'br': 'Rouantelezh-Unanet',
    'bs': 'Velika Britanija',
    'ca': 'Regne Unit',
    'ce': 'Йоккха Британи',
    'ch': 'United Kingdom',
    'cs': 'Spojené království',
    'cv': 'Йоккха Британи',
    'cy': 'Y Deyrnas Unedig',
    'da': 'Storbritannien',
    'de': 'Vereinigtes Königreich',
    'dv': 'ޔުނައިޓެޑް ކިންގްޑަމް',
    'dz': 'ཡུ་ནའི་ཊེཊ་ ཀིང་ཌོམ།',
    'ee': 'United Kingdom',
    'el': 'Ηνωμένο Βασίλειο',
    'en': 'United Kingdom',
    'eo': 'Britio',
    'es': 'Reino Unido',
    'et': 'Suurbritannia',
    'eu': 'Erresuma Batua',
    'fa': 'انگلستان',
    'ff': 'Biritaani-Mawndi',
    'fi': 'Yhdistynyt kuningaskunta',
    'fo': 'United Kingdom',
    'fr': 'Royaume-Uni',
    'fy': 'Grut-Brittanje',
    'ga': 'An Ríocht Aontaithe',
    'gl': 'Reino Unido',
    'gn': 'United Kingdom',
    'gu': 'યુનાઇટેડ કિંગડમ',
    'gv': 'Reeriaght Unnaneysit',
    'ha': 'Birtaniya',
    'he': 'הממלכה המאוחדת',
    'hi': 'यूनाइटेड किंगडम',
    'hr': 'Ujedinjeno Kraljevstvo',
    'ht': 'Wayòm Ini',
    'hu': 'Egyesült Királyság',
    'hy': 'Մեծ Բրիտանիա',
    'ia': 'Regno Unite',
    'id': 'Britania Raya',
    'io': 'Unionita Rejio',
    'is': 'Bretland',
    'it': 'Regno Unito',
    'iu': 'ᑐᓗᐃᑦ ᓄᓈᑦ',
    'ja': '英国',
    'ka': 'გაერთიანებული სამეფო',
    'ki': 'United Kingdom',
    'kk': 'Ұлыбритания',
    'kl': 'United Kingdom',
    'km': 'ចក្រភព​អង់គ្លេស',
    'kn': 'ಯುನೈಟೆಡ್ ಕಿಂಗ್ಡಮ್',
    'ko': '영국',
    'ku': 'Şahitiya Yekbuyî',
    'kv': 'Ыджыд Британия',
    'kw': 'Ruwvaneth Unys',
    'ky': 'Улуу Британия',
    'lo': 'ສະຫະລາຊະອານາຈັກ',
    'lt': 'Jungtinė Karalystė',
    'lv': 'Lielbritānija',
    'mi': 'Kīngitanga Kotahi',
    'mk': 'Велика Британија',
    'ml': 'യുണൈറ്റഡ് കിങ്ഡം',
    'mn': 'Нэгдсэн Вант Улс',
    'mr': 'युनायटेड किंगडम',
    'ms': 'United Kingdom',
    'mt': 'Ingilterra',
    'my': 'ယူနိုက်တက် ကင်းဒမ်း',
    'na': 'Ingerand',
    'nb': 'Storbritannia',
    'ne': 'संयुक्त अधिराज्य',
    'nl': 'Verenigd Koninkrijk',
    'nn': 'Storbritannia',
    'nv': 'Tó Táʼ Dinéʼiʼ Bikéyah',
    'oc': 'Reialme Unit',
    'or': 'ଯୁକ୍ତ ରାଜ୍ଯ',
    'pa': 'ਬਰਤਾਨੀਆ',
    'pi': 'United Kingdom',
    'pl': 'Wielka Brytania',
    'ps': 'برتانیه',
    'pt': 'Reino Unido',
    'pt_BR': 'Reino Unido',
    'ro': 'Regatul Unit',
    'ru': 'Соединённое Королевство',
    'rw': 'Ubwongereza (UK)',
    'sc': 'Rennu Unidu',
    'sd': 'United Kingdom',
    'si': 'එක්සත් රාජධානිය',
    'sk': 'Spojené kráľovstvo',
    'sl': 'Združeno kraljestvo',
    'so': 'Midowga boqortooyada Britan',
    'sq': 'Mbretëria e Bashkuar',
    'sr': 'Уједињено Краљевство',
    'sv': 'Storbritannien',
    'sw': 'United Kingdom',
    'ta': 'ஐக்கிய இராஜ்ஜியம்',
    'te': 'యునైటెడ్ కింగ్‌డమ్',
    'tg': 'Шоҳигарии Муттаҳида',
    'th': 'สหราชอาณาจักร',
    'ti': 'ብሪጣንያ',
    'tk': 'Birleşen Patyşalyk',
    'tl': 'Nagkaisang Kaharian',
    'tr': 'Birleşik Krallık',
    'tt': 'Берләшкән Падшаһлык',
    'ug': 'ئەنگلىيە',
    'uk': 'Велика Британія',
    'ur': 'برطانیہ',
    'uz': 'Birlashgan Qirollik',
    've': 'United Kingdom',
    'vi': 'Vương Quốc Anh Thống Nhất',
    'wa': 'Rweyåme Uni',
    'wo': 'Ruwaayom bu Bennoo',
    'xh': 'United Kingdom',
    'yo': 'Ilẹ̀ọba Aṣọ̀kan',
    'zh_CN': '英国',
    'zh_HK': '英國',
    'zh_TW': '英國',
    'zu': 'Umbuso Ohlangeneyo'
  },
);
