import '../country.dart';

const countryGRC = Country(
  alpha2: 'GR',
  alpha3: 'GRC',
  continent: Continent.europe,
  countryCode: '30',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'GR',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 39.074208,
      longitude: 21.824312,
    ),
    maxCoordinate: Coordinate(
      latitude: 41.7488784,
      longitude: 29.6527999,
    ),
    minCoordinate: Coordinate(
      latitude: 34.5428,
      longitude: 19.3098,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 41.7488784,
        longitude: 29.6527999,
      ),
      southwest: Coordinate(
        latitude: 34.5428,
        longitude: 19.3098,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'GRE',
  isoLongName: 'The Hellenic Republic',
  isoShortName: 'Greece',
  isoShortNameLowerCase: null,
  languagesOfficial: ['el'],
  languagesSpoken: ['el'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10],
  nationalPrefix: 'None',
  nationality: 'Greek',
  number: '300',
  postalCode: true,
  postalCodeFormat: '\\d{3} ?\\d{2}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Southern Europe',
  unLocode: 'GR',
  unMember: true,
  unofficialNames: [
    'Greece',
    'Griechenland',
    'Grèce',
    'Grecia',
    'ギリシャ',
    'Griekenland'
  ],
  vehicleRegistrationCode: 'GR',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 24,
    reduced: [6, 13],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Greece',
    'af': 'Griekeland',
    'ak': 'Greece',
    'am': 'ጔሱጤ',
    'an': 'Greece',
    'ar': 'اليونان',
    'as': 'গ্ইচ্‌লামিকীচ',
    'ay': 'Greece',
    'az': 'Yunanıstan',
    'ba': 'Greece',
    'be': 'Грэцыя',
    'bg': 'Гърция',
    'bi': 'Greece',
    'bn': 'গ্রিস',
    'bn_IN': 'গ্রিস',
    'br': 'Gres',
    'bs': 'Grčka',
    'ca': 'Grècia',
    'ce': 'Грекийн',
    'ch': 'Greece',
    'cs': 'Řecko',
    'cv': 'Грекийн',
    'cy': 'Groeg',
    'da': 'Grækenland',
    'de': 'Griechenland',
    'dv': 'ޔޫނާން',
    'dz': 'གིརིསི་།',
    'ee': 'Greece',
    'el': 'Ελλάδα',
    'en': 'Greece',
    'eo': 'Grekio',
    'es': 'Grecia',
    'et': 'Kreeka',
    'eu': 'Grezia',
    'fa': 'یونان',
    'ff': 'Yunan',
    'fi': 'Kreikka',
    'fo': 'Grikkaland',
    'fr': 'Grèce',
    'fy': 'Grikelân',
    'ga': 'An Ghréig',
    'gl': 'Grecia',
    'gn': 'Greece',
    'gu': 'ગ્રીસ',
    'gv': 'Yn Ghreag',
    'ha': 'Greek',
    'he': 'יוון',
    'hi': 'यूनान',
    'hr': 'Grčka',
    'ht': 'Grès',
    'hu': 'Görögország',
    'hy': 'Հունաստան',
    'ia': 'Grecia',
    'id': 'Yunani',
    'io': 'Grekia',
    'is': 'Grikkland',
    'it': 'Grecia',
    'iu': 'Greece',
    'ja': 'ギリシャ',
    'ka': 'საბერძნეთი',
    'ki': 'Ngiriki',
    'kk': 'Грекия',
    'kl': 'Greece',
    'km': 'ក្រិក',
    'kn': 'ಗ್ರೀಸ್',
    'ko': '그리스',
    'ku': 'Yewnanistan',
    'kv': 'Эллада',
    'kw': 'Pow Grek',
    'ky': 'Греция',
    'lo': 'ປະເທດກະແລັດ',
    'lt': 'Graikija',
    'lv': 'Grieķija',
    'mi': 'Kirihi',
    'mk': 'Грција',
    'ml': 'ഗ്രീസ്',
    'mn': 'Грек',
    'mr': 'ग्रीस',
    'ms': 'Yunani',
    'mt': 'Greċja',
    'my': 'ဂရိနိုင်ငံ',
    'na': 'Grit',
    'nb': 'Hellas',
    'ne': 'ग्रीस',
    'nl': 'Griekenland',
    'nn': 'Hellas',
    'nv': 'Gwíík Dineʼé Bikéyah',
    'oc': 'Grècia',
    'or': 'ଗ୍ରୀସ',
    'pa': 'ਗਰੀਸ',
    'pi': 'ग्रीस (यूनान)',
    'pl': 'Grecja',
    'ps': 'یونان',
    'pt': 'Grécia',
    'pt_BR': 'Grécia',
    'ro': 'Grecia',
    'ru': 'Греция',
    'rw': 'Ikigereki',
    'sc': 'Grètzia',
    'sd': 'يونان',
    'si': 'ග්‍රීසිය',
    'sk': 'Grécko',
    'sl': 'Grčija',
    'so': 'Giriigga',
    'sq': 'Greqi',
    'sr': 'Грчка',
    'sv': 'Grekland',
    'sw': 'Greece',
    'ta': 'கிரீஸ்',
    'te': 'గ్రీస్',
    'tg': 'Юнон',
    'th': 'กรีซ',
    'ti': 'ግሪኽ',
    'tk': 'Gresiýa',
    'tl': 'Gresya',
    'tr': 'Yunanistan',
    'tt': 'Юнанстан',
    'ug': 'گىرېتسىيە',
    'uk': 'Греція',
    'ur': 'یونان',
    'uz': 'Yunoniston',
    've': 'Greece',
    'vi': 'Hy Lạp',
    'wa': 'Grece',
    'wo': 'Girees',
    'xh': 'Greece',
    'yo': 'Gríìsì',
    'zh_CN': '希腊',
    'zh_HK': '希臘',
    'zh_TW': '希臘',
    'zu': 'IGreki'
  },
);
