import '../country.dart';

const countryHUN = Country(
  alpha2: 'HU',
  alpha3: 'HUN',
  continent: Continent.europe,
  countryCode: '36',
  currencyCode: 'HUF',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'HU',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 47.162494,
      longitude: 19.5033041,
    ),
    maxCoordinate: Coordinate(
      latitude: 48.585234,
      longitude: 22.8965438,
    ),
    minCoordinate: Coordinate(
      latitude: 45.7370889,
      longitude: 16.1133078,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 48.585234,
        longitude: 22.8965438,
      ),
      southwest: Coordinate(
        latitude: 45.7370889,
        longitude: 16.1133078,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'HUN',
  isoLongName: 'Hungary',
  isoShortName: 'Hungary',
  isoShortNameLowerCase: null,
  languagesOfficial: ['hu'],
  languagesSpoken: ['hu'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9],
  nationalPrefix: '06',
  nationality: 'Hungarian',
  number: '348',
  postalCode: true,
  postalCodeFormat: r'\d{4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Eastern Europe',
  unLocode: 'HU',
  unMember: true,
  unofficialNames: [
    'Hungary',
    'Ungarn',
    'Hongrie',
    'Hungría',
    'ハンガリー',
    'Hongarije'
  ],
  vehicleRegistrationCode: 'H',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{city}}
{{street}}
{{postalcode}}
{{country}}''',
  vatRates: VatRates(
    standard: 27.0,
    reduced: [5.0, 18.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Hungary",
    "af": "Hongarye",
    "ak": "Hungary",
    "am": "ሀንጒሱ",
    "an": "Hungary",
    "ar": "المجر (هنغاريا)",
    "as": "হাংগেৰী",
    "ay": "Hungary",
    "az": "Macarıstan",
    "ba": "Hungary",
    "be": "Венгрыя",
    "bg": "Унгария",
    "bi": "Hungary",
    "bn": "হাঙ্গেরি",
    "bn_IN": "হাঙ্গেরি",
    "br": "Hungaria",
    "bs": "Mađarska",
    "ca": "Hongria",
    "ce": "Венгри",
    "ch": "Hungary",
    "cs": "Maďarsko",
    "cv": "Венгри",
    "cy": "Hwngari",
    "da": "Ungarn",
    "de": "Ungarn",
    "dv": "ހަންގޭރީ",
    "dz": "ཧང་ག་རི།",
    "ee": "Hungary",
    "el": "Ουγγαρία",
    "en": "Hungary",
    "eo": "Hungario",
    "es": "Hungría",
    "et": "Ungari",
    "eu": "Hungaria",
    "fa": "مجارستان",
    "ff": "Hunngariya",
    "fi": "Unkari",
    "fo": "Ungarn",
    "fr": "Hongrie",
    "fy": "Hongarije",
    "ga": "An Ungáir",
    "gl": "Hungría",
    "gn": "Hungary",
    "gu": "હંગેરી",
    "gv": "Yn Ungaar",
    "ha": "Hungariya",
    "he": "הונגריה",
    "hi": "हंगरी",
    "hr": "Mađarska",
    "ht": "Ongri",
    "hu": "Magyarország",
    "hy": "Հունգարիա",
    "ia": "Hungaria",
    "id": "Hongaria",
    "io": "Hungaria",
    "is": "Ungverjaland",
    "it": "Ungheria",
    "iu": "Hungary",
    "ja": "ハンガリー",
    "ka": "უნგრეთი",
    "ki": "Macartsa",
    "kk": "Венгрия",
    "kl": "Hungary",
    "km": "ហុងគ្រី",
    "kn": "ಹಂಗರಿ",
    "ko": "헝가리",
    "ku": "Macaristan",
    "kv": "Мадьяр Му",
    "kw": "Hungari",
    "ky": "Мажарстан",
    "lo": "ປະເທດຮົງກະລີ",
    "lt": "Vengrija",
    "lv": "Ungārija",
    "mi": "Hanekari",
    "mk": "Унгарија",
    "ml": "ഹംഗറി",
    "mn": "Унгар",
    "mr": "हंगेरी",
    "ms": "Hungari",
    "mt": "Ungerija",
    "my": "ဟန်ဂေရီနိုင်ငံ",
    "na": "Ungari",
    "nb": "Ungarn",
    "ne": "हङ्गेरी",
    "nl": "Hongarije",
    "nn": "Ungarn",
    "nv": "Hángewii",
    "oc": "Ongria",
    "or": "ହଙ୍ଗାରୀ",
    "pa": "ਹੰਗਰੀ",
    "pi": "हंगरी",
    "pl": "Węgry",
    "ps": "مجارستان",
    "pt": "Hungria",
    "pt_BR": "Hungria",
    "ro": "Ungaria",
    "ru": "Венгрия",
    "rw": "Hongiriya",
    "sc": "Ungheria",
    "sd": "Hungary",
    "si": "හංගේරියාව",
    "sk": "Maďarsko",
    "sl": "Madžarska",
    "so": "Hangeri",
    "sq": "Hungari",
    "sr": "Мађарска",
    "sv": "Ungern",
    "sw": "Hungary",
    "ta": "ஹங்கேரி",
    "te": "హంగేరీ",
    "tg": "Маҷористон",
    "th": "ฮังการี",
    "ti": "ሀንጋሪ",
    "tk": "Wengriýa",
    "tl": "Hungary",
    "tr": "Macaristan",
    "tt": "Маҗарстан",
    "ug": "ۋېنگىرىيە",
    "uk": "Угорщина",
    "ur": "مجارستان",
    "uz": "Mojariston",
    "ve": "Hungary",
    "vi": "Hun-ga-ri",
    "wa": "Hongreye",
    "wo": "Oonguri",
    "xh": "Hungary",
    "yo": "Húngárì",
    "zh_CN": "匈牙利",
    "zh_HK": "匈牙利",
    "zh_TW": "匈牙利",
    "zu": "I-Hungariya"
  },
);
