import '../country.dart';

const countryIDN = Country(
  alpha2: 'ID',
  alpha3: 'IDN',
  continent: Continent.asia,
  countryCode: '62',
  currencyCode: 'IDR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'ID',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -0.789275,
      longitude: 113.921327,
    ),
    maxCoordinate: Coordinate(
      latitude: 6.216999899999999,
      longitude: 141.0425,
    ),
    minCoordinate: Coordinate(
      latitude: -11.1082999,
      longitude: 94.7351,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 6.216999899999999,
        longitude: 141.0425,
      ),
      southwest: Coordinate(
        latitude: -11.1082999,
        longitude: 94.7351,
      ),
    ),
  ),
  internationalPrefix: '001',
  ioc: 'INA',
  isoLongName: 'The Republic of Indonesia',
  isoShortName: 'Indonesia',
  isoShortNameLowerCase: null,
  languagesOfficial: ['id'],
  languagesSpoken: ['id'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9, 10, 11],
  nationalPrefix: '0',
  nationality: 'Indonesian',
  number: '360',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'South-Eastern Asia',
  unLocode: 'ID',
  unMember: true,
  unofficialNames: [
    'Indonesia',
    'Indonesien',
    'Indonésie',
    'インドネシア',
    'Indonesië'
  ],
  vehicleRegistrationCode: 'RI',
  worldRegion: WorldRegion.apac,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{city}}\n{{region}} {{postalcode}}\n{{country}}',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: true,
  isoShortNameByLocale: {
    'ab': 'Indonesia',
    'af': 'Indonesië',
    'ak': 'Indonesia',
    'am': 'ጒን፦ኔፒ።',
    'an': 'Indonesia',
    'ar': 'إندونيسيا',
    'as': 'ইণ্ডোনেছিয়া',
    'ay': 'Indonesia',
    'az': 'İndoneziya',
    'ba': 'Indonesia',
    'be': 'Інданезія',
    'bg': 'Индонезия',
    'bi': 'Indonesia',
    'bn': 'ইন্দোনেশিয়া',
    'bn_IN': 'ইন্দোনেশিয়া',
    'br': 'Indonezia',
    'bs': 'Indonezija',
    'ca': 'Indonèsia',
    'ce': 'Индонези',
    'ch': 'Indonesia',
    'cs': 'Indonésie',
    'cv': 'Индонези',
    'cy': 'Indonesia',
    'da': 'Indonesien',
    'de': 'Indonesien',
    'dv': 'އިންޑޮނޭޝިޔާ',
    'dz': 'ཨིན་ཌོ་ནེ་ཤི་ཡ།',
    'ee': 'Indonesia',
    'el': 'Ινδονησία',
    'en': 'Indonesia',
    'eo': 'Indonezio',
    'es': 'Indonesia',
    'et': 'Indoneesia',
    'eu': 'Indonesia',
    'fa': 'اندونزی',
    'ff': 'Indonesia',
    'fi': 'Indonesia',
    'fo': 'Indonesia',
    'fr': 'Indonésie',
    'fy': 'Yndoneezje',
    'ga': 'An Indinéis',
    'gl': 'Indonesia',
    'gn': 'Indonesia',
    'gu': 'ઇન્ડોનેશિયા',
    'gv': 'Yn Indoneesh',
    'ha': 'Indonesiya',
    'he': 'אינדונזיה',
    'hi': 'इंडोनेशिया',
    'hr': 'Indonezija',
    'ht': 'Endonezi',
    'hu': 'Indonézia',
    'hy': 'Ինդոնեզիա',
    'ia': 'Indonesia',
    'id': 'Indonesia',
    'io': 'Indonezia',
    'is': 'Indónesía',
    'it': 'Indonesia',
    'iu': 'ᐄᓅᓯᐊ',
    'ja': 'インドネシア',
    'ka': 'ინდონეზია',
    'ki': 'Indonesia',
    'kk': 'Индонезия',
    'kl': 'Indonesia',
    'km': 'ឥណ្ឌូនេស៊ី',
    'kn': 'ಇಂಡೋನೇಶಿಯಾ',
    'ko': '인도네시아',
    'ku': 'Endonezya',
    'kv': 'Индонезия',
    'kw': 'Indonesi',
    'ky': 'Индонезия',
    'lo': 'ປະເທດອິນໂດເນເຊຍ',
    'lt': 'Indonezija',
    'lv': 'Indonēzija',
    'mi': 'Initonīhia',
    'mk': 'Индонезија',
    'ml': 'ഇന്തോനേഷ്യ',
    'mn': 'Индонез',
    'mr': 'इंडोनेशिया',
    'ms': 'Indonesia',
    'mt': 'Indoneżja',
    'my': 'အင်ဒိုနီးရှားနိုင်ငံ',
    'na': 'Indonitsiya',
    'nb': 'Indonesia',
    'ne': 'इन्डोनेसिया',
    'nl': 'Indonesië',
    'nn': 'Indonesia',
    'nv': 'Kéyah Dah Ndaaʼeełí Łání',
    'oc': 'Indonesia',
    'or': 'ଇଣ୍ଡୋନେଶିୟା',
    'pa': 'ਇੰਡੋਨੇਸ਼ੀਆ',
    'pi': 'इन्दोनेशिया',
    'pl': 'Indonezja',
    'ps': 'اندونیزیا',
    'pt': 'Indonésia',
    'pt_BR': 'Indonésia',
    'ro': 'Indonezia',
    'ru': 'Индонезия',
    'rw': 'Indonesiya',
    'sc': 'Indonèsia',
    'sd': 'انڊونيشيا',
    'si': 'ඉන්දුනීසියාව',
    'sk': 'Indonézia',
    'sl': 'Indonezija',
    'so': 'Indoneesiya',
    'sq': 'Indonezi',
    'sr': 'Индонезија',
    'sv': 'Indonesien',
    'sw': 'Indonesia',
    'ta': 'இந்தோனேசியா',
    'te': 'ఇండోనేషియా',
    'tg': 'Индонезия',
    'th': 'อินโดนีเซีย',
    'ti': 'ኢንዶኔዢያ',
    'tk': 'Indoneziýa',
    'tl': 'Indonesia',
    'tr': 'Endonezya',
    'tt': 'İндонесиа',
    'ug': 'ھىندونېزىيە',
    'uk': 'Індонезія',
    'ur': 'انڈونیشیا',
    'uz': 'Indoneziya',
    've': 'Indonesia',
    'vi': 'Nam Dương',
    'wa': 'Indonezeye',
    'wo': 'Indoneesi',
    'xh': 'Indonesia',
    'yo': 'Indonésíà',
    'zh_CN': '印度尼西亚',
    'zh_HK': '印尼',
    'zh_TW': '印度尼西亞',
    'zu': 'I-Indonesia'
  },
);
