import '../country.dart';

const countryIND = Country(
  alpha2: 'IN',
  alpha3: 'IND',
  continent: Continent.asia,
  countryCode: '91',
  currencyCode: 'INR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'IN',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 20.593684,
      longitude: 78.96288,
    ),
    maxCoordinate: Coordinate(
      latitude: 35.513327,
      longitude: 97.39535869999999,
    ),
    minCoordinate: Coordinate(
      latitude: 6.4626999,
      longitude: 68.1097,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 35.513327,
        longitude: 97.39535869999999,
      ),
      southwest: Coordinate(
        latitude: 6.4626999,
        longitude: 68.1097,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'IND',
  isoLongName: 'The Republic of India',
  isoShortName: 'India',
  isoShortNameLowerCase: null,
  languagesOfficial: ['hi', 'en'],
  languagesSpoken: ['hi', 'en'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10],
  nationalPrefix: '0',
  nationality: 'Indian',
  number: '356',
  postalCode: true,
  postalCodeFormat: r'\d{6}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Southern Asia',
  unLocode: 'IN',
  unMember: true,
  unofficialNames: ['India', 'Indien', 'Inde', 'インド'],
  vehicleRegistrationCode: 'IND',
  worldRegion: WorldRegion.apac,
  addressFormat: '''{{recipient}}
{{street}}
{{region}}
{{city}} {{postalcode}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: true,
  isoShortNameByLocale: {
    "ab": "India",
    "af": "Indië",
    "ak": "India",
    "am": "ህን፥",
    "an": "India",
    "ar": "الهند",
    "as": "ভাৰত",
    "ay": "India",
    "az": "Hindistan",
    "ba": "India",
    "be": "Індыя",
    "bg": "Индия",
    "bi": "India",
    "bn": "ভারত",
    "bn_IN": "ভারত",
    "br": "India",
    "bs": "Indija",
    "ca": "Índia",
    "ce": "Инди",
    "ch": "India",
    "cs": "Indie",
    "cv": "Инди",
    "cy": "India",
    "da": "Indien",
    "de": "Indien",
    "dv": "އިންޑިޔާ",
    "dz": "རྒྱ་གར།",
    "ee": "India",
    "el": "Ινδία",
    "en": "India",
    "eo": "Barato",
    "es": "India",
    "et": "India",
    "eu": "India",
    "fa": "هندوستان",
    "ff": "India",
    "fi": "Intia",
    "fo": "India",
    "fr": "Inde",
    "fy": "Yndia",
    "ga": "An India",
    "gl": "A India",
    "gn": "India",
    "gu": "ભારત",
    "gv": "Yn Injey",
    "ha": "Indiya",
    "he": "הודו",
    "hi": "भारत",
    "hr": "Indija",
    "ht": "End",
    "hu": "India",
    "hy": "Հնդկաստան",
    "ia": "India",
    "id": "India",
    "io": "India",
    "is": "Indland",
    "it": "India",
    "iu": "ᐃᓐᑎᐊ",
    "ja": "インド",
    "ka": "ინდოეთი",
    "ki": "India",
    "kk": "Үндістан",
    "kl": "India",
    "km": "ឥណ្ឌា",
    "kn": "ಭಾರತ",
    "ko": "인도",
    "ku": "Hindistan",
    "kv": "Индия",
    "kw": "Eynda",
    "ky": "Индия",
    "lo": "India",
    "lt": "Indija",
    "lv": "Indija",
    "mi": "Īnia",
    "mk": "Индија",
    "ml": "ഇന്ത്യ",
    "mn": "Энэтхэг",
    "mr": "भारत",
    "ms": "Hindia",
    "mt": "Indja",
    "my": "အိန္ဒိယနိုင်ငံ",
    "na": "Indjiya",
    "nb": "India",
    "ne": "भारत",
    "nl": "India",
    "nn": "India",
    "nv": "Tó Wónaanídę́ę́ʼ Bitsįʼ Yishtłizhii Bikéyah",
    "oc": "Índia",
    "or": "ଭାରତ",
    "pa": "ਭਾਰਤ",
    "pi": "भारत",
    "pl": "Indie",
    "ps": "هند",
    "pt": "Índia",
    "pt_BR": "Índia",
    "ro": "India",
    "ru": "Индия",
    "rw": "Ubuhinde",
    "sc": "Ìndia",
    "sd": "ڀارت",
    "si": "ඉන්දියාව",
    "sk": "India",
    "sl": "Indija",
    "so": "Hindiya",
    "sq": "Indi",
    "sr": "Индија",
    "sv": "Indien",
    "sw": "India",
    "ta": "இந்தியா",
    "te": "భారతదేశము",
    "tg": "Ҳиндустон",
    "th": "อินเดีย",
    "ti": "ህንዲ",
    "tk": "Hindistan",
    "tl": "Indiya",
    "tr": "Hindistan",
    "tt": "Һиндстан",
    "ug": "ھىندىستان",
    "uk": "Індія",
    "ur": "بھارت",
    "uz": "Hindiston",
    "ve": "India",
    "vi": "Ấn-độ",
    "wa": "Inde",
    "wo": "Eend",
    "xh": "India",
    "yo": "Índíà",
    "zh_CN": "印度",
    "zh_HK": "印度",
    "zh_TW": "印度",
    "zu": "India"
  },
);
