import '../country.dart';

const countryIRN = Country(
  alpha2: 'IR',
  alpha3: 'IRN',
  continent: Continent.asia,
  countryCode: '98',
  currencyCode: 'IRR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'IR',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 32.427908,
      longitude: 53.688046,
    ),
    maxCoordinate: Coordinate(
      latitude: 39.782056,
      longitude: 63.3333366,
    ),
    minCoordinate: Coordinate(
      latitude: 24.8066999,
      longitude: 44.0326949,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 39.782056,
        longitude: 63.3333366,
      ),
      southwest: Coordinate(
        latitude: 24.8066999,
        longitude: 44.0326949,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'IRI',
  isoLongName: 'The Islamic Republic of Iran',
  isoShortName: 'Iran (Islamic Republic of)',
  isoShortNameLowerCase: null,
  languagesOfficial: ['fa'],
  languagesSpoken: ['fa'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10],
  nationalPrefix: '0',
  nationality: 'Iranian',
  number: '364',
  postalCode: true,
  postalCodeFormat: '\\d{5}-?\\d{5}',
  region: Region.asia,
  startOfWeek: Week.saturday,
  subregion: 'Southern Asia',
  unLocode: 'IR',
  unMember: true,
  unofficialNames: [
    'Iran',
    'Irán',
    'Iran (Islamic Republic Of)',
    'イラン・イスラム共和国',
    'Islamic Republic of Iran'
  ],
  vehicleRegistrationCode: 'IR',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Iran, Islamic Republic of',
    'af': 'Iran, Islamitiese Republiek van',
    'ak': 'Iran, Islamic Republic of',
    'am': 'Iran, Islamic Republic of',
    'an': 'Iran, Islamic Republic of',
    'ar': 'إيران، الجمهوريّة الإسلاميّة الإيرانيّة',
    'as': 'ইৰান, ইচ্‌লামিক প্ৰজাতন্ত্ৰ',
    'ay': 'Iran, Islamic Republic of',
    'az': 'Iran, Islamic Republic of',
    'ba': 'Iran, Islamic Republic of',
    'be': 'Іран, Ісламская Рэспубліка',
    'bg': 'Иран, Ислямска република',
    'bi': 'Iran, Islamic Republic of',
    'bn': 'ইরান, ইসলামিক প্রজাতন্ত্র',
    'bn_IN': 'ইরান, ইসলামিক প্রজাতন্ত্র',
    'br': 'Iran, Islamic Republic of',
    'bs': 'Islamska Republika Iran',
    'ca': 'Iran',
    'ce': 'Iran, Islamic Republic of',
    'ch': 'Iran, Islamic Republic of',
    'cs': 'Írán, islámská republika',
    'cv': 'Iran, Islamic Republic of',
    'cy': 'Iran, Gweriniaeth Islamaidd',
    'da': 'Iran, Den Islamiske Republik',
    'de': 'Iran, Islamische Republik',
    'dv': 'Iran, Islamic Republic of',
    'dz': 'ཨི་རཱན་ ཨིས་ལ་མིཀ་ མི་སེར་རྒྱལ་ཁབ།',
    'ee': 'Iran, Islamic Republic of',
    'el': 'Ιράν, Ισλαμική Δημοκρατία του',
    'en': 'Iran',
    'eo': 'Irano, Islama Respubliko',
    'es': 'Irán, República islámica de',
    'et': 'Iraan',
    'eu': 'Iran, Islamiar Errepublika',
    'fa': 'ایران',
    'ff': 'Iran, Islamic Republic of',
    'fi': 'Iranin islamilainen tasavalta',
    'fo': 'Iran, Islamic Republic of',
    'fr': 'Iran, République islamique d\'',
    'fy': 'Iran, Islamic Republic of',
    'ga': 'An Iaráin',
    'gl': 'Irán, República Islámica de',
    'gn': 'Iran, Islamic Republic of',
    'gu': 'ઇરાન, ઇસ્લામિક રીપબ્લિક ઓફ',
    'gv': 'Iran, Islamic Republic of',
    'ha': 'Iran, Islamic Republic of',
    'he': 'אירן, הרפובליקה האיסלמית של',
    'hi': 'ईरान, इस्लामिक रिपब्लिक ऑफ',
    'hr': 'Iran, Islamska Republika',
    'ht': 'Iran, Islamic Republic of',
    'hu': 'Irán, Iszlám Köztársaság',
    'hy': 'Իրան, -ի Իսլամական Հանրապետություն',
    'ia': 'Iran',
    'id': 'Iran, Republik Islam',
    'io': 'Iran, Islamic Republic of',
    'is': 'Íran, íslamska lýðveldið',
    'it': 'Iran',
    'iu': 'Iran, Islamic Republic of',
    'ja': 'イラン・イスラム共和国',
    'ka': 'ირანის ისლამური რესპუბლიკა',
    'ki': 'Iran, Islamic Republic of',
    'kk': 'Иран',
    'kl': 'Iran, Islamic Republic of',
    'km': '​អ៊ីរ៉ង់ សាធារណ​រដ្ឋ​អ៊ីស្លាម​នៃ',
    'kn': 'ಇರಾನ್ ಇಸ್ಲಾಮಿಕ್ ಗಣರಾಜ್ಯ',
    'ko': '이란 이슬람 공화국',
    'ku': 'Îran, Komara Îslamî ya',
    'kv': 'Iran, Islamic Republic of',
    'kw': 'Iran, Islamic Republic of',
    'ky': 'Иран',
    'lo': 'Iran, Islamic Republic of',
    'lt': 'Irano Islamo Respublika',
    'lv': 'Irāna',
    'mi': 'Iran, Islamic Republic of',
    'mk': 'Иран',
    'ml': 'ഇറാന്‍, ഇസ്ലാമിക് റിപ്പബ്ലിക് ഓഫ്',
    'mn': 'Iran, Islamic Republic of',
    'mr': 'इराण, इस्लामिक रिपब्लिक ऑफ',
    'ms': 'Iran, Islamic Republic of',
    'mt': 'Iran, Islamic Republic of',
    'my': 'Iran, Islamic Republic of',
    'na': 'Iran, Islamic Republic of',
    'nb': 'Iran, Den islamske republikk',
    'ne': 'इरान, इस्लामिक गणराज्य',
    'nl': 'Iran',
    'nn': 'Iran',
    'nv': 'Iran, Islamic Republic of',
    'oc': 'Republica Dominicana',
    'or': 'ଇରାନ, ଇସଲାମିକ ଗଣତନ୍ତ୍ର',
    'pa': 'ਈਰਾਨ, ਮੁਸਲਮਾਨ ਗਣਰਾਜ',
    'pi': 'Iran, Islamic Republic of',
    'pl': 'Iran',
    'ps': 'Iran, Islamic Republic of',
    'pt': 'Irão',
    'pt_BR': 'Irã',
    'ro': 'Iran, Republica islamică',
    'ru': 'Иран',
    'rw': 'Iran, Repubulika ya Kisilimu',
    'sc': 'Iran, Repùblica Islàmica de',
    'sd': 'Iran, Islamic Republic of',
    'si': 'ඉරාන ඉස්ලාමීය ජනරජය',
    'sk': 'Iránska islamská republika',
    'sl': 'Iran',
    'so': 'Iiraan',
    'sq': 'Iran, Republika Islamike',
    'sr': 'Иран, Исламска Република',
    'sv': 'Iran, islamiska republiken',
    'sw': 'Iran, Islamic Republic of',
    'ta': 'ஈரான், இஸ்லாமிக் குடியரசு',
    'te': 'ఇరాన్, ఇస్లామిక్ రిపబ్లిక్ ఆఫ్',
    'tg': 'Ҷумҳурии Исломии Эрон',
    'th': 'อิหร่าน, สาธารณรัฐอิสลาม',
    'ti': 'Iran, Islamic Republic of',
    'tk': 'Eýran yslam respublikasy',
    'tl': 'Iran, Republikang Islam ng',
    'tr': 'İran İslâm Cumhuriyeti',
    'tt': 'İран, İслам Җөмһүриәте',
    'ug': 'ئىران ئىسلام جۇمھۇرىيىتى',
    'uk': 'Іран',
    'ur': 'Iran, Islamic Republic of',
    'uz': 'Iran, Islamic Republic of',
    've': 'Iran, Islamic Republic of',
    'vi': 'Ba Tư, Cộng hoà Hồi giáo',
    'wa': 'Iran',
    'wo': 'Iraan, Republik Islaamik bu',
    'xh': 'Iran, Islamic Republic of',
    'yo': 'Iran, Islamic Republic of',
    'zh_CN': '伊朗',
    'zh_HK': '伊朗',
    'zh_TW': '伊朗伊斯蘭共和國',
    'zu': 'Iran, Islamic Republic of'
  },
);
