import '../country.dart';

const countryISL = Country(
  alpha2: 'IS',
  alpha3: 'ISL',
  continent: Continent.europe,
  countryCode: '354',
  currencyCode: 'ISK',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'IC',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 64.963051,
      longitude: -19.020835,
    ),
    maxCoordinate: Coordinate(
      latitude: 67.2466,
      longitude: -12.2388001,
    ),
    minCoordinate: Coordinate(
      latitude: 62.4819,
      longitude: -26.2572999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 67.2466,
        longitude: -12.2388001,
      ),
      southwest: Coordinate(
        latitude: 62.4819,
        longitude: -26.2572999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ISL',
  isoLongName: 'Iceland',
  isoShortName: 'Iceland',
  isoShortNameLowerCase: null,
  languagesOfficial: ['is'],
  languagesSpoken: ['is'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8, 9],
  nationalPrefix: '0',
  nationality: 'Icelander',
  number: '352',
  postalCode: true,
  postalCodeFormat: '\\d{3}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Northern Europe',
  unLocode: 'IS',
  unMember: true,
  unofficialNames: [
    'Iceland',
    'Island',
    'Islande',
    'Islandia',
    'アイスランド',
    'IJsland'
  ],
  vehicleRegistrationCode: 'IS',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 24,
    reduced: [11],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Iceland',
    'af': 'Ysland',
    'ak': 'Iceland',
    'am': 'ጐ፤ስሒን፥',
    'an': 'Iceland',
    'ar': 'آيسلندا',
    'as': 'আইচলেণ্ড',
    'ay': 'Iceland',
    'az': 'İslandiya',
    'ba': 'Iceland',
    'be': 'Ісландыя',
    'bg': 'Исландия',
    'bi': 'Iceland',
    'bn': 'আইসল্যান্ড',
    'bn_IN': 'আইসল্যান্ড',
    'br': 'Island',
    'bs': 'Island',
    'ca': 'Islàndia',
    'ce': 'Исланди',
    'ch': 'Iceland',
    'cs': 'Island',
    'cv': 'Исланди',
    'cy': 'Gwlad yr Iâ',
    'da': 'Island',
    'de': 'Island',
    'dv': 'އައިސްލަންޑަން',
    'dz': 'ཨའིསི་ལེནཌི།',
    'ee': 'Iceland',
    'el': 'Ισλανδία',
    'en': 'Iceland',
    'eo': 'Islando',
    'es': 'Islandia',
    'et': 'Island',
    'eu': 'Islandia',
    'fa': 'ایسلند',
    'ff': 'Islannda',
    'fi': 'Islanti',
    'fo': 'Ísland',
    'fr': 'Islande',
    'fy': 'Yslân',
    'ga': 'An Íoslainn',
    'gl': 'Islandia',
    'gn': 'Iceland',
    'gu': 'આઇસલેન્ડ',
    'gv': 'Yn Eeslynn',
    'ha': 'Iceland',
    'he': 'איסלנד',
    'hi': 'आइसलैण्ड',
    'hr': 'Island',
    'ht': 'Islann',
    'hu': 'Izland',
    'hy': 'Իսլանդիա',
    'ia': 'Islanda',
    'id': 'Islandia',
    'io': 'Islando',
    'is': 'Ísland',
    'it': 'Islanda',
    'iu': 'Iceland',
    'ja': 'アイスランド',
    'ka': 'ისლანდია',
    'ki': 'Iceland',
    'kk': 'Исландия',
    'kl': 'Iceland',
    'km': 'អ៊ីស្លង់',
    'kn': 'ಐಸ್‍ಲ್ಯಾಂಡ್',
    'ko': '아이슬란드',
    'ku': 'Îzlanda',
    'kv': 'Исландия',
    'kw': 'Island',
    'ky': 'Исландия',
    'lo': 'ອິດສະລັງ',
    'lt': 'Islandija',
    'lv': 'Islande',
    'mi': 'Tiorangi',
    'mk': 'Исланд',
    'ml': 'ഐസ്‌ലാന്‍ഡ്',
    'mn': 'Исланд',
    'mr': 'आइसलॅंड',
    'ms': 'Iceland',
    'mt': 'Islandja',
    'my': 'အိုက်စလန်နိုင်ငံ',
    'na': 'Aiterand',
    'nb': 'Island',
    'ne': 'आइसल्याण्ड',
    'nl': 'IJsland',
    'nn': 'Island',
    'nv': 'Tin Kéyah',
    'oc': 'Islàndia',
    'or': 'ଆଇସଲ୍ଯାଣ୍ଡ',
    'pa': 'ਆਈਸਲੈਂਡ',
    'pi': 'आइसलैंड',
    'pl': 'Islandia',
    'ps': 'آیسلینډ',
    'pt': 'Islândia',
    'pt_BR': 'Islândia',
    'ro': 'Islanda',
    'ru': 'Исландия',
    'rw': 'Isilande',
    'sc': 'Islanda',
    'sd': 'Iceland',
    'si': 'අයිස්ලන්තය',
    'sk': 'Island',
    'sl': 'Islandija',
    'so': 'Iislaand',
    'sq': 'Islandë',
    'sr': 'Исланд',
    'sv': 'Island',
    'sw': 'Iceland',
    'ta': 'ஐஸ்லாந்து',
    'te': 'ఐలాండ్',
    'tg': 'Исландия',
    'th': 'ไอซ์แลนด์',
    'ti': 'አይስላንድ',
    'tk': 'Islandiýa',
    'tl': 'Lupangyelo',
    'tr': 'İzlanda',
    'tt': 'İсланд',
    'ug': 'ئىسلاندىيە',
    'uk': 'Ісландія',
    'ur': 'آئس لینڈ',
    'uz': 'Islandiya',
    've': 'Iceland',
    'vi': 'Băng Đảo',
    'wa': 'Izlande',
    'wo': 'Islaand',
    'xh': 'Iceland',
    'yo': 'Íslándì',
    'zh_CN': '冰岛',
    'zh_HK': '冰島',
    'zh_TW': '冰島',
    'zu': 'I-Ayisilandi'
  },
);
