import '../country.dart';

const countryISR = Country(
  alpha2: 'IL',
  alpha3: 'ISR',
  continent: Continent.asia,
  countryCode: '972',
  currencyCode: 'ILS',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'IS',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 31.046051,
      longitude: 34.851612,
    ),
    maxCoordinate: Coordinate(
      latitude: 33.33280500000001,
      longitude: 35.896244,
    ),
    minCoordinate: Coordinate(
      latitude: 29.47969999999999,
      longitude: 34.2673871,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 33.33280500000001,
        longitude: 35.896244,
      ),
      southwest: Coordinate(
        latitude: 29.47969999999999,
        longitude: 34.2673871,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ISR',
  isoLongName: 'The State of Israel',
  isoShortName: 'Israel',
  isoShortNameLowerCase: null,
  languagesOfficial: ['he', 'ar'],
  languagesSpoken: ['he', 'ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8, 9],
  nationalPrefix: '0',
  nationality: 'Israeli',
  number: '376',
  postalCode: true,
  postalCodeFormat: '\\d{5}(?:\\d{2})?',
  region: Region.asia,
  startOfWeek: Week.sunday,
  subregion: 'Western Asia',
  unLocode: 'IL',
  unMember: true,
  unofficialNames: ['Israel', 'Israël', 'イスラエル'],
  vehicleRegistrationCode: 'IL',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: VatRates(
    standard: 17,
    reduced: [],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Israel',
    'af': 'Israel',
    'ak': 'Israel',
    'am': 'ጕስሲጔሔ',
    'an': 'Israel',
    'ar': 'إسرائيل',
    'as': 'ইজ্ৰাইল',
    'ay': 'Israel',
    'az': 'İsrail',
    'ba': 'Israel',
    'be': 'Ізраіль',
    'bg': 'Израел',
    'bi': 'Israel',
    'bn': 'ইজরাইল',
    'bn_IN': 'ইজরাইল',
    'br': 'Israel',
    'bs': 'Izrael',
    'ca': 'Israel',
    'ce': 'Израиль',
    'ch': 'Israel',
    'cs': 'Izrael',
    'cv': 'Израиль',
    'cy': 'Israel',
    'da': 'Israel',
    'de': 'Israel',
    'dv': 'އިސްރާއީލު',
    'dz': 'ཨིཛི་རེལ།',
    'ee': 'Israel',
    'el': 'Ισραήλ',
    'en': 'Israel',
    'eo': 'Israelo',
    'es': 'Israel',
    'et': 'Iisrael',
    'eu': 'Israel',
    'fa': 'اسراییل',
    'ff': 'Israel',
    'fi': 'Israel',
    'fo': 'Ísrael',
    'fr': 'Israël',
    'fy': 'Israel',
    'ga': 'Iosrael',
    'gl': 'Israel',
    'gn': 'Israel',
    'gu': 'ઇઝરાયેલ',
    'gv': 'Israel',
    'ha': 'Isra\'ila',
    'he': 'ישראל',
    'hi': 'इज़राइल',
    'hr': 'Izrael',
    'ht': 'Izrayèl',
    'hu': 'Izrael',
    'hy': 'Իսրայել',
    'ia': 'Israel',
    'id': 'Israel',
    'io': 'Israel',
    'is': 'Ísrael',
    'it': 'Israele',
    'iu': 'Israel',
    'ja': 'イスラエル',
    'ka': 'ისრაელი',
    'ki': 'Israel',
    'kk': 'Израиль',
    'kl': 'Israel',
    'km': 'អ៊ីស្រាអែល',
    'kn': 'ಇಸ್ರೇಲ್',
    'ko': '이스라엘',
    'ku': 'Îsraîl',
    'kv': 'Израиль',
    'kw': 'Ysrael',
    'ky': 'Израиль',
    'lo': 'Israel',
    'lt': 'Izraelis',
    'lv': 'Izraēla',
    'mi': 'Iharaira',
    'mk': 'Израел',
    'ml': 'ഇസ്രായേല്‍',
    'mn': 'Израйл',
    'mr': 'इस्रायल',
    'ms': 'Israel',
    'mt': 'Iżrael',
    'my': 'အစ္စရေးနိုင်ငံ',
    'na': 'Iteraer',
    'nb': 'Israel',
    'ne': 'इज्रायल',
    'nl': 'Israël',
    'nn': 'Israel',
    'nv': 'Ízrel Bikéyah',
    'oc': 'Israel',
    'or': 'ଇଜ୍ରାଇଲ',
    'pa': 'ਇਜ਼ਰਾਈਲ',
    'pi': 'इस्रैल',
    'pl': 'Izrael',
    'ps': 'اسرائیل',
    'pt': 'Israel',
    'pt_BR': 'Israel',
    'ro': 'Israel',
    'ru': 'Израиль',
    'rw': 'Isirayeli',
    'sc': 'Israele',
    'sd': 'اسرائيل جي رياست',
    'si': 'ඊශ්‍රායලය',
    'sk': 'Izrael',
    'sl': 'Izrael',
    'so': 'Israa\'iil',
    'sq': 'Izrael',
    'sr': 'Израел',
    'sv': 'Israel',
    'sw': 'Israel',
    'ta': 'இஸ்ரேல்',
    'te': 'ఇస్రాయిల్',
    'tg': 'Исроил',
    'th': 'อิสราเอล',
    'ti': 'እስራኤል',
    'tk': 'Izraýyl',
    'tl': 'Israel',
    'tr': 'İsrail',
    'tt': 'İсраел',
    'ug': 'ئىسرائىلىيە',
    'uk': 'Ізраїль',
    'ur': 'اسرائیل',
    'uz': 'Isroil',
    've': 'Israel',
    'vi': 'Do Thái',
    'wa': 'Israyel',
    'wo': 'Israayil',
    'xh': 'Sirayeli',
    'yo': 'Ísráẹ́lì',
    'zh_CN': '以色列',
    'zh_HK': '以色列',
    'zh_TW': '以色列',
    'zu': 'Isreyili'
  },
);
