import '../country.dart';

const countryJOR = Country(
  alpha2: 'JO',
  alpha3: 'JOR',
  continent: Continent.asia,
  countryCode: '962',
  currencyCode: 'JOD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'JO',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 30.585164,
      longitude: 36.238414,
    ),
    maxCoordinate: Coordinate(
      latitude: 33.374735,
      longitude: 39.301154,
    ),
    minCoordinate: Coordinate(
      latitude: 29.1850361,
      longitude: 34.9441001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 33.374735,
        longitude: 39.301154,
      ),
      southwest: Coordinate(
        latitude: 29.1850361,
        longitude: 34.9441001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'JOR',
  isoLongName: 'The Hashemite Kingdom of Jordan',
  isoShortName: 'Jordan',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar'],
  languagesSpoken: ['ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9],
  nationalPrefix: '0',
  nationality: 'Jordanian',
  number: '400',
  postalCode: true,
  postalCodeFormat: r'\d{5}',
  region: Region.asia,
  startOfWeek: Week.sunday,
  subregion: 'Western Asia',
  unLocode: 'JO',
  unMember: true,
  unofficialNames: [
    'Jordan',
    'الأردن',
    'Jordanien',
    'Jordanie',
    'Jordania',
    'ヨルダン',
    'Jordanië'
  ],
  vehicleRegistrationCode: 'JOR',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Jordan",
    "af": "Jordanië",
    "ak": "Jordan",
    "am": "ጆሴ፣ን",
    "an": "Jordan",
    "ar": "الأردن",
    "as": "জৰ্ডান",
    "ay": "Jordan",
    "az": "İordaniya",
    "ba": "Jordan",
    "be": "Іарданія",
    "bg": "Йордания",
    "bi": "Jordan",
    "bn": "জর্ডান",
    "bn_IN": "জর্ডান",
    "br": "Jordania",
    "bs": "Jordan",
    "ca": "Jordània",
    "ce": "Урдан",
    "ch": "Jordan",
    "cs": "Jordánsko",
    "cv": "Урдан",
    "cy": "Gwlad Yr Iorddonen",
    "da": "Jordan",
    "de": "Jordanien",
    "dv": "އުރުދުން",
    "dz": "ཇོར་ཌན།",
    "ee": "Jordan",
    "el": "Ιορδανία",
    "en": "Jordan",
    "eo": "Jordanio",
    "es": "Jordania",
    "et": "Jordaania",
    "eu": "Jordania",
    "fa": "اردن",
    "ff": "Jordan",
    "fi": "Jordania",
    "fo": "Jordan",
    "fr": "Jordanie",
    "fy": "Jordaanje",
    "ga": "An Iordáin",
    "gl": "Xordania",
    "gn": "Jordan",
    "gu": "જોર્ડન",
    "gv": "Yn Jordaan",
    "ha": "Jordan",
    "he": "ירדן",
    "hi": "जॉर्डन",
    "hr": "Jordan",
    "ht": "Jòdani",
    "hu": "Jordánia",
    "hy": "Հորդանան",
    "ia": "Jordania",
    "id": "Yordania",
    "io": "Jordania",
    "is": "Jórdanía",
    "it": "Giordania",
    "iu": "Jordan",
    "ja": "ヨルダン",
    "ka": "იორდანია",
    "ki": "Jordan",
    "kk": "Иордания",
    "kl": "Jordan",
    "km": "ហ្ស៊កដង់",
    "kn": "ಜೋರ್ಡಾನ್",
    "ko": "요르단",
    "ku": "Urdin",
    "kv": "Иордания",
    "kw": "Jordan",
    "ky": "Иордания",
    "lo": "Jordan",
    "lt": "Jordanija",
    "lv": "Jordānija",
    "mi": "Jordan",
    "mk": "Џордан",
    "ml": "ജോര്‍ഡാന്‍",
    "mn": "Ёрдан",
    "mr": "जॉर्डन",
    "ms": "Jordan",
    "mt": "Ġordan",
    "my": "ဂျော်ဒန်နိုင်ငံ",
    "na": "Djordan",
    "nb": "Jordan",
    "ne": "जोर्डन",
    "nl": "Jordanië",
    "nn": "Jordan",
    "nv": "Jordan",
    "oc": "Jordania",
    "or": "ଜୋର୍ଡାନ",
    "pa": "ਜਾਰਡਨ",
    "pi": "जार्डन",
    "pl": "Jordania",
    "ps": "اردن",
    "pt": "Jordânia",
    "pt_BR": "Jordânia",
    "ro": "Iordania",
    "ru": "Иордания",
    "rw": "Yorudani",
    "sc": "Giordània",
    "sd": "اردن",
    "si": "ජෝර්දානය",
    "sk": "Jordánsko",
    "sl": "Jordanija",
    "so": "Urdun",
    "sq": "Jordani",
    "sr": "Јордан",
    "sv": "Jordanien",
    "sw": "Jordan",
    "ta": "ஜோர்டான்",
    "te": "జోర్డాన్",
    "tg": "Ҷордон",
    "th": "จอร์แดน",
    "ti": "ጆርዳን",
    "tk": "Iordaniýa",
    "tl": "Jordan",
    "tr": "Ürdün",
    "tt": "Жордан",
    "ug": "ئىيوردانىيە",
    "uk": "Йорданія",
    "ur": "اردن",
    "uz": "Iordaniya",
    "ve": "Jordan",
    "vi": "Gi-oa-đanh",
    "wa": "Djordaneye",
    "wo": "Jordaani",
    "xh": "Jordan",
    "yo": "Jọ́rdánì",
    "zh_CN": "约旦",
    "zh_HK": "約旦",
    "zh_TW": "約旦",
    "zu": "Jordan"
  },
);
