import '../country.dart';

const countryKAZ = Country(
  alpha2: 'KZ',
  alpha3: 'KAZ',
  continent: Continent.asia,
  countryCode: '7',
  currencyCode: 'KZT',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'KZ',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 48.019573,
      longitude: 66.923684,
    ),
    maxCoordinate: Coordinate(
      latitude: 55.4419839,
      longitude: 87.315415,
    ),
    minCoordinate: Coordinate(
      latitude: 40.5685841,
      longitude: 46.493672,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 55.4419839,
        longitude: 87.315415,
      ),
      southwest: Coordinate(
        latitude: 40.5685841,
        longitude: 46.493672,
      ),
    ),
  ),
  internationalPrefix: '810',
  ioc: 'KAZ',
  isoLongName: 'The Republic of Kazakhstan',
  isoShortName: 'Kazakhstan',
  isoShortNameLowerCase: null,
  languagesOfficial: ['kk', 'ru'],
  languagesSpoken: ['kk', 'ru'],
  nationalDestinationCodeLengths: [3],
  nationalNumberLengths: [10],
  nationalPrefix: '8',
  nationality: 'Kazakhstani',
  number: '398',
  postalCode: true,
  postalCodeFormat: '\\d{6}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Central Asia',
  unLocode: 'KZ',
  unMember: true,
  unofficialNames: [
    'Kazakhstan',
    'Kasachstan',
    'Kazajistán',
    'カザフスタン',
    'Kazachstan'
  ],
  vehicleRegistrationCode: 'KZ',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Kazakhstan',
    'af': 'Kazakstan',
    'ak': 'Kazakhstan',
    'am': 'ካዛክስታን',
    'an': 'Kazakhstan',
    'ar': 'كازاخستان',
    'as': 'কাজাখিস্তান',
    'ay': 'Kazakhstan',
    'az': 'Qazaxstan',
    'ba': 'Kazakhstan',
    'be': 'Казахстан',
    'bg': 'Казахстан',
    'bi': 'Kazakhstan',
    'bn': 'কাজাখস্তান',
    'bn_IN': 'কাজাখস্তান',
    'br': 'Kazakstan',
    'bs': 'Kazahstan',
    'ca': 'Kazakhstan',
    'ce': 'Кхазакхстан',
    'ch': 'Kazakhstan',
    'cs': 'Kazachstán',
    'cv': 'Кхазакхстан',
    'cy': 'Kazakhstan',
    'da': 'Kasakhstan',
    'de': 'Kasachstan',
    'dv': 'ކަޒަކިސްތާން',
    'dz': 'ཀ་ཛཀསི་ཏཱན།',
    'ee': 'Kazakhstan',
    'el': 'Καζακστάν',
    'en': 'Kazakhstan',
    'eo': 'Kazaĥio',
    'es': 'Kazajistán',
    'et': 'Kasahstan',
    'eu': 'Kazakhstan',
    'fa': 'قزاقستان',
    'ff': 'Kazakhstan',
    'fi': 'Kazakstan',
    'fo': 'Kasakstan',
    'fr': 'Kazakhstan',
    'fy': 'Kazakstan',
    'ga': 'An Chasacstáin',
    'gl': 'Kazakhstán',
    'gn': 'Kazakhstan',
    'gu': 'કઝાખસ્તાન',
    'gv': 'Yn Chassaghstaan',
    'ha': 'Kazakystan',
    'he': 'קזחסטן',
    'hi': 'कज़ाख़िस्तान',
    'hr': 'Kazahstan',
    'ht': 'Kazakstan',
    'hu': 'Kazahsztán',
    'hy': 'Ղազախստան',
    'ia': 'Kazakhstan',
    'id': 'Kazakhstan',
    'io': 'Kazakstan',
    'is': 'Kasakstan',
    'it': 'Kazakistan',
    'iu': 'ᑲᓴᒃᖢᓇ ᓄᓇ',
    'ja': 'カザフスタン',
    'ka': 'ყაზახეთი',
    'ki': 'Kazakhstan',
    'kk': 'Қазақстан',
    'kl': 'Kazakhstan',
    'km': 'កាហ្សាក់ស្តង់',
    'kn': 'ಕಝಕಸ್ತಾನ್',
    'ko': '카자흐스탄',
    'ku': 'Kazaxstan',
    'kv': 'Казахстан',
    'kw': 'Pow Kazagh',
    'ky': 'Казакстан',
    'lo': 'Kazakhstan',
    'lt': 'Kazachstanas',
    'lv': 'Kazahstāna',
    'mi': 'Katatānga',
    'mk': 'Казакстан',
    'ml': 'കസാഖിസ്താന്‍',
    'mn': 'Казакстан',
    'mr': 'कझाकिस्तान',
    'ms': 'Kazakhstan',
    'mt': 'Każakistan',
    'my': 'ကာဇက်စတန်နိုင်ငံ',
    'na': 'Kadaketan',
    'nb': 'Kasakhstan',
    'ne': 'काजखास्तान',
    'nl': 'Kazachstan',
    'nn': 'Kasakhstan',
    'nv': 'Bilį́į́ʼ Ńdeiltihii Dineʼé Bikéyah',
    'oc': 'Cazacstan',
    'or': 'କାଜାଖସ୍ତାନ',
    'pa': 'ਕਜ਼ਾਕਸਤਾਨ',
    'pi': 'कजाकस्थान',
    'pl': 'Kazachstan',
    'ps': 'قزاقستان',
    'pt': 'Cazaquistão',
    'pt_BR': 'Cazaquistão',
    'ro': 'Kazakhstan',
    'ru': 'Казахстан',
    'rw': 'Kazakisitani',
    'sc': 'Kazakistan',
    'sd': 'قازڪستان',
    'si': 'කසකස්තානය',
    'sk': 'Kazachstan',
    'sl': 'Kazahstan',
    'so': 'Kasaakhistaan',
    'sq': 'Kazakistan',
    'sr': 'Казахстан',
    'sv': 'Kazakstan',
    'sw': 'Kazakhstan',
    'ta': 'கசகிஸ்தான்',
    'te': 'కఝకిస్తాన్',
    'tg': 'Қазоқистон',
    'th': 'คาซัคสถาน',
    'ti': 'Kazakhstan',
    'tk': 'Gazagystan',
    'tl': 'Kazakhstan',
    'tr': 'Kazakistan',
    'tt': 'Казакстан',
    'ug': 'قازاقىستان',
    'uk': 'Казахстан',
    'ur': 'قازقستان',
    'uz': 'Qozogʻiston',
    've': 'Kazakhstan',
    'vi': 'Kha-xa-kh-x-thanh',
    'wa': 'Kazaxhtan',
    'wo': 'Kaasakestaan',
    'xh': 'Kazakhstan',
    'yo': 'Kàsàkstán',
    'zh_CN': '哈萨克斯坦',
    'zh_HK': '哈薩克',
    'zh_TW': '哈薩克',
    'zu': 'Kazakhstan'
  },
);
