import '../country.dart';

const countryKGZ = Country(
  alpha2: 'KG',
  alpha3: 'KGZ',
  continent: Continent.asia,
  countryCode: '996',
  currencyCode: 'KGS',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'KG',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 41.20438,
      longitude: 74.766098,
    ),
    maxCoordinate: Coordinate(
      latitude: 43.2653569,
      longitude: 80.2281514,
    ),
    minCoordinate: Coordinate(
      latitude: 39.180254,
      longitude: 69.250998,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 43.2653569,
        longitude: 80.2281514,
      ),
      southwest: Coordinate(
        latitude: 39.180254,
        longitude: 69.250998,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'KGZ',
  isoLongName: 'The Kyrgyz Republic',
  isoShortName: 'Kyrgyzstan',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ky', 'ru'],
  languagesSpoken: ['ky', 'ru'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '0',
  nationality: 'Kirghiz',
  number: '417',
  postalCode: true,
  postalCodeFormat: '\\d{6}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Central Asia',
  unLocode: 'KG',
  unMember: true,
  unofficialNames: [
    'Kyrgyzstan',
    'Kirgisistan',
    'Kirghizistan',
    'Kirguizistán',
    'キルギス',
    'Kirgizië',
    'Kyrgzstan'
  ],
  vehicleRegistrationCode: 'KG',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Kyrgyzstan',
    'af': 'Kirgisië',
    'ak': 'Kyrgyzstan',
    'am': 'ኪርጊዝስታን',
    'an': 'Kyrgyzstan',
    'ar': 'قيرغزستان',
    'as': 'কিৰ্গিজস্তান',
    'ay': 'Kyrgyzstan',
    'az': 'Qırğızıstan',
    'ba': 'Kyrgyzstan',
    'be': 'Кыргызстан',
    'bg': 'Киргизстан',
    'bi': 'Kyrgyzstan',
    'bn': 'কির্গিজস্তান',
    'bn_IN': 'কির্গিজস্তান',
    'br': 'Kirgizstan',
    'bs': 'Kirgistan',
    'ca': 'Kirguizistan',
    'ce': 'Киргизи',
    'ch': 'Kyrgyzstan',
    'cs': 'Kyrgyzstán',
    'cv': 'Киргизи',
    'cy': 'Kyrgyzstan',
    'da': 'Kirgisistan',
    'de': 'Kirgisistan',
    'dv': 'ކިރިގިސްތާން',
    'dz': 'ཀར་གིཛི་ཏཱན།',
    'ee': 'Kyrgyzstan',
    'el': 'Κιργιζία',
    'en': 'Kyrgyzstan',
    'eo': 'Kirgizio',
    'es': 'Kirguistán',
    'et': 'Kõrgõzstan',
    'eu': 'Kirgizistan',
    'fa': 'قرقیزستان',
    'ff': 'Kyrgyzstan',
    'fi': 'Kirgisia',
    'fo': 'Kirgisia',
    'fr': 'Kirghizistan',
    'fy': 'Kirgyzje',
    'ga': 'An Chirgeastáin',
    'gl': 'Quirgizistán',
    'gn': 'Kyrgyzstan',
    'gu': 'કિર્ગિસ્તાન',
    'gv': 'Yn Chyrgistaan',
    'ha': 'Kyrgystan',
    'he': 'קירגיזסטן',
    'hi': 'किर्गिज़स्तान',
    'hr': 'Kirgistan',
    'ht': 'Kirgistan',
    'hu': 'Kirgizisztán',
    'hy': 'Կիրգիզստան',
    'ia': 'Kirghizistan',
    'id': 'Kirgizstan',
    'io': 'Kirgizistan',
    'is': 'Kirgisistan',
    'it': 'Kirghizistan',
    'iu': 'Kyrgyzstan',
    'ja': 'キルギス共和国',
    'ka': 'ყირგიზეთი',
    'ki': 'Kyrgyzstan',
    'kk': 'Қырғызстан',
    'kl': 'Kyrgyzstan',
    'km': 'គៀរហ្គីស្តង់',
    'kn': 'ಕಿರ್ಗಿಝ್‍ಸ್ತಾನ್',
    'ko': '키르기스스탄',
    'ku': 'Kirgîsistan',
    'kv': 'Кыргызстан',
    'kw': 'Pow Kyrgys',
    'ky': 'Кыргызстан',
    'lo': 'Kyrgyzstan',
    'lt': 'Kirgizija',
    'lv': 'Kirgizstāna',
    'mi': 'Kyrgyzstan',
    'mk': 'Киргистан',
    'ml': 'കിര്‍ഗിസ്താന്‍',
    'mn': 'Киргиз',
    'mr': 'किर्गिझस्तान',
    'ms': 'Kyrgyzstan',
    'mt': 'Kirgistan',
    'my': 'ကာဂျစ္စတန်နိုင်ငံ',
    'na': 'Kirgitan',
    'nb': 'Kirgisistan',
    'ne': 'किर्जिस्तान',
    'nl': 'Kirgizië',
    'nn': 'Kirgisistan',
    'nv': 'Kyrgyzstan',
    'oc': 'Kirguizstan',
    'or': 'କିର୍ଗିଜସ୍ତାନ',
    'pa': 'ਕਿਰਗਸਤਾਨ',
    'pi': 'किरगिस्थान',
    'pl': 'Kirgistan',
    'ps': 'قرغزستان',
    'pt': 'Quirguistão',
    'pt_BR': 'Quirguistão',
    'ro': 'Kârgâzstan',
    'ru': 'Киргизия',
    'rw': 'Kirigizasitani',
    'sc': 'Kirghìzistan',
    'sd': 'ڪِرگزِستانُ',
    'si': 'කිර්ගිස්තානය',
    'sk': 'Kirgizsko',
    'sl': 'Kirgizistan',
    'so': 'Qargistan',
    'sq': 'Kirgistan',
    'sr': 'Киргистан',
    'sv': 'Kirgizistan',
    'sw': 'Kyrgyzstan',
    'ta': 'கிரைகிசுத்தான்',
    'te': 'కిర్గిఝస్తాన',
    'tg': 'Қирғизистон',
    'th': 'คีร์กีซสถาน',
    'ti': 'Kyrgyzstan',
    'tk': 'Gyrgyzstan',
    'tl': 'Kyrgyzstan',
    'tr': 'Kırgızistan',
    'tt': 'Кыргызстан',
    'ug': 'قىرغىزىستان',
    'uk': 'Киргизстан',
    'ur': 'کرغیزستان',
    'uz': 'Qirgʻiziston',
    've': 'Kyrgyzstan',
    'vi': 'Khư-rơ-gư-xtanh',
    'wa': 'Kirguiztan',
    'wo': 'Kirgistaan',
    'xh': 'Kyrgyzstan',
    'yo': 'Kirgistani',
    'zh_CN': '吉尔吉斯坦',
    'zh_HK': '吉爾吉斯',
    'zh_TW': '吉爾吉斯',
    'zu': 'Kyrgyzstan'
  },
);
