import '../country.dart';

const countryKNA = Country(
  alpha2: 'KN',
  alpha3: 'KNA',
  continent: Continent.northAmerica,
  countryCode: '1',
  currencyCode: 'XCD',
  distanceUnit: DistanceUnit.miles,
  gec: 'SC',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 17.357822,
      longitude: -62.782998,
    ),
    maxCoordinate: Coordinate(
      latitude: 17.4205891,
      longitude: -62.52369989999999,
    ),
    minCoordinate: Coordinate(
      latitude: 17.07861,
      longitude: -62.86949999999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 17.4205891,
        longitude: -62.52369989999999,
      ),
      southwest: Coordinate(
        latitude: 17.07861,
        longitude: -62.86949999999999,
      ),
    ),
  ),
  internationalPrefix: '011',
  ioc: 'SKN',
  isoLongName: 'Saint Kitts and Nevis',
  isoShortName: 'Saint Kitts and Nevis',
  isoShortNameLowerCase: null,
  languagesOfficial: ['en'],
  languagesSpoken: ['en'],
  nationalDestinationCodeLengths: [3],
  nationalNumberLengths: [10],
  nationalPrefix: '1',
  nationality: 'Kittian and Nevisian',
  number: '659',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.americas,
  startOfWeek: Week.monday,
  subregion: 'Caribbean',
  unLocode: 'KN',
  unMember: true,
  unofficialNames: [
    'Saint Kitts and Nevis',
    'Föderation St. Kitts und Nevis',
    'Saint Kitts et Nevis',
    'Saint Kitts y Nevis',
    'セントクリストファー・ネイビス',
    'Saint Kitts en Nevis',
    'St. Kitts and Nevis',
    'St Kitts and Nevis'
  ],
  vehicleRegistrationCode: 'KAN',
  worldRegion: WorldRegion.amer,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: '1869',
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Saint Kitts and Nevis',
    'af': 'St. Kitts en Nevis',
    'ak': 'Saint Kitts and Nevis',
    'am': 'ሰይንት ኪትስና ኒቨስ',
    'an': 'Saint Kitts and Nevis',
    'ar': 'سانت كيتس و نيفس',
    'as': 'চেন্ট কিট্‌স আৰু নেভিচ',
    'ay': 'Saint Kitts and Nevis',
    'az': 'Saint Kitts and Nevis',
    'ba': 'Saint Kitts and Nevis',
    'be': 'Сент-Кітс і Невіс',
    'bg': 'Свети Китс и Невис',
    'bi': 'Saint Kitts and Nevis',
    'bn': 'সেন্ট কিটস ও নেভিস',
    'bn_IN': 'সেন্ট কিটস ও নেভিস',
    'br': 'S. Kitts ha Nevis',
    'bs': 'Saint Kitts i Nevis',
    'ca': 'Saint Christopher i Nevis',
    'ce': 'Сент-Китс а Невис',
    'ch': 'Saint Kitts and Nevis',
    'cs': 'Svatý Kryštof a Nevis',
    'cv': 'Сент-Китс а Невис',
    'cy': 'Saint Kitts a Nevis',
    'da': 'Sankt Kitts og Nevis',
    'de': 'St. Kitts und Nevis',
    'dv': 'ސަންތި ކިޓަސް އަދި ނޭވީސް',
    'dz': 'སེནཊི་ ཀིཊིསི་ ཨེནཌི་ ནེ་བིསི།',
    'ee': 'Saint Kitts and Nevis',
    'el': 'Άγιος Χριστόφορος και Νέβις',
    'en': 'Saint Kitts and Nevis',
    'eo': 'Sankta-Kito kaj Neviso',
    'es': 'San Cristóbal y Nieves',
    'et': 'Saint Kitts ja Nevis',
    'eu': 'Saint Kitts eta Nevis',
    'fa': 'سن کیتس و نویس',
    'ff': 'Saint Kitts and Nevis',
    'fi': 'Saint Kitts ja Nevis',
    'fo': 'Saint Kitts og Nevis',
    'fr': 'Saint-Christophe-et-Niévès',
    'fy': 'Sint Kits en Nevis',
    'ga': 'Saint Kitts agus Nevis',
    'gl': 'San Cristobo e Nevis',
    'gn': 'Saint Kitts and Nevis',
    'gu': 'સેન્ટ કીટ્સ અને નેવિસ',
    'gv': 'Noo Kitts as Nevis',
    'ha': 'Saint Kitts and Nevis',
    'he': 'סנט קיטס ונוויס',
    'hi': 'सन्त किट्स और नेविस',
    'hr': 'Sveti Kristofor i Nevis',
    'ht': 'Saint Kitts and Nevis',
    'hu': 'Saint Kitts és Nevis',
    'hy': 'Սենտ Կիտս-Նեվիս',
    'ia': 'Sancte Christophoro e Nevis',
    'id': 'Saint Kitts dan Nevis',
    'io': 'Santa Kitts e Nevis',
    'is': 'Sankti Kitts og Neviseyjar',
    'it': 'Saint Kitts e Nevis',
    'iu': 'Saint Kitts and Nevis',
    'ja': 'セントクリストファー・ネーヴィス',
    'ka': 'სენტ-კიტსი და ნევისი',
    'ki': 'Saint Kitts and Nevis',
    'kk': 'Сент-Китс және Невис',
    'kl': 'Saint Kitts and Nevis',
    'km': 'សង់ឃីត និង នេវីស',
    'kn': 'ಸೇಂಟ್ ಕಿಟ್ಸ್ ಮತ್ತು ನೇವಿಸ್',
    'ko': '세인트키츠 네비스',
    'ku': 'Saint Kitts û Nevis',
    'kv': 'Saint Kitts and Nevis',
    'kw': 'Sen Kitts ha Nevis',
    'ky': 'Сент-Китс жана Невис',
    'lo': 'Saint Kitts and Nevis',
    'lt': 'Sent Kitsas ir Nevis',
    'lv': 'Sentkitsa un Nevisa',
    'mi': 'Saint Kitts and Nevis',
    'mk': 'Св. Китс и Невис',
    'ml': 'സെയിന്റ് കിറ്റ്സും നെവിസും',
    'mn': 'Сент-Китс ба Невис',
    'mr': 'सेंट किटस् आणी नेव्हिस',
    'ms': 'Saint Kitts dan Nevis',
    'mt': 'Saint Kitts and Nevis',
    'my': 'စိန့်ကစ်နှင့် နီးဗစ်နိုင်ငံ',
    'na': 'Saint Kitts and Nevis',
    'nb': 'Saint Kitts og Nevis',
    'ne': 'सेन्ट किट्स र नेभिस',
    'nl': 'Saint Kitts en Nevis',
    'nn': 'St. Kitts og Nevis; Saint Kitts og Nevis',
    'nv': 'Saint Kitts and Nevis',
    'oc': 'St. Kitts e Nevis',
    'or': 'ସେଣ୍ଟ କିଟ୍ସ ଏବଂ ନେଭିସ',
    'pa': 'ਸੇਂਟ ਕਿਟਸ ਅਤੇ ਨੇਵੀਸ',
    'pi': 'सेंट किट्',
    'pl': 'Saint Kitts i Nevis',
    'ps': 'Saint Kitts and Nevis',
    'pt': 'São Cristóvão e Nevis',
    'pt_BR': 'São Cristóvão e Névis',
    'ro': 'Saint Kitts și Nevis',
    'ru': 'Сент-Китс и Невис',
    'rw': 'Mutagatifu Kitsi na Nevisi',
    'sc': 'Saint Kitts e Nevis',
    'sd': 'Saint Kitts and Nevis',
    'si': 'ශාන්ත කිට්ස් හා නෙවිස්',
    'sk': 'Svätý Krištof a Nevis',
    'sl': 'Saint Kitts in Nevis',
    'so': 'Saint Kitts and Nevis',
    'sq': 'Shën Kits dhe Nevis',
    'sr': 'Свети Китс и Невис',
    'sv': 'Sankt Kitts och Nevis',
    'sw': 'Saint Kitts and Nevis',
    'ta': 'செயின்ட் கிட்ஸ் மற்றும் நிவிஸ்',
    'te': 'సైంట్ కిట్స్ మరియు నెవిస్',
    'tg': 'Сент-Китс ва Невис',
    'th': 'เซนต์คิตส์และเนวิส',
    'ti': 'Saint Kitts and Nevis',
    'tk': 'Sent-Kits we Newis',
    'tl': 'Saint Kitts at Nevis',
    'tr': 'Saint Kitts ve Nevis',
    'tt': 'Saint Kitts and Nevis',
    'ug': 'ساينىت-كىرىستوفېر ۋە نېۋىس',
    'uk': 'Сент-Кіттс і Невіс',
    'ur': 'سینٹ کیٹز و ناویس',
    'uz': 'Saint Kitts va Nevis',
    've': 'Saint Kitts and Nevis',
    'vi': 'Xan-kít và Nê-vi',
    'wa': 'St Kitts & Nevis',
    'wo': 'Saint Kitts and Nevis',
    'xh': 'Saint Kitts and Nevis',
    'yo': 'Saint Kitts àti Nevis',
    'zh_CN': '圣基茨和尼维斯',
    'zh_HK': '聖基茨和尼維斯聯邦',
    'zh_TW': '聖克里斯多福及尼維斯',
    'zu': 'Saint Kitts and Nevis'
  },
);
