import '../country.dart';

const countryLBN = Country(
  alpha2: 'LB',
  alpha3: 'LBN',
  continent: Continent.asia,
  countryCode: '961',
  currencyCode: 'LBP',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'LE',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 33.854721,
      longitude: 35.862285,
    ),
    maxCoordinate: Coordinate(
      latitude: 34.69209,
      longitude: 36.62372,
    ),
    minCoordinate: Coordinate(
      latitude: 33.0550256,
      longitude: 35.0711001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 34.69209,
        longitude: 36.62372,
      ),
      southwest: Coordinate(
        latitude: 33.0550256,
        longitude: 35.0711001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'LBN',
  isoLongName: 'The Lebanese Republic',
  isoShortName: 'Lebanon',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar', 'fr'],
  languagesSpoken: ['ar', 'fr'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '0',
  nationality: 'Lebanese',
  number: '422',
  postalCode: true,
  postalCodeFormat: r'(?:\d{4})(?: ?(?:\d{4}))?',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Western Asia',
  unLocode: 'LB',
  unMember: true,
  unofficialNames: ['Lebanon', 'لبنان', 'Libanon', 'Liban', 'Líbano', 'レバノン'],
  vehicleRegistrationCode: 'RL',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Lebanon",
    "af": "Libanon",
    "ak": "Lebanon",
    "am": "ሑባኖስ",
    "an": "Lebanon",
    "ar": "لبنان",
    "as": "লেবানন",
    "ay": "Lebanon",
    "az": "Livan",
    "ba": "Lebanon",
    "be": "Ліван",
    "bg": "Лебанон",
    "bi": "Lebanon",
    "bn": "লেবানন",
    "bn_IN": "লেবানন",
    "br": "Liban",
    "bs": "Liban",
    "ca": "Líban",
    "ce": "Ливан",
    "ch": "Lebanon",
    "cs": "Libanon",
    "cv": "Ливан",
    "cy": "Lebanon",
    "da": "Libanon",
    "de": "Libanon",
    "dv": "ލުބުނާން",
    "dz": "ལེ་བ་ནཱོན།",
    "ee": "Lebanon",
    "el": "Λίβανος",
    "en": "Lebanon",
    "eo": "Libano",
    "es": "Líbano",
    "et": "Liibanon",
    "eu": "Libano",
    "fa": "لبنان",
    "ff": "Lebanon",
    "fi": "Libanon",
    "fo": "Libanon",
    "fr": "Liban",
    "fy": "Libanon",
    "ga": "An Liobáin",
    "gl": "Líbano",
    "gn": "Lebanon",
    "gu": "લેબેનોન",
    "gv": "Yn Livaan",
    "ha": "Lebanon",
    "he": "לבנון",
    "hi": "लेबनान",
    "hr": "Libanon",
    "ht": "Liban",
    "hu": "Libanon",
    "hy": "Լիբանան",
    "ia": "Libano",
    "id": "Lebanon",
    "io": "Libano",
    "is": "Líbanon",
    "it": "Libano",
    "iu": "Lebanon",
    "ja": "レバノン",
    "ka": "ლიბანი",
    "ki": "Lebanon",
    "kk": "Ливан",
    "kl": "Lebanon",
    "km": "លីបង់",
    "kn": "ಲೆಬನನ್",
    "ko": "레바논",
    "ku": "Lubnan",
    "kv": "Ливан",
    "kw": "Lebnon",
    "ky": "Ливан",
    "lo": "Lebanon",
    "lt": "Libanas",
    "lv": "Libāna",
    "mi": "Lebanon",
    "mk": "Либан",
    "ml": "ലെബനോണ്‍",
    "mn": "Либони",
    "mr": "लेबेनॉन",
    "ms": "Lubnan",
    "mt": "Libanu",
    "my": "လက်ဘနွန်နိုင်ငံ",
    "na": "Ribanon",
    "nb": "Libanon",
    "ne": "लेबनान",
    "nl": "Libanon",
    "nn": "Libanon",
    "nv": "Lebanon",
    "oc": "Liban",
    "or": "ଲେବାନୋନ",
    "pa": "ਲੀਬਨਾਨ",
    "pi": "लेबनान",
    "pl": "Liban",
    "ps": "لبنان",
    "pt": "Líbano",
    "pt_BR": "Líbano",
    "ro": "Liban",
    "ru": "Ливан",
    "rw": "Libani",
    "sc": "Lìbanu",
    "sd": "Lebanon",
    "si": "ලෙබනන",
    "sk": "Libanon",
    "sl": "Libanon",
    "so": "Lubnaan",
    "sq": "Liban",
    "sr": "Либан",
    "sv": "Libanon",
    "sw": "Lebanon",
    "ta": "லெபனான்",
    "te": "లెబనాన్",
    "tg": "Лубнон",
    "th": "เลบานอน",
    "ti": "ሊባኖስ",
    "tk": "Liwan",
    "tl": "Lebanon",
    "tr": "Lübnan",
    "tt": "Лебанон",
    "ug": "لىۋان",
    "uk": "Ліван",
    "ur": "لبنان",
    "uz": "Livan",
    "ve": "Lebanon",
    "vi": "Le-ba-non",
    "wa": "Liban",
    "wo": "Libãa",
    "xh": "Lebanon",
    "yo": "Lẹ́bánọ́nì",
    "zh_CN": "黎巴嫩",
    "zh_HK": "黎巴嫩",
    "zh_TW": "黎巴嫩",
    "zu": "Lebanon"
  },
);
