import '../country.dart';

const countryLBY = Country(
  alpha2: 'LY',
  alpha3: 'LBY',
  continent: Continent.africa,
  countryCode: '218',
  currencyCode: 'LYD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'LY',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 26.3351,
      longitude: 17.228331,
    ),
    maxCoordinate: Coordinate(
      latitude: 33.2203,
      longitude: 25.2686,
    ),
    minCoordinate: Coordinate(
      latitude: 19.5,
      longitude: 9.391466,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 33.2203,
        longitude: 25.2686,
      ),
      southwest: Coordinate(
        latitude: 19.5,
        longitude: 9.391466,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'LBA',
  isoLongName: 'The State of Libya',
  isoShortName: 'Libya',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar'],
  languagesSpoken: ['ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9],
  nationalPrefix: '0',
  nationality: 'Libyan',
  number: '434',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.sunday,
  subregion: 'Northern Africa',
  unLocode: 'LY',
  unMember: true,
  unofficialNames: [
    'Libya',
    'ليبيا',
    'Libyen',
    'Libye',
    'Libia',
    'リビア',
    'Libië',
    'Libyan Arab Jamahiriya'
  ],
  vehicleRegistrationCode: 'LAR',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Libya',
    'af': 'Libië',
    'ak': 'Libya',
    'am': 'ሊቢያ',
    'an': 'Libya',
    'ar': 'ليبيا',
    'as': 'লিবিয়া',
    'ay': 'Libya',
    'az': 'Libya',
    'ba': 'Libya',
    'be': 'Лівія',
    'bg': 'Либия',
    'bi': 'Libya',
    'bn': 'লিবিয়া',
    'bn_IN': 'লিবিয়া',
    'br': 'Libia',
    'bs': 'Libija',
    'ca': 'Líbia',
    'ce': 'Ливи',
    'ch': 'Libya',
    'cs': 'Libye',
    'cv': 'Ливи',
    'cy': 'Libya',
    'da': 'Libyen',
    'de': 'Libyen',
    'dv': 'ލީބިޔާ',
    'dz': 'ལིབ་ཡ་',
    'ee': 'Libya',
    'el': 'Λιβύη',
    'en': 'Libya',
    'eo': 'Libio',
    'es': 'Libia',
    'et': 'Liibüa',
    'eu': 'Libia',
    'fa': 'لیبی',
    'ff': 'Libya',
    'fi': 'Libya',
    'fo': 'Libya',
    'fr': 'Libye',
    'fy': 'Lybje',
    'ga': 'An Libia',
    'gl': 'Libia',
    'gn': 'Libya',
    'gu': 'લિબયા',
    'gv': 'Yn Leeb',
    'ha': 'Libya',
    'he': 'לוב',
    'hi': 'लीबिया',
    'hr': 'Libija',
    'ht': 'Libi',
    'hu': 'Líbia',
    'hy': 'Լիբիա',
    'ia': 'Libya',
    'id': 'Libya',
    'io': 'Libia',
    'is': 'Líbýa',
    'it': 'Libia',
    'iu': 'Libya',
    'ja': 'リビア',
    'ka': 'Libya',
    'ki': 'Libya',
    'kk': 'Ливия',
    'kl': 'Libya',
    'km': 'លីបេរីយ៉ា',
    'kn': 'Libya',
    'ko': '리비아',
    'ku': 'Lîbya',
    'kv': 'Libya',
    'kw': 'Libi',
    'ky': 'Ливия',
    'lo': 'Libya',
    'lt': 'Libija',
    'lv': 'Lībija',
    'mi': 'Libya',
    'mk': 'Либија',
    'ml': 'Libya',
    'mn': 'Ливи',
    'mr': 'लिबया',
    'ms': 'Libya',
    'mt': 'Libja',
    'my': 'လစ်ဗျားနိုင်ငံ',
    'na': 'Libya',
    'nb': 'Libya',
    'ne': 'लिबेया',
    'nl': 'Libië',
    'nn': 'Libya',
    'nv': 'Libya',
    'oc': 'Libia',
    'or': 'ଲୀବିୟା',
    'pa': 'ਲੀਬੀਆ',
    'pi': 'लिबिया',
    'pl': 'Libia',
    'ps': 'Libya',
    'pt': 'Líbia',
    'pt_BR': 'Líbia',
    'ro': 'Libia',
    'ru': 'Ливия',
    'rw': 'Libiya',
    'sc': 'Lìbia',
    'sd': 'لبيا',
    'si': 'ලිබියාව',
    'sk': 'Líbya',
    'sl': 'Libija',
    'so': 'Libiya',
    'sq': 'Libi',
    'sr': 'Либија',
    'sv': 'Libyen',
    'sw': 'Libya',
    'ta': 'Libya',
    'te': 'లిబయా',
    'tg': 'Либия',
    'th': 'ลิเบีย',
    'ti': 'ሊብያ',
    'tk': 'Liwiýa',
    'tl': 'Libya',
    'tr': 'Libya',
    'tt': 'Libya',
    'ug': 'لىۋىيە',
    'uk': 'Лівія',
    'ur': 'لیبیا',
    'uz': 'Liviya',
    've': 'Libya',
    'vi': 'Li-bi',
    'wa': 'Libeye',
    'wo': 'Libi',
    'xh': 'Libya',
    'yo': 'Líbyà',
    'zh_CN': '利比亚',
    'zh_HK': '利比亞',
    'zh_TW': '利比亞',
    'zu': 'ILibiya'
  },
);
