import '../country.dart';

const countryLKA = Country(
  alpha2: 'LK',
  alpha3: 'LKA',
  continent: Continent.asia,
  countryCode: '94',
  currencyCode: 'LKR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'CE',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 7.873053999999999,
      longitude: 80.77179699999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 10.03377,
      longitude: 82.14479999999999,
    ),
    minCoordinate: Coordinate(
      latitude: 5.6816,
      longitude: 79.26769999999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 10.03377,
        longitude: 82.14479999999999,
      ),
      southwest: Coordinate(
        latitude: 5.6816,
        longitude: 79.26769999999999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'SRI',
  isoLongName: 'The Democratic Socialist Republic of Sri Lanka',
  isoShortName: 'Sri Lanka',
  isoShortNameLowerCase: null,
  languagesOfficial: ['si', 'ta'],
  languagesSpoken: ['si', 'ta'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10],
  nationalPrefix: '0',
  nationality: 'Sri Lankan',
  number: '144',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Southern Asia',
  unLocode: 'LK',
  unMember: true,
  unofficialNames: ['Sri Lanka', 'スリランカ'],
  vehicleRegistrationCode: 'CL',
  worldRegion: WorldRegion.apac,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Sri Lanka',
    'af': 'Sri Lanka',
    'ak': 'Sri Lanka',
    'am': 'ሽሪ ላንካ',
    'an': 'Sri Lanka',
    'ar': 'سريلانكا',
    'as': 'শ্ৰীলঙ্কা',
    'ay': 'Sri Lanka',
    'az': 'Şri Lanka',
    'ba': 'Sri Lanka',
    'be': 'Шры-Ланка',
    'bg': 'Шри Ланка',
    'bi': 'Sri Lanka',
    'bn': 'শ্রীলঙ্কা',
    'bn_IN': 'শ্রীলঙ্কা',
    'br': 'Sri Lanka',
    'bs': 'Šri Lanka',
    'ca': 'Sri Lanka',
    'ce': 'Шри-Ланка',
    'ch': 'Sri Lanka',
    'cs': 'Šrí Lanka',
    'cv': 'Шри-Ланка',
    'cy': 'Sri Lanka',
    'da': 'Sri Lanka',
    'de': 'Sri Lanka',
    'dv': 'އޮޅުދޫކަރަ',
    'dz': 'སི་རི་ལང་ཀ།(ཤྲི་ལངྐ་)',
    'ee': 'Sri Lanka',
    'el': 'Σρι Λάνκα',
    'en': 'Sri Lanka',
    'eo': 'Sri-Lanko',
    'es': 'Sri Lanka',
    'et': 'Sri Lanka',
    'eu': 'Sri Lanka',
    'fa': 'سری‌لانکا',
    'ff': 'Sri Lanka',
    'fi': 'Sri Lanka',
    'fo': 'Sri Lanka',
    'fr': 'Sri Lanka',
    'fy': 'Sry Lanka',
    'ga': 'Srí Lanca',
    'gl': 'Sri Lanka',
    'gn': 'Sri Lanka',
    'gu': 'શ્રી લંકા',
    'gv': 'Sri Lanka',
    'ha': 'Sri Lanka',
    'he': 'סרי לנקה',
    'hi': 'श्रीलंका',
    'hr': 'Šri Lanka',
    'ht': 'Srilanka',
    'hu': 'Srí Lanka',
    'hy': 'Շրի Լանկա',
    'ia': 'Sri Lanka',
    'id': 'Sri Lanka',
    'io': 'Sri-Lanka',
    'is': 'Srí Lanka',
    'it': 'Sri Lanka',
    'iu': 'Sri Lanka',
    'ja': 'スリランカ',
    'ka': 'შრი-ლანკა',
    'ki': 'Sri Lanka',
    'kk': 'Шри-Ланка',
    'kl': 'Sri Lanka',
    'km': 'ស្រីលង្កា',
    'kn': 'ಶ್ರೀಲಂಕಾ',
    'ko': '스리랑카',
    'ku': 'Srî Lanka',
    'kv': 'Шри-Ланка',
    'kw': 'Shri Lanka',
    'ky': 'Шри-Ланка',
    'lo': 'ປະເທດສີລັງກາ',
    'lt': 'Šri Lanka',
    'lv': 'Šrilanka',
    'mi': 'Hiri Rānaka',
    'mk': 'Шри Ланка',
    'ml': 'ശ്രീലങ്ക',
    'mn': 'Шри Ланка',
    'mr': 'श्री लंका',
    'ms': 'Sri Lanka',
    'mt': 'Sri Lanka',
    'my': 'သီရိလင်္ကာနိုင်ငံ',
    'na': 'Sri Lanka',
    'nb': 'Sri Lanka',
    'ne': 'श्री लङ्का',
    'nl': 'Sri Lanka',
    'nn': 'Sri Lanka',
    'nv': 'Naakaii Dootłʼizhí Bikéyah Dah Naaʼeełígíí',
    'oc': 'Sri Lanka',
    'or': 'ଶ୍ରୀଲଙ୍କା',
    'pa': 'ਸ੍ਰੀਲੰਕਾ',
    'pi': 'श्रीलङ्का',
    'pl': 'Sri Lanka',
    'ps': 'سریلانکا',
    'pt': 'Sri Lanka',
    'pt_BR': 'Sri Lanka',
    'ro': 'Sri Lanka',
    'ru': 'Шри-Ланка',
    'rw': 'Siri Lanka',
    'sc': 'Sri Lanka',
    'sd': 'سريلنڪا',
    'si': 'ශ්‍රී ලංකාව',
    'sk': 'Srí Lanka',
    'sl': 'Šrilanka',
    'so': 'Siirilaanka',
    'sq': 'Sri Lankë',
    'sr': 'Шри Ланка',
    'sv': 'Sri Lanka',
    'sw': 'Sri Lanka',
    'ta': 'இலங்கை',
    'te': 'శ్రీలంక',
    'tg': 'Князигарии Лихтенштейн',
    'th': 'ศรีลังกา',
    'ti': 'ስሪ ላንካ',
    'tk': 'Şri-Lanka',
    'tl': 'Sri Lanka',
    'tr': 'Sri Lanka',
    'tt': 'Шри Ланка',
    'ug': 'سىرىلانكا',
    'uk': 'Шрі-Ланка',
    'ur': 'سری لنکا',
    'uz': 'Shri-Lanka',
    've': 'Sri Lanka',
    'vi': 'Tích Lan',
    'wa': 'Sri Lanka',
    'wo': 'Siri Laaŋka',
    'xh': 'Sri Lanka',
    'yo': 'Sri Lanka',
    'zh_CN': '斯里兰卡',
    'zh_HK': '斯里蘭卡',
    'zh_TW': '斯里蘭卡',
    'zu': 'Sri Lanka'
  },
);
