import '../country.dart';

const countryLTU = Country(
  alpha2: 'LT',
  alpha3: 'LTU',
  continent: Continent.europe,
  countryCode: '370',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'LH',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 55.169438,
      longitude: 23.881275,
    ),
    maxCoordinate: Coordinate(
      latitude: 56.45032089999999,
      longitude: 26.835523,
    ),
    minCoordinate: Coordinate(
      latitude: 53.8967949,
      longitude: 20.931,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 56.45032089999999,
        longitude: 26.835523,
      ),
      southwest: Coordinate(
        latitude: 53.8967949,
        longitude: 20.931,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'LTU',
  isoLongName: 'The Republic of Lithuania',
  isoShortName: 'Lithuania',
  isoShortNameLowerCase: null,
  languagesOfficial: ['lt'],
  languagesSpoken: ['lt'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '8',
  nationality: 'Lithuanian',
  number: '440',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Northern Europe',
  unLocode: 'LT',
  unMember: true,
  unofficialNames: [
    'Lithuania',
    'Litauen',
    'Lituanie',
    'Lituania',
    'リトアニア',
    'Litouwen',
    'Літва',
    'Lietuva'
  ],
  vehicleRegistrationCode: 'LT',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: VatRates(
    standard: 21,
    reduced: [5, 9],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Lithuania',
    'af': 'Litoue',
    'ak': 'Lithuania',
    'am': 'ሑቱፃኒ።',
    'an': 'Lithuania',
    'ar': 'لثوانيا',
    'as': 'লিথুৱানিয়া',
    'ay': 'Lithuania',
    'az': 'Litva',
    'ba': 'Lithuania',
    'be': 'Літва',
    'bg': 'Литва',
    'bi': 'Lithuania',
    'bn': 'লিথুয়ানিয়া',
    'bn_IN': 'লিথুয়ানিয়া',
    'br': 'Lituania',
    'bs': 'Litvanija',
    'ca': 'Lituània',
    'ce': 'Литва',
    'ch': 'Lituania',
    'cs': 'Litva',
    'cv': 'Литва',
    'cy': 'Lithwania',
    'da': 'Litauen',
    'de': 'Litauen',
    'dv': 'ލިތުއޭނިއާ',
    'dz': 'ལི་ཐུ་ནི་ཡ།',
    'ee': 'Lithuania',
    'el': 'Λιθουανία',
    'en': 'Lithuania',
    'eo': 'Litovio',
    'es': 'Lituania',
    'et': 'Leedu',
    'eu': 'Lituania',
    'fa': 'لیتوانی',
    'ff': 'Lituwaniya',
    'fi': 'Liettua',
    'fo': 'Litava',
    'fr': 'Lituanie',
    'fy': 'Litouwen',
    'ga': 'An Liotuáin',
    'gl': 'Lituania',
    'gn': 'Lithuania',
    'gu': 'લિથુઆનીઆ',
    'gv': 'Yn Litaan',
    'ha': 'Lithuania',
    'he': 'ליטא',
    'hi': 'लिथुआनिया',
    'hr': 'Litva',
    'ht': 'Lityani',
    'hu': 'Litvánia',
    'hy': 'Լիտվա',
    'ia': 'Lituania',
    'id': 'Lituania',
    'io': 'Lituania',
    'is': 'Litháen',
    'it': 'Lituania',
    'iu': 'ᓕᐋᑐᕙ',
    'ja': 'リトアニア',
    'ka': 'ლიტვა',
    'ki': 'Lithuania',
    'kk': 'Литва',
    'kl': 'Lithuania',
    'km': 'លីទុយអានី',
    'kn': 'ಲಿಥುವೇನಿಯಾ',
    'ko': '리투아니아',
    'ku': 'Lîtvanya',
    'kv': 'Литва',
    'kw': 'Lithouani',
    'ky': 'Литва',
    'lo': 'ປະເທດລີຕົວນີ',
    'lt': 'Lietuva',
    'lv': 'Lietuva',
    'mi': 'Rituānia',
    'mk': 'Литванија',
    'ml': 'ലിത്വാനിയ',
    'mn': 'Литва',
    'mr': 'लिथुआनिया',
    'ms': 'Lithuania',
    'mt': 'Litwanja',
    'my': 'လစ်သူယေးနီးယားနိုင်ငံ',
    'na': 'Rituainiya',
    'nb': 'Litauen',
    'ne': 'लिथुआनिया',
    'nl': 'Litouwen',
    'nn': 'Litauen',
    'nv': 'Łitʼoowę́ęya',
    'oc': 'Lituània',
    'or': 'ଲିଥୁଆନିୟା',
    'pa': 'ਲੀਥੂਨੀਆ',
    'pi': 'लिथ्वानिया',
    'pl': 'Litwa',
    'ps': 'لېتوانيا',
    'pt': 'Lituânia',
    'pt_BR': 'Lituânia',
    'ro': 'Lituania',
    'ru': 'Литва',
    'rw': 'Lituwaniya',
    'sc': 'Lituània',
    'sd': 'Lithuania',
    'si': 'ලිතුවේනියාව',
    'sk': 'Litva',
    'sl': 'Litva',
    'so': 'Lithuania',
    'sq': 'Lituani',
    'sr': 'Литванија',
    'sv': 'Litauen',
    'sw': 'Lithuania',
    'ta': 'லிதுவேனியா',
    'te': 'లిథుఆనియా',
    'tg': 'Литва',
    'th': 'ลิทัวเนีย',
    'ti': 'ሊቱዌኒያ',
    'tk': 'Litwa',
    'tl': 'Lithuania',
    'tr': 'Litvanya',
    'tt': 'Литуаниа',
    'ug': 'لىتۋانىيە',
    'uk': 'Литва',
    'ur': 'لتھووینیا',
    'uz': 'Litva',
    've': 'Lituania',
    'vi': 'Li-tu-a-ni-a',
    'wa': 'Litwaneye',
    'wo': 'Lituwaani',
    'xh': 'Lithuania',
    'yo': 'Lituéníà',
    'zh_CN': '立陶宛',
    'zh_HK': '立陶宛',
    'zh_TW': '立陶宛',
    'zu': 'ILithuwaniya'
  },
);
