import '../country.dart';

const countryLUX = Country(
  alpha2: 'LU',
  alpha3: 'LUX',
  continent: Continent.europe,
  countryCode: '352',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'LU',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 49.815273,
      longitude: 6.129582999999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 50.18282,
      longitude: 6.530970099999999,
    ),
    minCoordinate: Coordinate(
      latitude: 49.447779,
      longitude: 5.7356699,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 50.18282,
        longitude: 6.530970099999999,
      ),
      southwest: Coordinate(
        latitude: 49.447779,
        longitude: 5.7356699,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'LUX',
  isoLongName: 'The Grand Duchy of Luxembourg',
  isoShortName: 'Luxembourg',
  isoShortNameLowerCase: null,
  languagesOfficial: ['fr', 'de', 'lb'],
  languagesSpoken: ['fr', 'de', 'lb'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: 'None',
  nationality: 'Luxembourger',
  number: '442',
  postalCode: true,
  postalCodeFormat: r'\d{4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Western Europe',
  unLocode: 'LU',
  unMember: true,
  unofficialNames: ['Luxembourg', 'Luxemburg', 'Luxemburgo', 'ルクセンブルク'],
  vehicleRegistrationCode: 'L',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 17.0,
    reduced: [8.0, 14.0],
    superReduced: 3.0,
    parking: 12.0,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Luxembourg",
    "af": "Luxenburg",
    "ak": "Luxembourg",
    "am": "ሉክሰምበርግ",
    "an": "Luxembourg",
    "ar": "لوكسمبورغ",
    "as": "লাক্সেমবুৰ্গ",
    "ay": "Luxembourg",
    "az": "Lüksemburq",
    "ba": "Luxembourg",
    "be": "Люксембург",
    "bg": "Люксембург",
    "bi": "Luxembourg",
    "bn": "লাক্সেমবুর্গ",
    "bn_IN": "লাক্সেমবুর্গ",
    "br": "Luksembourg",
    "bs": "Luksemburg",
    "ca": "Luxemburg",
    "ce": "Люксембург",
    "ch": "Luxembourg",
    "cs": "Lucembursko",
    "cv": "Люксембург",
    "cy": "Lwcsembwrg",
    "da": "Luxembourg",
    "de": "Luxemburg",
    "dv": "Luxembourg",
    "dz": "ལག་ཟེམ་བཱརག།",
    "ee": "Luxembourg",
    "el": "Λουξεμβούργο",
    "en": "Luxembourg",
    "eo": "Luksemburgio",
    "es": "Luxemburgo",
    "et": "Luksemburg",
    "eu": "Luxenburgo",
    "fa": "لوگزامبورگ",
    "ff": "Luksammbuur",
    "fi": "Luxemburg",
    "fo": "Luksemborg",
    "fr": "Luxembourg",
    "fy": "Lúksemboarch",
    "ga": "Lucsamburg",
    "gl": "Luxemburgo",
    "gn": "Luxembourg",
    "gu": "લક્ઝમબર્ગ",
    "gv": "Lucsemburg",
    "ha": "Luksamburg",
    "he": "לוקסמבורג",
    "hi": "लक्ज़मबर्ग",
    "hr": "Luksemburg",
    "ht": "Liksanbou",
    "hu": "Luxemburg",
    "hy": "Լյուքսեմբուրգ",
    "ia": "Luxemburg",
    "id": "Luksemburg",
    "io": "Luxemburgia",
    "is": "Lúxemborg",
    "it": "Lussemburgo",
    "iu": "Luxembourg",
    "ja": "ルクセンブルク",
    "ka": "ლუქსემბურგი",
    "ki": "Luxembourg",
    "kk": "Люксембург",
    "kl": "Luxembourg",
    "km": "លុចហ្សំបួរ",
    "kn": "ಲುಗ್ಸೆಮ್ಬರ್ಗ್",
    "ko": "룩셈부르크",
    "ku": "Luksemburg",
    "kv": "Люксембург",
    "kw": "Lushaborg",
    "ky": "Люксембург",
    "lo": "ປະເທດລູກຊຳບວກ",
    "lt": "Liuksemburgas",
    "lv": "Luksemburga",
    "mi": "Rakapuō",
    "mk": "Луксембург",
    "ml": "ലക്സെംബര്‍ഗ്",
    "mn": "Льюксембург",
    "mr": "लग्झेंबर्ग",
    "ms": "Luksembourg",
    "mt": "Lussemburgu",
    "my": "လူဇင်ဘတ်နိုင်ငံ",
    "na": "Ruketemburg",
    "nb": "Luxembourg",
    "ne": "लक्जेम्बर्ग",
    "nl": "Luxemburg",
    "nn": "Luxembourg; Luxemburg",
    "nv": "Látsębooʼ",
    "oc": "Luxemborg",
    "or": "ଲେକଜେମ୍ବର୍ଗ",
    "pa": "ਲ਼ਕਸ਼ਬਰਗ",
    "pi": "लक्सम्बर्ग",
    "pl": "Luksemburg",
    "ps": "لوګزامبورګ",
    "pt": "Luxemburgo",
    "pt_BR": "Luxemburgo",
    "ro": "Luxemburg",
    "ru": "Люксембург",
    "rw": "Lugizamburu",
    "sc": "Lussemburgu",
    "sd": "لڪسمبرگ",
    "si": "ලක්සම්බර්ග්",
    "sk": "Luxembursko",
    "sl": "Luksemburg",
    "so": "Luksemboorg",
    "sq": "Luksemburg",
    "sr": "Луксембург",
    "sv": "Luxemburg",
    "sw": "Luxembourg",
    "ta": "லக்ஸம்பர்க்",
    "te": "లగ్జెంబర్గ్",
    "tg": "Люксембург",
    "th": "ลักเซมเบิร์ก",
    "ti": "Luxembourg",
    "tk": "Lýuksemburg",
    "tl": "Luxembourg",
    "tr": "Lüksemburg",
    "tt": "Лүксембурg",
    "ug": "لىيۇكسېمبۇرگ",
    "uk": "Люксембург",
    "ur": "لکسمبرگ",
    "uz": "Lyuksemburg",
    "ve": "Luxembourg",
    "vi": "Lục Xâm Bảo",
    "wa": "Lussimbork",
    "wo": "Luksembuur",
    "xh": "Luxembourg",
    "yo": "Lúksẹ́mbọ̀rg",
    "zh_CN": "卢森堡",
    "zh_HK": "盧森堡",
    "zh_TW": "盧森堡",
    "zu": "I-Luxembourg"
  },
);
