import '../country.dart';

const countryMAR = Country(
  alpha2: 'MA',
  alpha3: 'MAR',
  continent: Continent.africa,
  countryCode: '212',
  currencyCode: 'MAD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'MO',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 31.791702,
      longitude: -7.092619999999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 35.9344,
      longitude: -0.9969759,
    ),
    minCoordinate: Coordinate(
      latitude: 27.6672693,
      longitude: -13.3044001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 35.9344,
        longitude: -0.9969759,
      ),
      southwest: Coordinate(
        latitude: 27.6672693,
        longitude: -13.3044001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'MAR',
  isoLongName: 'The Kingdom of Morocco',
  isoShortName: 'Morocco',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar'],
  languagesSpoken: ['ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '0',
  nationality: 'Moroccan',
  number: '504',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Northern Africa',
  unLocode: 'MA',
  unMember: true,
  unofficialNames: [
    'Morocco',
    'المغرب',
    'Marokko',
    'Maroc',
    'Marruecos',
    'モロッコ'
  ],
  vehicleRegistrationCode: 'MA',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Morocco',
    'af': 'Marokko',
    'ak': 'Morocco',
    'am': 'ሥስጥ',
    'an': 'Morocco',
    'ar': 'المغرب',
    'as': 'মৰোক্কো',
    'ay': 'Morocco',
    'az': 'Mərakeş',
    'ba': 'Morocco',
    'be': 'Марока',
    'bg': 'Мароко',
    'bi': 'Morocco',
    'bn': 'মরোক্কো',
    'bn_IN': 'মরোক্কো',
    'br': 'Maroko',
    'bs': 'Maroko',
    'ca': 'Marroc',
    'ce': 'Марокко',
    'ch': 'Morocco',
    'cs': 'Maroko',
    'cv': 'Марокко',
    'cy': 'Moroco',
    'da': 'Marokko',
    'de': 'Marokko',
    'dv': 'މައުރިބު',
    'dz': 'མོ་རོཀ་ཀོ།',
    'ee': 'Morocco',
    'el': 'Μαρόκο',
    'en': 'Morocco',
    'eo': 'Maroko',
    'es': 'Marruecos',
    'et': 'Maroko',
    'eu': 'Maroko',
    'fa': 'مراکش',
    'ff': 'Morocco',
    'fi': 'Marokko',
    'fo': 'Marokko',
    'fr': 'Maroc',
    'fy': 'Marokko',
    'ga': 'Maracó',
    'gl': 'Marrocos',
    'gn': 'Morocco',
    'gu': 'મોરક્કો',
    'gv': 'Yn Varoc',
    'ha': 'Morocco',
    'he': 'מרוקו',
    'hi': 'मोरक्को',
    'hr': 'Maroko',
    'ht': 'Mawòk',
    'hu': 'Marokkó',
    'hy': 'Մարոկո',
    'ia': 'Marocco',
    'id': 'Maroko',
    'io': 'Maroko',
    'is': 'Marokkó',
    'it': 'Marocco',
    'iu': 'Morocco',
    'ja': 'モロッコ',
    'ka': 'მაროკო',
    'ki': 'Morocco',
    'kk': 'Марокко',
    'kl': 'Morocco',
    'km': 'ម៉ារ៉ុក',
    'kn': 'ಮೊರೊಕ್ಕೊ',
    'ko': '모로코',
    'ku': 'Fas',
    'kv': 'Morocco',
    'kw': 'Marokk',
    'ky': 'Марокко',
    'lo': 'Morocco',
    'lt': 'Marokas',
    'lv': 'Maroka',
    'mi': 'Moroko',
    'mk': 'Мароко',
    'ml': 'മൊറോക്കോ',
    'mn': 'Морокко',
    'mr': 'मोरोक्को',
    'ms': 'Maghribi',
    'mt': 'Marokk',
    'my': 'မော်ရိုကိုနိုင်ငံ',
    'na': 'Morocco',
    'nb': 'Marokko',
    'ne': 'मोरक्को',
    'nl': 'Marokko',
    'nn': 'Marokko',
    'nv': 'Eʼeʼaahjí Ghą́ą́ʼaskʼidii Biłikahii Bikéyah',
    'oc': 'Marròc',
    'or': 'ମୋରକ୍କୋ',
    'pa': 'ਮੋਰੋਸ਼ਸੋ',
    'pi': 'मोराको',
    'pl': 'Maroko',
    'ps': 'مراکش',
    'pt': 'Marrocos',
    'pt_BR': 'Marrocos',
    'ro': 'Maroc',
    'ru': 'Марокко',
    'rw': 'Maroke',
    'sc': 'Marocu',
    'sd': 'Morocco',
    'si': 'මොරොක්කෝව',
    'sk': 'Maroko',
    'sl': 'Maroko',
    'so': 'Marooko',
    'sq': 'Marok',
    'sr': 'Мароко',
    'sv': 'Marocko',
    'sw': 'Morocco',
    'ta': 'மொரோக்கோ',
    'te': 'మోరోక్కో',
    'tg': 'Марокаш',
    'th': 'โมร็อกโก',
    'ti': 'ሞሮኮ',
    'tk': 'Morokko',
    'tl': 'Morocco',
    'tr': 'Fas',
    'tt': 'Морокко',
    'ug': 'ماراكەش',
    'uk': 'Марокко',
    'ur': 'مراکش',
    'uz': 'Marokash',
    've': 'Morocco',
    'vi': 'Mo-ro-cô',
    'wa': 'Marok',
    'wo': 'Marook',
    'xh': 'Morocco',
    'yo': 'Mòrókò',
    'zh_CN': '摩洛哥',
    'zh_HK': '摩洛哥',
    'zh_TW': '摩洛哥',
    'zu': 'IMorokho'
  },
);
