import '../country.dart';

const countryMDA = Country(
  alpha2: 'MD',
  alpha3: 'MDA',
  continent: Continent.europe,
  countryCode: '373',
  currencyCode: 'MDL',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'MD',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 47.411631,
      longitude: 28.369885,
    ),
    maxCoordinate: Coordinate(
      latitude: 48.492029,
      longitude: 30.1635898,
    ),
    minCoordinate: Coordinate(
      latitude: 45.4674379,
      longitude: 26.6164248,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 48.492029,
        longitude: 30.1635898,
      ),
      southwest: Coordinate(
        latitude: 45.4674379,
        longitude: 26.6164248,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'MDA',
  isoLongName: 'The Republic of Moldova',
  isoShortName: 'Moldova (Republic of)',
  isoShortNameLowerCase: 'Moldova (the Republic of)',
  languagesOfficial: ['ro'],
  languagesSpoken: ['ro'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '0',
  nationality: 'Moldovan',
  number: '498',
  postalCode: true,
  postalCodeFormat: r'\d{4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Eastern Europe',
  unLocode: 'MD',
  unMember: true,
  unofficialNames: [
    'Moldova',
    'Moldawien',
    'Moldavie',
    'Moldavia',
    'Moldova (Republic of)',
    'the Republic of Moldova',
    'モルドバ共和国',
    'Moldavië'
  ],
  vehicleRegistrationCode: 'MD',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Moldova",
    "af": "Moldawië",
    "ak": "Moldova",
    "am": "ሞልዶቫ",
    "an": "Moldova",
    "ar": "المالديف",
    "as": "মোলডোভা",
    "ay": "Moldova",
    "az": "Moldova",
    "ba": "Moldova",
    "be": "Малдова",
    "bg": "Молдова",
    "bi": "Moldova",
    "bn": "মোলডোভা",
    "bn_IN": "মোলডোভা",
    "br": "Moldova",
    "bs": "Moldavija",
    "ca": "Moldàvia",
    "ce": "Молдави",
    "ch": "Moldova",
    "cs": "Moldavsko",
    "cv": "Молдави",
    "cy": "Moldofa",
    "da": "Moldova",
    "de": "Moldau",
    "dv": "މޮލްޑޯވާ",
    "dz": "མོལ་ཌོ་ཝ།",
    "ee": "Moldova",
    "el": "Μολδαβία",
    "en": "Moldova",
    "eo": "Moldavio",
    "es": "Moldavia",
    "et": "Moldova",
    "eu": "Moldavia",
    "fa": "مولداوی",
    "ff": "Moldowa",
    "fi": "Moldova",
    "fo": "Moldova",
    "fr": "Moldavie",
    "fy": "Moldaavje",
    "ga": "An Mholdóiv",
    "gl": "Moldavia",
    "gn": "Moldova",
    "gu": "મોલ્ડોવા",
    "gv": "Moldova",
    "ha": "MOldufiniya",
    "he": "מולדובה",
    "hi": "मॉल्डोवा",
    "hr": "Moldavija",
    "ht": "Moldavi",
    "hu": "Moldova",
    "hy": "Մոլդովա",
    "ia": "Moldavia",
    "id": "Moldova",
    "io": "Moldova",
    "is": "Moldavía",
    "it": "Moldavia",
    "iu": "Moldova",
    "ja": "モルドバ",
    "ka": "მოლდოვა",
    "ki": "Moldova",
    "kk": "Молдова",
    "kl": "Moldova",
    "km": "មុលឌូវ៉ា",
    "kn": "Moldova",
    "ko": "몰도바",
    "ku": "Moldova",
    "kv": "Молдова",
    "kw": "Moldova",
    "ky": "Молдова",
    "lo": "Moldova",
    "lt": "Moldova",
    "lv": "Moldova",
    "mi": "Morotawa",
    "mk": "Молдавија",
    "ml": "മോള്‍ഡോവ",
    "mn": "Молдав",
    "mr": "मोल्डोवा",
    "ms": "Moldova",
    "mt": "Moldova",
    "my": "မော်လ်ဒိုဗာနိုင်ငံ",
    "na": "Ripubrikin Mordowa",
    "nb": "Moldova",
    "ne": "मोल्डोभा",
    "nl": "Moldavië",
    "nn": "Moldova",
    "nv": "Moldova",
    "oc": "Moldàvia",
    "or": "ମାଲଡୋଭା",
    "pa": "ਮੋਲਡੀਵਾ",
    "pi": "मोल्दोवा",
    "pl": "Mołdawia",
    "ps": "مولدوا",
    "pt": "Moldávia",
    "pt_BR": "Moldávia",
    "ro": "Moldova",
    "ru": "Молдавия",
    "rw": "Molidova",
    "sc": "Moldàvia",
    "sd": "Moldova",
    "si": "මොල්ඩෝවා",
    "sk": "Moldavsko",
    "sl": "Moldavija",
    "so": "Moldofa",
    "sq": "Moldavi",
    "sr": "Молдавија",
    "sv": "Moldavien",
    "sw": "Moldova",
    "ta": "மோல்டோவா",
    "te": "మాల్డోవా",
    "tg": "Молдова",
    "th": "มอลโดวา",
    "ti": "Moldova",
    "tk": "Moldawiýa",
    "tl": "Moldova",
    "tr": "Moldova",
    "tt": "Moldova",
    "ug": "مولدوۋا",
    "uk": "Молдова",
    "ur": "مالدووا",
    "uz": "Moldova",
    "ve": "Moldova",
    "vi": "Mon-đô-va",
    "wa": "Moldova",
    "wo": "Moldaawi",
    "xh": "Moldova",
    "yo": "Móldófà",
    "zh_CN": "摩尔多瓦",
    "zh_HK": "摩爾多瓦",
    "zh_TW": "摩爾多瓦",
    "zu": "Moldova"
  },
);
