import '../country.dart';

const countryMDV = Country(
  alpha2: 'MV',
  alpha3: 'MDV',
  continent: Continent.asia,
  countryCode: '960',
  currencyCode: 'MVR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'MV',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 3.202778,
      longitude: 73.22068,
    ),
    maxCoordinate: Coordinate(
      latitude: 7.5149809,
      longitude: 74.7290038,
    ),
    minCoordinate: Coordinate(
      latitude: -1.2907844,
      longitude: 71.75170899999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 7.5149809,
        longitude: 74.7290038,
      ),
      southwest: Coordinate(
        latitude: -1.2907844,
        longitude: 71.75170899999999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'MDV',
  isoLongName: 'The Republic of Maldives',
  isoShortName: 'Maldives',
  isoShortNameLowerCase: null,
  languagesOfficial: ['dv'],
  languagesSpoken: ['dv'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7],
  nationalPrefix: 'None',
  nationality: 'Maldivan',
  number: '462',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.asia,
  startOfWeek: Week.sunday,
  subregion: 'Southern Asia',
  unLocode: 'MV',
  unMember: true,
  unofficialNames: ['Maldives', 'Malediven', 'Maldivas', 'モルディブ', 'Maldiven'],
  vehicleRegistrationCode: 'MV',
  worldRegion: WorldRegion.apac,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Maldives',
    'af': 'Maledive',
    'ak': 'Maldives',
    'am': 'ማልዲቭስ',
    'an': 'Maldives',
    'ar': 'جزر المالديف',
    'as': 'মালডিভ্‌চ',
    'ay': 'Maldives',
    'az': 'Maldives',
    'ba': 'Maldives',
    'be': 'Мальдывы',
    'bg': 'Малдиви',
    'bi': 'Maldives',
    'bn': 'মালডিভস',
    'bn_IN': 'মালডিভস',
    'br': 'Maldivez',
    'bs': 'Maldivi',
    'ca': 'Maldives',
    'ce': 'Мальдиви',
    'ch': 'Maldives',
    'cs': 'Maledivy',
    'cv': 'Мальдиви',
    'cy': 'Maldives',
    'da': 'Maldiverne',
    'de': 'Malediven',
    'dv': 'ދިވެހިރާއްޖެ',
    'dz': 'མེལ་ཌིབསི།',
    'ee': 'Maldives',
    'el': 'Μαλδίβες',
    'en': 'Maldives',
    'eo': 'Maldivoj',
    'es': 'Islas Maldivas',
    'et': 'Maldiivid',
    'eu': 'Maldivak',
    'fa': 'مالدیو',
    'ff': 'Maldives',
    'fi': 'Malediivit',
    'fo': 'Maldivuoyggjarnar',
    'fr': 'Maldives',
    'fy': 'Maldiven',
    'ga': 'Oileáin Mhaildíve',
    'gl': 'Maldivas',
    'gn': 'Maldives',
    'gu': 'માલ્દીવ્સ',
    'gv': 'Ny Maldeevaghyn',
    'ha': 'Maldives',
    'he': 'האיים המלדיביים',
    'hi': 'मालदीव',
    'hr': 'Maldivi',
    'ht': 'Maldiv',
    'hu': 'Maldív-szigetek',
    'hy': 'Մալդիվներ',
    'ia': 'Maldivas',
    'id': 'Maladewa',
    'io': 'Maldivi',
    'is': 'Maldíveyjar',
    'it': 'Maldive',
    'iu': 'Maldives',
    'ja': 'モルディブ',
    'ka': 'მალდივის კუნძულები',
    'ki': 'Maldives',
    'kk': 'Мальдив аралдары',
    'kl': 'Maldives',
    'km': 'ម៉ាល់ឌីវ',
    'kn': 'ಮಾಲ್ಡೀವ್ಸ್',
    'ko': '몰디브',
    'ku': 'Giravên Maldiv',
    'kv': 'Мальдивъяс',
    'kw': 'Maldivys',
    'ky': 'Мальдивдер',
    'lo': 'Maldives',
    'lt': 'Maldyvai',
    'lv': 'Maldīvija',
    'mi': 'Maldives',
    'mk': 'Малдиви',
    'ml': 'മാല്‍ഡീവ്സ്',
    'mn': 'Малдивс',
    'mr': 'मालदिव्हज्',
    'ms': 'Maldiv',
    'mt': 'Maldivi',
    'my': 'မော်လဒိုက်နိုင်ငံ',
    'na': 'Mardib',
    'nb': 'Maldivene',
    'ne': 'मालदिव्स',
    'nl': 'Maldiven',
    'nn': 'Maldivane',
    'nv': 'Naakaii Dootłʼizhí Bikéyah Yázhí',
    'oc': 'Maldivas',
    'or': 'ମାଲଦୀଭ',
    'pa': 'ਮਾਲਦੀਵ',
    'pi': 'मालदीव',
    'pl': 'Malediwy',
    'ps': 'مالديپ',
    'pt': 'Maldivas',
    'pt_BR': 'Maldivas',
    'ro': 'Maldive',
    'ru': 'Мальдивы',
    'rw': 'Malidivezi',
    'sc': 'Maldivas',
    'sd': 'مالديپ',
    'si': 'මාල දිවයින',
    'sk': 'Maldivy',
    'sl': 'Maldivi',
    'so': 'Maaldiqeen',
    'sq': 'Maldive',
    'sr': 'Малдиви',
    'sv': 'Maldiverna',
    'sw': 'Maldives',
    'ta': 'மாலதீவுகள்',
    'te': 'మాల్దీవ్స్',
    'tg': 'Малдив',
    'th': 'มัลดีฟส์',
    'ti': 'Maldives',
    'tk': 'Maldiw adalary',
    'tl': 'Maldives',
    'tr': 'Maldivler',
    'tt': 'Малдивлар',
    'ug': 'مالدىۋې',
    'uk': 'Мальдіви',
    'ur': 'مالدیپ',
    'uz': 'Maldivalar',
    've': 'Maldives',
    'vi': 'Mal-đi-vợx',
    'wa': 'Maldives',
    'wo': 'Maldiif',
    'xh': 'Maldives',
    'yo': 'Àwọn Maldive',
    'zh_CN': '马尔代夫',
    'zh_HK': '馬爾代夫',
    'zh_TW': '馬爾地夫',
    'zu': 'Maldives'
  },
);
