import '../country.dart';

const countryMHL = Country(
  alpha2: 'MH',
  alpha3: 'MHL',
  continent: Continent.australia,
  countryCode: '692',
  currencyCode: 'USD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'RM',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 7.131474,
      longitude: 171.184478,
    ),
    maxCoordinate: Coordinate(
      latitude: 15.0190749,
      longitude: 172.5732421,
    ),
    minCoordinate: Coordinate(
      latitude: 4.1601583,
      longitude: 159.8840332,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 15.0190749,
        longitude: 172.5732421,
      ),
      southwest: Coordinate(
        latitude: 4.1601583,
        longitude: 159.8840332,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'MHL',
  isoLongName: 'The Republic of the Marshall Islands',
  isoShortName: 'Marshall Islands',
  isoShortNameLowerCase: 'Marshall Islands (the)',
  languagesOfficial: ['en', 'mh'],
  languagesSpoken: ['en', 'mh'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7],
  nationalPrefix: '1',
  nationality: 'Marshallese',
  number: '584',
  postalCode: true,
  postalCodeFormat: r'(969[67]\d)(?:[ \-](\d{4}))?',
  region: Region.oceania,
  startOfWeek: Week.monday,
  subregion: 'Micronesia',
  unLocode: 'MH',
  unMember: true,
  unofficialNames: [
    'Marshall Islands',
    'Marshallinseln',
    'Îles Marshall',
    'Islas Marshall',
    'マーシャル諸島',
    'Marshalleilanden'
  ],
  vehicleRegistrationCode: 'MH',
  worldRegion: WorldRegion.apac,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Marshall Islands",
    "af": "Marshall-eilande",
    "ak": "Marshall Islands",
    "am": "Marshall Islands",
    "an": "Marshall Islands",
    "ar": "جزر المارشال",
    "as": "মাৰ্শ্বেল দ্বীপপুঞ্জ",
    "ay": "Marshall Islands",
    "az": "Marşal Adaları",
    "ba": "Marshall Islands",
    "be": "Маршалавы Астравы",
    "bg": "Маршалски острови",
    "bi": "Marshall Islands",
    "bn": "মার্শাল দ্বীপপুঞ্জ",
    "bn_IN": "মার্শাল দ্বীপপুঞ্জ",
    "br": "Marshall Islands",
    "bs": "Maršalska Ostrva",
    "ca": "Illes Marshall",
    "ce": "Marshall Islands",
    "ch": "Marshall Islands",
    "cs": "Marshallovy ostrovy",
    "cv": "Marshall Islands",
    "cy": "Ynysoedd Marshall",
    "da": "Marshalløerne",
    "de": "Marshallinseln",
    "dv": "Marshall Islands",
    "dz": "མར་ཤཱལ་ ཨའི་ལེནཌིསི།",
    "ee": "Marshall Islands",
    "el": "Νήσοι Μάρσαλ",
    "en": "Marshall Islands",
    "eo": "Marŝaloj",
    "es": "Islas Marshall",
    "et": "Marshalli Saared",
    "eu": "Marshall uharteak",
    "fa": "جزایر مارشال",
    "ff": "Marshall Islands",
    "fi": "Marshallinsaaret",
    "fo": "Marshalloyggjarnar",
    "fr": "Îles Marshall",
    "fy": "Marshall Islands",
    "ga": "Oileáin Marshall",
    "gl": "Illas Marshall",
    "gn": "Marshall Islands",
    "gu": "માર્શલ ટાપુઓ",
    "gv": "Marshall Islands",
    "ha": "Marshall Islands",
    "he": "איי מרשל",
    "hi": "मार्शल आइलैंड्स",
    "hr": "Maršalovi otoci",
    "ht": "Marshall Islands",
    "hu": "Marshall-szigetek",
    "hy": "Մարշալյան կղզիներ",
    "ia": "Insulas Marshall",
    "id": "Kepulauan Marshall",
    "io": "Marshall Islands",
    "is": "Marshalleyjar",
    "it": "Isole Marshall",
    "iu": "Marshall Islands",
    "ja": "マーシャル諸島",
    "ka": "მარშალის კუნძულები",
    "ki": "Marshall Islands",
    "kk": "Маршалл аралдары",
    "kl": "Marshall Islands",
    "km": "កោះ​ម៉ាស្យល",
    "kn": "ಮಾರ್ಷಲ್ ದ್ವೀಪಗಳು",
    "ko": "마셜 제도",
    "ku": "Giravên Marsal",
    "kv": "Marshall Islands",
    "kw": "Marshall Islands",
    "ky": "Маршалл аралдары",
    "lo": "Marshall Islands",
    "lt": "Maršalo salos",
    "lv": "Māršala salas",
    "mi": "Marshall Islands",
    "mk": "Маршалови острови",
    "ml": "മാര്‍ഷല്‍ ദ്വീപുകള്‍",
    "mn": "Маршаллын арлууд",
    "mr": "मार्शल आयलॅंडस्",
    "ms": "Kepulauan Marshall",
    "mt": "Gżejjer ta' Marshall",
    "my": "Marshall Islands",
    "na": "Marshall Islands",
    "nb": "Marshalløyene",
    "ne": "मार्शल टापु",
    "nl": "Marshalleilanden",
    "nn": "Marshalløyane",
    "nv": "Marshall Islands",
    "oc": "Illas Marshall",
    "or": "ମାର୍ଶଲ ଦ୍ବୀପ",
    "pa": "ਮਾਰਸ਼ਲ ਟਾਪੂ",
    "pi": "Marshall Islands",
    "pl": "Wyspy Marshalla",
    "ps": "Marshall Islands",
    "pt": "Ilhas Marshall",
    "pt_BR": "Ilhas Marshall",
    "ro": "Insulele Marshall",
    "ru": "Маршалловы острова",
    "rw": "Ibirwa bya Marishali",
    "sc": "Ìsulas Marshall",
    "sd": "Marshall Islands",
    "si": "මාශල් දූපත්",
    "sk": "Marshallove ostrovy",
    "sl": "Marshallovi otoki",
    "so": "Marshall Islands",
    "sq": "Ishujt Marshall",
    "sr": "Маршалска острва",
    "sv": "Marshallöarna",
    "sw": "Marshall Islands",
    "ta": "மார்சல் தீவுகள்",
    "te": "మార్షల్ ఐలాండ్స్",
    "tg": "Ҷазираҳои Маршал",
    "th": "หมู่เกาะมาร์แชลล์",
    "ti": "Marshall Islands",
    "tk": "Marşal adaslary",
    "tl": "Marshall Islands",
    "tr": "Marşal Adaları",
    "tt": "Маршал Утравлары",
    "ug": "مارشال تاقىم ئارىلى",
    "uk": "Маршаллові острови",
    "ur": "Marshall Islands",
    "uz": "Marshall Islands",
    "ve": "Marshall Islands",
    "vi": "Quần Đảo Ma-san",
    "wa": "Iyes Marshall",
    "wo": "Marshall Islands",
    "xh": "Marshall Islands",
    "yo": "Marshall Islands",
    "zh_CN": "马绍尔群岛",
    "zh_HK": "馬紹爾羣島",
    "zh_TW": "馬紹爾群島",
    "zu": "Marshall Islands"
  },
);
