import '../country.dart';

const countryMLT = Country(
  alpha2: 'MT',
  alpha3: 'MLT',
  continent: Continent.europe,
  countryCode: '356',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'MT',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 35.937496,
      longitude: 14.375416,
    ),
    maxCoordinate: Coordinate(
      latitude: 36.0853,
      longitude: 14.5765999,
    ),
    minCoordinate: Coordinate(
      latitude: 35.79960000000001,
      longitude: 14.1801001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 36.0853,
        longitude: 14.5765999,
      ),
      southwest: Coordinate(
        latitude: 35.79960000000001,
        longitude: 14.1801001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'MLT',
  isoLongName: 'The Republic of Malta',
  isoShortName: 'Malta',
  isoShortNameLowerCase: null,
  languagesOfficial: ['mt', 'en'],
  languagesSpoken: ['mt', 'en'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: '21',
  nationality: 'Maltese',
  number: '470',
  postalCode: true,
  postalCodeFormat: r'[A-Z]{3} ?\d{2,4}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Southern Europe',
  unLocode: 'MT',
  unMember: true,
  unofficialNames: ['Malta', 'Malte', 'マルタ'],
  vehicleRegistrationCode: 'M',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: VatRates(
    standard: 18.0,
    reduced: [5.0, 7.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Malta",
    "af": "Malta",
    "ak": "Malta",
    "am": "ሢሔታ",
    "an": "Malta",
    "ar": "مالطة",
    "as": "মাল্টা",
    "ay": "Malta",
    "az": "Malta",
    "ba": "Malta",
    "be": "Мальта",
    "bg": "Малта",
    "bi": "Malta",
    "bn": "মল্টা",
    "bn_IN": "মল্টা",
    "br": "Malta",
    "bs": "Malta",
    "ca": "Malta",
    "ce": "Мальта",
    "ch": "Malta",
    "cs": "Malta",
    "cv": "Мальта",
    "cy": "Malta",
    "da": "Malta",
    "de": "Malta",
    "dv": "މޯލްޓާ",
    "dz": "མཱལ་ཊ་ མི་སེར་རྒྱལ་ཁབ།",
    "ee": "Malta",
    "el": "Μάλτα",
    "en": "Malta",
    "eo": "Malto",
    "es": "Malta",
    "et": "Malta",
    "eu": "Malta",
    "fa": "جزیره مالت",
    "ff": "Malta",
    "fi": "Malta",
    "fo": "Malta",
    "fr": "Malte",
    "fy": "Malta",
    "ga": "Málta",
    "gl": "Malta",
    "gn": "Malta",
    "gu": "માલ્ટા",
    "gv": "Yn Valta",
    "ha": "Malta",
    "he": "מלטה",
    "hi": "माल्टा",
    "hr": "Malta",
    "ht": "Malt",
    "hu": "Málta",
    "hy": "Մալթա",
    "ia": "Malta",
    "id": "Malta",
    "io": "Malta",
    "is": "Malta",
    "it": "Malta",
    "iu": "Malta",
    "ja": "マルタ",
    "ka": "მალტა",
    "ki": "Malta",
    "kk": "Мальта",
    "kl": "Malta",
    "km": "ម៉ាល់តា",
    "kn": "ಮಾಲ್ಟಾ",
    "ko": "몰타",
    "ku": "Malta",
    "kv": "Мальта",
    "kw": "Malta",
    "ky": "Мальта",
    "lo": "ປະເທດມັນ",
    "lt": "Malta",
    "lv": "Malta",
    "mi": "Mārata",
    "mk": "Малта",
    "ml": "മാള്‍ട്ട",
    "mn": "Малта",
    "mr": "माल्टा",
    "ms": "Malta",
    "mt": "Malta",
    "my": "မော်လတာနိုင်ငံ",
    "na": "Marta",
    "nb": "Malta",
    "ne": "माल्टा",
    "nl": "Malta",
    "nn": "Malta",
    "nv": "Malta",
    "oc": "Malta",
    "or": "ମାଲ୍ଟା",
    "pa": "ਮਾਲਟਾ",
    "pi": "माल्टा",
    "pl": "Malta",
    "ps": "مالټا",
    "pt": "Malta",
    "pt_BR": "Malta",
    "ro": "Malta",
    "ru": "Мальта",
    "rw": "Malita",
    "sc": "Malta",
    "sd": "Malta",
    "si": "මෝල්ටා",
    "sk": "Malta",
    "sl": "Malta",
    "so": "Maalda",
    "sq": "Maltë",
    "sr": "Малта",
    "sv": "Malta",
    "sw": "Malta",
    "ta": "மால்டா",
    "te": "మాల్టా",
    "tg": "Малта",
    "th": "มอลตา",
    "ti": "ማልታ",
    "tk": "Malta",
    "tl": "Malta",
    "tr": "Malta",
    "tt": "Малта",
    "ug": "مالتا",
    "uk": "Мальта",
    "ur": "مالٹا",
    "uz": "Malta",
    "ve": "Malta",
    "vi": "Moa-ta",
    "wa": "Male",
    "wo": "Malt",
    "xh": "Malta",
    "yo": "Máltà",
    "zh_CN": "马尔他",
    "zh_HK": "馬耳他",
    "zh_TW": "馬爾他",
    "zu": "IMalta"
  },
);
