import '../country.dart';

const countryNLD = Country(
  alpha2: 'NL',
  alpha3: 'NLD',
  continent: Continent.europe,
  countryCode: '31',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'NL',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 52.132633,
      longitude: 5.291265999999999,
    ),
    maxCoordinate: Coordinate(
      latitude: 53.6316,
      longitude: 7.227510199999999,
    ),
    minCoordinate: Coordinate(
      latitude: 50.75038379999999,
      longitude: 3.3316001,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 53.6316,
        longitude: 7.227510199999999,
      ),
      southwest: Coordinate(
        latitude: 50.75038379999999,
        longitude: 3.3316001,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'NED',
  isoLongName: 'The Kingdom of the Netherlands',
  isoShortName: 'Netherlands',
  isoShortNameLowerCase: 'Netherlands (the)',
  languagesOfficial: ['nl'],
  languagesSpoken: ['nl', 'fy'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '0',
  nationality: 'Dutch',
  number: '528',
  postalCode: true,
  postalCodeFormat: r'\d{4} ?[A-Z]{2}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Western Europe',
  unLocode: 'NL',
  unMember: true,
  unofficialNames: [
    'Netherlands',
    'The Netherlands',
    'Niederlande',
    'Pays-Bas',
    'Países Bajos',
    'オランダ',
    'Nederland',
    'Нидерландия'
  ],
  vehicleRegistrationCode: 'NL',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 21.0,
    reduced: [9.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Netherlands",
    "af": "Nederland",
    "ak": "Netherlands",
    "am": "ኔፈሴሒን፥",
    "an": "Netherlands",
    "ar": "هولندا",
    "as": "নেডাৰলেণ্ড",
    "ay": "Netherlands",
    "az": "Hollandiya",
    "ba": "Netherlands",
    "be": "Нідэрланды",
    "bg": "Холандия",
    "bi": "Netherlands",
    "bn": "নেদারল্যান্ড",
    "bn_IN": "নেদারল্যান্ড",
    "br": "Izelvroioù",
    "bs": "Nizozemska",
    "ca": "Països Baixos",
    "ce": "Нидерландаш",
    "ch": "Netherlands",
    "cs": "Nizozemsko",
    "cv": "Нидерландаш",
    "cy": "Yr Iseldiroedd",
    "da": "Holland",
    "de": "Niederlande",
    "dv": "ނެދަލޭންޑު",
    "dz": "ནེ་དར་ལེནཌིསི།",
    "ee": "Netherlands",
    "el": "Ολλανδία",
    "en": "Netherlands",
    "eo": "Nederlando",
    "es": "Países Bajos",
    "et": "Holland",
    "eu": "Herbehereak",
    "fa": "هلند",
    "ff": "Holannda",
    "fi": "Alankomaat",
    "fo": "Niðurlond",
    "fr": "Pays-Bas",
    "fy": "Nederlân",
    "ga": "An Ísiltír",
    "gl": "Países Baixos",
    "gn": "Netherlands",
    "gu": "નેધરલેન્ડ્સ",
    "gv": "Yn Çheer Injil",
    "ha": "Netherlands",
    "he": "הולנד",
    "hi": "नीदरलैण्ड",
    "hr": "Nizozemska",
    "ht": "Peyiba",
    "hu": "Hollandia",
    "hy": "Նիդերլանդեր",
    "ia": "Pais Basse",
    "id": "Belanda",
    "io": "Nederlando",
    "is": "Holland",
    "it": "Paesi Bassi",
    "iu": "Netherlands",
    "ja": "オランダ",
    "ka": "ნიდერლანდები",
    "ki": "Netherlands",
    "kk": "Нидерланды",
    "kl": "Netherlands",
    "km": "​ហូល្លង់",
    "kn": "ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್",
    "ko": "네덜란드",
    "ku": "Holanda",
    "kv": "Нидерландъяс",
    "kw": "Iseldiryow",
    "ky": "Нидерландтар",
    "lo": "ປະເທດໂຮນລັງ",
    "lt": "Nyderlandai",
    "lv": "Nīderlande",
    "mi": "Hōrana",
    "mk": "Холандија",
    "ml": "നെതര്‍ലന്‍ഡ്സ്",
    "mn": "Нидерланд",
    "mr": "नेदरलॅंडस्",
    "ms": "Belanda",
    "mt": "Netherlands",
    "my": "နယ်သာလန်နိုင်ငံ",
    "na": "Eben Eyong",
    "nb": "Nederland",
    "ne": "नेदरल्याण्ड",
    "nl": "Nederland",
    "nn": "Nederland",
    "nv": "Kéyah Wóyahgo Siʼánígíí",
    "oc": "Païses Basses",
    "or": "ନେଦରଲ୍ଯାଣ୍ଡ",
    "pa": "ਨੀਂਦਰਲੈਂਡ",
    "pi": "नेदरलैंड्स",
    "pl": "Holandia",
    "ps": "هالېنډ",
    "pt": "Países Baixos",
    "pt_BR": "Países Baixos",
    "ro": "Olanda",
    "ru": "Нидерланды",
    "rw": "Nederilande",
    "sc": "Paisos Bassos",
    "sd": "Netherlands",
    "si": "නෙදර්ලන්තය",
    "sk": "Holandsko",
    "sl": "Nizozemska",
    "so": "Netherlands",
    "sq": "Holandë",
    "sr": "Холандија",
    "sv": "Nederländerna",
    "sw": "Uholanzi",
    "ta": "நெதர்லாந்து",
    "te": "నేదర్లాండ్స్",
    "tg": "Нидерландия",
    "th": "เนเธอร์แลนด์",
    "ti": "ኔዘርላንድ",
    "tk": "Niderland",
    "tl": "Netherlands",
    "tr": "Hollanda",
    "tt": "Нидерландлар",
    "ug": "گوللاندىيە",
    "uk": "Нідерланди",
    "ur": "نیدرلینڈز",
    "uz": "Niderlandlar",
    "ve": "Netherlands",
    "vi": "Hoà Lan",
    "wa": "Bas Payis",
    "wo": "Olaand",
    "xh": "Netherlands",
    "yo": "Nẹ́dálándì",
    "zh_CN": "荷兰",
    "zh_HK": "荷蘭",
    "zh_TW": "荷蘭",
    "zu": "I-Netherlands"
  },
);
