import '../country.dart';

const countryNZL = Country(
  alpha2: 'NZ',
  alpha3: 'NZL',
  continent: Continent.australia,
  countryCode: '64',
  currencyCode: 'NZD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'NZ',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -40.900557,
      longitude: 174.885971,
    ),
    maxCoordinate: Coordinate(
      latitude: -28.8773225,
      longitude: -175.1235077,
    ),
    minCoordinate: Coordinate(
      latitude: -52.7224663,
      longitude: 165.7437641,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: -28.8773225,
        longitude: -175.1235077,
      ),
      southwest: Coordinate(
        latitude: -52.7224663,
        longitude: 165.7437641,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'NZL',
  isoLongName: 'New Zealand',
  isoShortName: 'New Zealand',
  isoShortNameLowerCase: null,
  languagesOfficial: ['en'],
  languagesSpoken: ['en'],
  nationalDestinationCodeLengths: [1],
  nationalNumberLengths: [8, 9],
  nationalPrefix: '0',
  nationality: 'New Zealander',
  number: '554',
  postalCode: true,
  postalCodeFormat: '\\d{4}',
  region: Region.oceania,
  startOfWeek: Week.monday,
  subregion: 'Australia and New Zealand',
  unLocode: 'NZ',
  unMember: true,
  unofficialNames: [
    'New Zealand',
    'Neuseeland',
    'Nouvelle Zélande',
    'Nueva Zelanda',
    'ニュージーランド',
    'Nieuw-Zeeland'
  ],
  vehicleRegistrationCode: 'NZ',
  worldRegion: WorldRegion.apac,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{region}}\n{{city}} {{postalcode}}\n{{country}}',
  vatRates: VatRates(
    standard: 15,
    reduced: [9],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'New Zealand',
    'af': 'Nieu-Seeland',
    'ak': 'New Zealand',
    'am': 'ኒፄ ፑሒን፥',
    'an': 'New Zealand',
    'ar': 'نيوزيلاندا',
    'as': 'নিউজিলেণ্ড',
    'ay': 'New Zealand',
    'az': 'Yeni Zellandiya',
    'ba': 'New Zealand',
    'be': 'Новая Зеландыя',
    'bg': 'Нова Зеландия',
    'bi': 'New Zealand',
    'bn': 'নিউজিল্যান্ড',
    'bn_IN': 'নিউজিল্যান্ড',
    'br': 'Zeland nevez',
    'bs': 'Novi Zeland',
    'ca': 'Nova Zelanda',
    'ce': 'Керла Зеланди',
    'ch': 'New Zealand',
    'cs': 'Nový Zéland',
    'cv': 'Керла Зеланди',
    'cy': 'Seland Newydd',
    'da': 'New Zealand',
    'de': 'Neuseeland',
    'dv': 'ނިއުޒިލޭންޑު',
    'dz': 'ནིའུ་ཛི་ལེནཌི།',
    'ee': 'New Zealand',
    'el': 'Νέα Ζηλανδία',
    'en': 'New Zealand',
    'eo': 'Nov-Zelando',
    'es': 'Nueva Zelanda',
    'et': 'Uus-Meremaa',
    'eu': 'Zeelanda Berria',
    'fa': 'نیوزیلند',
    'ff': 'New Zealand',
    'fi': 'Uusi-Seelanti',
    'fo': 'Ný Sæland',
    'fr': 'Nouvelle-Zélande',
    'fy': 'Nij-Seelân',
    'ga': 'An Nua-Shéalainn',
    'gl': 'Nova Celandia',
    'gn': 'New Zealand',
    'gu': 'ન્યુ ઝીલેન્ડ',
    'gv': 'Yn Teelynn Noa',
    'ha': 'New Zealand',
    'he': 'ניו זילנד',
    'hi': 'न्यूज़ीलैण्ड',
    'hr': 'Novi Zeland',
    'ht': 'Nouvèl Zelann',
    'hu': 'Új-Zéland',
    'hy': 'Նոր Զելանդիա',
    'ia': 'Nove Zelanda',
    'id': 'Selandia Baru',
    'io': 'Nova-Zelando',
    'is': 'Nýja-Sjáland',
    'it': 'Nuova Zelanda',
    'iu': 'New Zealand',
    'ja': 'ニュージーランド',
    'ka': 'ახალი ზელანდია',
    'ki': 'New Zealand',
    'kk': 'Жаңа Зеландия',
    'kl': 'New Zealand',
    'km': 'នូវែលហ្សេឡង់',
    'kn': 'ನ್ಯೂ ಜಿಲ್ಯಂಡ್',
    'ko': '뉴질랜드',
    'ku': 'Zelandaya Nû',
    'kv': 'Выль Зеландия',
    'kw': 'Mordir Nowydh',
    'ky': 'Жаңы Зеландия',
    'lo': 'ປະເທດນູແວນ ເຊລັງ',
    'lt': 'Naujoji Zelandija',
    'lv': 'Jaunzēlande',
    'mi': 'Aotearoa',
    'mk': 'Нов Зеланд',
    'ml': 'ന്യൂസിലാന്‍ഡ്',
    'mn': 'Шинэ зеланд',
    'mr': 'न्यूझिलंड',
    'ms': 'New Zealand',
    'mt': 'New Zealand',
    'my': 'နယူးဇီလန်နိုင်ငံ',
    'na': 'Niu Djiran',
    'nb': 'New Zealand',
    'ne': 'न्युजिल्याण्ड',
    'nl': 'Nieuw-Zeeland',
    'nn': 'New Zealand',
    'nv': 'New Zealand',
    'oc': 'Novèla Zelanda',
    'or': 'ନ୍ଯୁଜୀଲ୍ଯାଣ୍ଡ',
    'pa': 'ਨਿਊਜ਼ੀਲੈਂਡ',
    'pi': 'न्यू-जीलैंड',
    'pl': 'Nowa Zelandia',
    'ps': 'نیوزیلنډ',
    'pt': 'Nova Zelândia',
    'pt_BR': 'Nova Zelândia',
    'ro': 'Noua Zeelandă',
    'ru': 'Новая Зеландия',
    'rw': 'Nuveli Zelande',
    'sc': 'Zelanda Noa',
    'sd': 'New Zealand',
    'si': 'නවසීලන්තය',
    'sk': 'Nový Zéland',
    'sl': 'Nova Zelandija',
    'so': 'Neyuusilaand',
    'sq': 'Zelandë e Re',
    'sr': 'Нови Зеланд',
    'sv': 'Nya Zeeland',
    'sw': 'New Zealand',
    'ta': 'நியூசிலாந்து',
    'te': 'న్యూజిలాండ్',
    'tg': 'Зеландияи Нав',
    'th': 'นิวซีแลนด์',
    'ti': 'ኒው ዚላንድ',
    'tk': 'Täze Zelandiýa',
    'tl': 'New Zealand',
    'tr': 'Yeni Zelanda',
    'tt': 'Яңа Зеаланд',
    'ug': 'يېڭى زېلاندىيە',
    'uk': 'Нова Зеландія',
    'ur': 'نیوزی لینڈ',
    'uz': 'Yangi Zelandiya',
    've': 'New Zealand',
    'vi': 'Niu Xi-lân',
    'wa': 'Nouve Zelande',
    'wo': 'Nuweel Selaand',
    'xh': 'New Zealand (izealand entsha)',
    'yo': 'New Zealand',
    'zh_CN': '新西兰',
    'zh_HK': '新西蘭',
    'zh_TW': '紐西蘭',
    'zu': 'INyuzilandi'
  },
);
