import '../country.dart';

const countryPHL = Country(
  alpha2: 'PH',
  alpha3: 'PHL',
  continent: Continent.asia,
  countryCode: '63',
  currencyCode: 'PHP',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'RP',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 12.879721,
      longitude: 121.774017,
    ),
    maxCoordinate: Coordinate(
      latitude: 21.2412572,
      longitude: 127.6444784,
    ),
    minCoordinate: Coordinate(
      latitude: 4.2259,
      longitude: 116.1474999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 21.2412572,
        longitude: 127.6444784,
      ),
      southwest: Coordinate(
        latitude: 4.2259,
        longitude: 116.1474999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'PHI',
  isoLongName: 'The Republic of the Philippines',
  isoShortName: 'Philippines',
  isoShortNameLowerCase: 'Philippines (the)',
  languagesOfficial: ['tl', 'en'],
  languagesSpoken: ['tl', 'en'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9, 10],
  nationalPrefix: '0',
  nationality: 'Filipino',
  number: '608',
  postalCode: true,
  postalCodeFormat: r'\d{4}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'South-Eastern Asia',
  unLocode: 'PH',
  unMember: true,
  unofficialNames: [
    'Philippines',
    'Philippinen',
    'Filipinas',
    'フィリピン',
    'Filipijnen'
  ],
  vehicleRegistrationCode: 'RP',
  worldRegion: WorldRegion.apac,
  addressFormat: '''{{recipient}}
{{street}} {{region_short}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 12.0,
    reduced: [],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Philippines",
    "af": "Filippyne",
    "ak": "Philippines",
    "am": "ፊሊፒንስ",
    "an": "Philippines",
    "ar": "الفلبّين",
    "as": "ফিলিপাইনছ",
    "ay": "Philippines",
    "az": "Filippin",
    "ba": "Philippines",
    "be": "Філіпіны",
    "bg": "Филипини",
    "bi": "Philippines",
    "bn": "ফিলিপাইনস",
    "bn_IN": "ফিলিপাইনস",
    "br": "Filipinez",
    "bs": "Filipini",
    "ca": "Filipines",
    "ce": "Филиппин",
    "ch": "Filipinas",
    "cs": "Filipíny",
    "cv": "Филиппин",
    "cy": "Pilipinas",
    "da": "Filippinerne",
    "de": "Philippinen",
    "dv": "ފިލިޕީންސް",
    "dz": "ཕི་ལི་པིནསི།",
    "ee": "Philippines",
    "el": "Φιλιππίνες",
    "en": "Philippines",
    "eo": "Filipinoj",
    "es": "Filipinas",
    "et": "Filipiinid",
    "eu": "Filipinak",
    "fa": "فیلیپین",
    "ff": "Philippines",
    "fi": "Filippiinit",
    "fo": "Filipsoyggjar",
    "fr": "Philippines",
    "fy": "Filipinen",
    "ga": "Na hOileáin Fhilipíneacha",
    "gl": "Filipinas",
    "gn": "Philippines",
    "gu": "ફિલિપાઇન્સ",
    "gv": "Ny h-Ellanyn Philippeenagh",
    "ha": "Filipin",
    "he": "הפיליפינים",
    "hi": "फ़िलीपीन्स",
    "hr": "Filipini",
    "ht": "Filipin",
    "hu": "Fülöp-szigetek",
    "hy": "Ֆիլիպիններ",
    "ia": "Philippinas",
    "id": "Filipina",
    "io": "Filipini",
    "is": "Filippseyjar",
    "it": "Filippine",
    "iu": "Philippines",
    "ja": "フィリピン",
    "ka": "ფილიპინები",
    "ki": "Philippines",
    "kk": "Филиппин",
    "kl": "Philippines",
    "km": "ហ្វីលីពីន",
    "kn": "ಫಿಲಿಪ್ಪೈನ್ಸ್",
    "ko": "필리핀",
    "ku": "Fîlîpîn",
    "kv": "Филиппинъяс",
    "kw": "Filipinys",
    "ky": "Филиппиндер",
    "lo": "ປະເທດຟີລິບປິນ",
    "lt": "Filipinai",
    "lv": "Filipīnas",
    "mi": "Piripīni",
    "mk": "Филипини",
    "ml": "ഫിലിപ്പൈന്‍സ്",
    "mn": "Флиппен",
    "mr": "फिलिपिन्स",
    "ms": "Filipina",
    "mt": "Filippini",
    "my": "ဖိလစ်ပိုင်နိုင်ငံ",
    "na": "Eben Piripin",
    "nb": "Filippinene",
    "ne": "फिलिपिन्स",
    "nl": "Filipijnen",
    "nn": "Filippinane",
    "nv": "Kéyah Dańlíinii",
    "oc": "Filipinas",
    "or": "ଫିଲିପାଇନ୍ସ",
    "pa": "ਫਿਲਿਪੀਨੀਜ਼",
    "pi": "फिलिपीन्स",
    "pl": "Filipiny",
    "ps": "فلېپين",
    "pt": "Filipinas",
    "pt_BR": "Filipinas",
    "ro": "Filipine",
    "ru": "Филиппины",
    "rw": "Filipine",
    "sc": "Filipinas",
    "sd": "Philippines",
    "si": "පිලිපීන",
    "sk": "Filipíny",
    "sl": "Filipini",
    "so": "Filibiin",
    "sq": "Filipine",
    "sr": "Филипини",
    "sv": "Filippinerna",
    "sw": "Philippines",
    "ta": "பிலிப்பைன்ஸ்",
    "te": "ఫిలిప్పిన్స్",
    "tg": "Филиппинҳо",
    "th": "ฟิลิปปินส์",
    "ti": "Philippines",
    "tk": "Filippin adalary",
    "tl": "Pilipinas",
    "tr": "Filipinler",
    "tt": "Филиппиннәр",
    "ug": "فىلىپپىن",
    "uk": "Філіппіни",
    "ur": "فلپائن",
    "uz": "Filippin",
    "ve": "Philippines",
    "vi": "Phi-li-pi-nợ",
    "wa": "Filipenes",
    "wo": "Filipiin",
    "xh": "Philippines",
    "yo": "Filipínì",
    "zh_CN": "菲律宾",
    "zh_HK": "菲律賓",
    "zh_TW": "菲律賓",
    "zu": "Philippines"
  },
);
