import '../country.dart';

const countryPRT = Country(
  alpha2: 'PT',
  alpha3: 'PRT',
  continent: Continent.europe,
  countryCode: '351',
  currencyCode: 'EUR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'PO',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 39.39987199999999,
      longitude: -8.224454,
    ),
    maxCoordinate: Coordinate(
      latitude: 42.1543111,
      longitude: -6.189159200000001,
    ),
    minCoordinate: Coordinate(
      latitude: 32.2895,
      longitude: -31.4647999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 42.1543111,
        longitude: -6.189159200000001,
      ),
      southwest: Coordinate(
        latitude: 32.2895,
        longitude: -31.4647999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'POR',
  isoLongName: 'The Portuguese Republic',
  isoShortName: 'Portugal',
  isoShortNameLowerCase: null,
  languagesOfficial: ['pt'],
  languagesSpoken: ['pt'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: 'None',
  nationality: 'Portuguese',
  number: '620',
  postalCode: true,
  postalCodeFormat: '\\d{4}-\\d{3}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Southern Europe',
  unLocode: 'PT',
  unMember: true,
  unofficialNames: ['Portugal', 'ポルトガル'],
  vehicleRegistrationCode: 'P',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}} {{region_short}}\n{{country}}',
  vatRates: VatRates(
    standard: 23,
    reduced: [6, 13],
    superReduced: null,
    parking: 13,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Portugal',
    'af': 'Portugal',
    'ak': 'Portugal',
    'am': 'ፖርቱጋል',
    'an': 'Portugal',
    'ar': 'البرتغال',
    'as': 'পোর্টুগাল',
    'ay': 'Portugal',
    'az': 'Portuqaliya',
    'ba': 'Portugal',
    'be': 'Партугалія',
    'bg': 'Португалия',
    'bi': 'Portugal',
    'bn': 'পোর্টুগাল',
    'bn_IN': 'পোর্টুগাল',
    'br': 'Portugal',
    'bs': 'Portugal',
    'ca': 'Portugal',
    'ce': 'Португали',
    'ch': 'Portugal',
    'cs': 'Portugalsko',
    'cv': 'Португали',
    'cy': 'Portiwgal',
    'da': 'Portugal',
    'de': 'Portugal',
    'dv': 'ޕޯޗުގަލް',
    'dz': 'པོར་ཊུ་གཱལ།',
    'ee': 'Portugal',
    'el': 'Πορτογαλία',
    'en': 'Portugal',
    'eo': 'Portugalio',
    'es': 'Portugal',
    'et': 'Portugal',
    'eu': 'Portugal',
    'fa': 'پرتغال',
    'ff': 'Portokeesi',
    'fi': 'Portugali',
    'fo': 'Portugal',
    'fr': 'Portugal',
    'fy': 'Portegal',
    'ga': 'An Phortaingéil',
    'gl': 'Portugal',
    'gn': 'Portugal',
    'gu': 'પોર્ટુગલ',
    'gv': 'Yn Phortiugal',
    'ha': 'Portugal',
    'he': 'פורטוגל',
    'hi': 'पुर्तगाल',
    'hr': 'Portugal',
    'ht': 'Pòtigal',
    'hu': 'Portugália',
    'hy': 'Պորտուգալիա',
    'ia': 'Portugal',
    'id': 'Portugal',
    'io': 'Portugal',
    'is': 'Portúgal',
    'it': 'Portogallo',
    'iu': 'Portugal',
    'ja': 'ポルトガル',
    'ka': 'პორტუგალია',
    'ki': 'Portugal',
    'kk': 'Португалия',
    'kl': 'Portugal',
    'km': 'ព័រទុយហ្គាល់',
    'kn': 'ಪೋರ್ತುಗಾಲ್',
    'ko': '포르투갈',
    'ku': 'Portekîz',
    'kv': 'Португалия',
    'kw': 'Portyngal',
    'ky': 'Португалия',
    'lo': 'ປະເທດປອກຕຸຍການ',
    'lt': 'Portugalija',
    'lv': 'Portugāle',
    'mi': 'Potukara',
    'mk': 'Португалија',
    'ml': 'പോര്‍ച്ചുഗല്‍',
    'mn': 'Португаль',
    'mr': 'पोर्तुगाल',
    'ms': 'Feringgi',
    'mt': 'Portugall',
    'my': 'ပေါ်တူဂီနိုင်ငံ',
    'na': 'Portsiugar',
    'nb': 'Portugal',
    'ne': 'पोर्चुगल',
    'nl': 'Portugal',
    'nn': 'Portugal',
    'nv': 'Portugal',
    'oc': 'Portugal',
    'or': 'ପର୍ତୁଗାଲ',
    'pa': 'ਪੁਰਤਗਾਲ',
    'pi': 'पुर्तगाल',
    'pl': 'Portugalia',
    'ps': 'پورتګال',
    'pt': 'Portugal',
    'pt_BR': 'Portugal',
    'ro': 'Portugalia',
    'ru': 'Португалия',
    'rw': 'Porutigali',
    'sc': 'Portugallu',
    'sd': 'پرتگال',
    'si': 'පෘතුගාලය',
    'sk': 'Portugalsko',
    'sl': 'Portugalska',
    'so': 'Bortuqaal',
    'sq': 'Portugali',
    'sr': 'Португал',
    'sv': 'Portugal',
    'sw': 'Portugal',
    'ta': 'போர்ச்சுகல்',
    'te': 'పోర్చుగల్',
    'tg': 'Португалия',
    'th': 'โปรตุเกส',
    'ti': 'ፖርቱጋል',
    'tk': 'Portugaliýa',
    'tl': 'Portugal',
    'tr': 'Portekiz',
    'tt': 'Портуgалиа',
    'ug': 'پورتۇگالىيە',
    'uk': 'Португалія',
    'ur': 'پرتگال',
    'uz': 'Portugaliya',
    've': 'Portugal',
    'vi': 'Bồ Đào Nha',
    'wa': 'Portugal',
    'wo': 'Portugaal',
    'xh': 'Portugal',
    'yo': 'Pọ́rtúgàl',
    'zh_CN': '葡萄牙',
    'zh_HK': '葡萄牙',
    'zh_TW': '葡萄牙',
    'zu': 'IPhothugali'
  },
);
