import '../country.dart';

const countryROU = Country(
  alpha2: 'RO',
  alpha3: 'ROU',
  continent: Continent.europe,
  countryCode: '40',
  currencyCode: 'RON',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'RO',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 45.943161,
      longitude: 24.96676,
    ),
    maxCoordinate: Coordinate(
      latitude: 48.26518,
      longitude: 29.77839999999999,
    ),
    minCoordinate: Coordinate(
      latitude: 43.6186193,
      longitude: 20.2617591,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 48.26518,
        longitude: 29.77839999999999,
      ),
      southwest: Coordinate(
        latitude: 43.6186193,
        longitude: 20.2617591,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ROU',
  isoLongName: 'Romania',
  isoShortName: 'Romania',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ro'],
  languagesSpoken: ['ro'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '0',
  nationality: 'Romanian',
  number: '642',
  postalCode: true,
  postalCodeFormat: r'\d{6}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Eastern Europe',
  unLocode: 'RO',
  unMember: true,
  unofficialNames: [
    'Romania',
    'Rumänien',
    'Roumanie',
    'Rumania',
    'ルーマニア',
    'Roemenië'
  ],
  vehicleRegistrationCode: 'RO',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{street}}
{{postalcode}} {{city}}
{{country}}''',
  vatRates: VatRates(
    standard: 21.0,
    reduced: [11.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: true,
  euMember: true,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Romania",
    "af": "Roemenië",
    "ak": "Romania",
    "am": "ስሣኒ።",
    "an": "Romania",
    "ar": "رومانيا",
    "as": "ৰোমানিয়া",
    "ay": "Romania",
    "az": "Ruminıya",
    "ba": "Romania",
    "be": "Румынія",
    "bg": "Румъния",
    "bi": "Romania",
    "bn": "রোমানিয়া",
    "bn_IN": "রোমানিয়া",
    "br": "Roumania",
    "bs": "Rumunija",
    "ca": "Romania",
    "ce": "Румыни",
    "ch": "Romania",
    "cs": "Rumunsko",
    "cv": "Румыни",
    "cy": "Rwmania",
    "da": "Rumænien",
    "de": "Rumänien",
    "dv": "ރުމޭނިއާ",
    "dz": "རོ་མ་ནི་ཡ།",
    "ee": "Romania",
    "el": "Ρουμανία",
    "en": "Romania",
    "eo": "Rumanio",
    "es": "Rumanía",
    "et": "Rumeenia",
    "eu": "Errumania",
    "fa": "رومانی",
    "ff": "Romaniya",
    "fi": "Romania",
    "fo": "Rumenia",
    "fr": "Roumanie",
    "fy": "Roemeenje",
    "ga": "An Rómáin",
    "gl": "Romanía",
    "gn": "Romania",
    "gu": "રોમાનિયા",
    "gv": "Yn Romaan",
    "ha": "Romainiya",
    "he": "רומניה",
    "hi": "रोमानिया",
    "hr": "Rumunjska",
    "ht": "Woumani",
    "hu": "Románia",
    "hy": "Ռումինիա",
    "ia": "Romania",
    "id": "Rumania",
    "io": "Rumania",
    "is": "Rúmenía",
    "it": "Romania",
    "iu": "Romania",
    "ja": "ルーマニア",
    "ka": "რუმინეთი",
    "ki": "Romania",
    "kk": "Румыния",
    "kl": "Romania",
    "km": "រូម៉ានី",
    "kn": "ರೊಮೇನಿಯಾ",
    "ko": "루마니아",
    "ku": "Romanya",
    "kv": "Румыния",
    "kw": "Roumani",
    "ky": "Румыния",
    "lo": "ປະເທດລູມານີ",
    "lt": "Rumunija",
    "lv": "Rumānija",
    "mi": "Romeinia",
    "mk": "Романија",
    "ml": "റൊമാനിയ",
    "mn": "Румын",
    "mr": "रोमानिया",
    "ms": "Romania",
    "mt": "Rumanija",
    "my": "ရိုမေးနီးယားနိုင်ငံ",
    "na": "Romania",
    "nb": "Romania",
    "ne": "रोमानिया",
    "nl": "Roemenië",
    "nn": "Romania",
    "nv": "Wooméiniya",
    "oc": "Romania",
    "or": "ରୋମାନିୟା",
    "pa": "ਰੋਮਾਨੀਆ",
    "pi": "रोमानिया",
    "pl": "Rumunia",
    "ps": "رومانیا",
    "pt": "Roménia",
    "pt_BR": "Romênia",
    "ro": "România",
    "ru": "Румыния",
    "rw": "Romaniya",
    "sc": "Romania",
    "sd": "Romania",
    "si": "රොමේනියාව",
    "sk": "Rumunsko",
    "sl": "Romunija",
    "so": "Rumaaniya",
    "sq": "Rumani",
    "sr": "Румунија",
    "sv": "Rumänien",
    "sw": "Romania",
    "ta": "ரோமானியா",
    "te": "రోమానియా",
    "tg": "Руминия",
    "th": "โรมาเนีย",
    "ti": "ሮሜኒያ",
    "tk": "Rumyniýa",
    "tl": "Romania",
    "tr": "Romanya",
    "tt": "Романиа",
    "ug": "رۇمىنىيە",
    "uk": "Румунія",
    "ur": "رومانیہ",
    "uz": "Ruminiya",
    "ve": "Romania",
    "vi": "Rô-ma-ni",
    "wa": "Roumaneye",
    "wo": "Romaani",
    "xh": "Romania",
    "yo": "Románíà",
    "zh_CN": "罗马尼亚",
    "zh_HK": "羅馬尼亞",
    "zh_TW": "羅馬尼亞",
    "zu": "I-Romaniya"
  },
);
