import '../country.dart';

const countryRUS = Country(
  alpha2: 'RU',
  alpha3: 'RUS',
  continent: Continent.europe,
  countryCode: '7',
  currencyCode: 'RUB',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'RS',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 61.52401,
      longitude: 105.318756,
    ),
    maxCoordinate: Coordinate(
      latitude: 82.1673907,
      longitude: -168.97788,
    ),
    minCoordinate: Coordinate(
      latitude: 41.185353,
      longitude: 19.6160999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 82.1673907,
        longitude: -168.97788,
      ),
      southwest: Coordinate(
        latitude: 41.185353,
        longitude: 19.6160999,
      ),
    ),
  ),
  internationalPrefix: '810',
  ioc: 'RUS',
  isoLongName: 'The Russian Federation',
  isoShortName: 'Russian Federation',
  isoShortNameLowerCase: 'Russian Federation (the)',
  languagesOfficial: ['ru'],
  languagesSpoken: ['ru'],
  nationalDestinationCodeLengths: [3],
  nationalNumberLengths: [10],
  nationalPrefix: '8',
  nationality: 'Russian',
  number: '643',
  postalCode: true,
  postalCodeFormat: r'\d{6}',
  region: Region.europe,
  startOfWeek: Week.monday,
  subregion: 'Eastern Europe',
  unLocode: 'RU',
  unMember: true,
  unofficialNames: [
    'Russia',
    'Russian Federation',
    'Russland',
    'Russie',
    'Rusia',
    'ロシア連邦',
    'Rusland',
    'Россия',
    'Расія'
  ],
  vehicleRegistrationCode: 'RUS',
  worldRegion: WorldRegion.emea,
  addressFormat: '''{{recipient}}
{{postalcode}} {{city}}
{{street}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: true,
  isoShortNameByLocale: {
    "ab": "Russian Federation",
    "af": "Russiese Federasie",
    "ak": "Russian Federation",
    "am": "ሲቁ።",
    "an": "Russian Federation",
    "ar": "الاتّحاد الرّوسي",
    "as": "ৰুচ যুক্তৰাষ্ট্ৰ",
    "ay": "Russian Federation",
    "az": "Rusiya Federasiyası",
    "ba": "Russian Federation",
    "be": "Расійская Федэрацыя",
    "bg": "Руска федерация",
    "bi": "Russian Federation",
    "bn": "রুশ যুক্তরাষ্ট্র",
    "bn_IN": "রুশ যুক্তরাষ্ট্র",
    "br": "Russian Federation",
    "bs": "Ruska Federacija",
    "ca": "Federació Russa",
    "ce": "Russian Federation",
    "ch": "Russian Federation",
    "cs": "Ruská federace",
    "cv": "Russian Federation",
    "cy": "Ffederasiwn Rwsia",
    "da": "Russiske føderation",
    "de": "Russische Föderation",
    "dv": "Russian Federation",
    "dz": "ར་ཤི་ཡཱན་ ཕེ་ཌི་རེ་ཤཱན།",
    "ee": "Russian Federation",
    "el": "Ρωσική Ομοσπονδία",
    "en": "Russian Federation",
    "eo": "Rusa Federacio",
    "es": "Federación Rusa",
    "et": "Venemaa Föderatsioon",
    "eu": "Errusiar Federakundea",
    "fa": "روسیه فدرال",
    "ff": "Russian Federation",
    "fi": "Venäjän federaatio",
    "fo": "Russian Federation",
    "fr": "Russie, Fédération de",
    "fy": "Russian Federation",
    "ga": "Cónaidhm na Rúise",
    "gl": "Federación Rusa",
    "gn": "Russian Federation",
    "gu": "રશિયન ફેડરેશન",
    "gv": "Russian Federation",
    "ha": "Russian Federation",
    "he": "הפדרציה הרוסית",
    "hi": "रशियन फेडेरशन",
    "hr": "Ruska Federacija",
    "ht": "Russian Federation",
    "hu": "Orosz Föderáció",
    "hy": "Ռուսաստանի Դաշնություն",
    "ia": "Federation Russe",
    "id": "Federasi Rusia",
    "io": "Russian Federation",
    "is": "Rússneska sambandið",
    "it": "Russia",
    "iu": "Russian Federation",
    "ja": "ロシア連邦",
    "ka": "რუსეთის ფედრაცია",
    "ki": "Russian Federation",
    "kk": "Ресей",
    "kl": "Russian Federation",
    "km": "សហព័ន្ធ​រុស្ស៊ី",
    "kn": "ರಶಿಯನ್ ಒಕ್ಕೂಟ",
    "ko": "러시아 연방",
    "ku": "Federasyona Rûsî",
    "kv": "Russian Federation",
    "kw": "Russian Federation",
    "ky": "Орус Федерациясы",
    "lo": "Russian Federation",
    "lt": "Rusijos Federacija",
    "lv": "Krievijas Federācija",
    "mi": "Russian Federation",
    "mk": "Руска федерација",
    "ml": "റഷ്യന്‍ ഫെഡറേഷന്‍",
    "mn": "Оросын холбооны улс",
    "mr": "रशियन संघराज्य",
    "ms": "Russian Federation",
    "mt": "Russian Federation",
    "my": "Russian Federation",
    "na": "Russian Federation",
    "nb": "Den russiske føderasjon",
    "ne": "रसियन संघ",
    "nl": "Rusland",
    "nn": "Russland",
    "nv": "Russian Federation",
    "oc": "Federacion russa",
    "or": "ଋଷୀ ଫେଡରେଶନ",
    "pa": "ਰੂਸੀ ਗਣਰਾਜ",
    "pi": "Russian Federation",
    "pl": "Federacja Rosyjska",
    "ps": "Russian Federation",
    "pt": "Federação Russa",
    "pt_BR": "Federação Russa",
    "ro": "Federația Rusă",
    "ru": "Российская Федерация",
    "rw": "Ukwishyirahamwe kw'Uburusiya",
    "sc": "Federatzione Russa",
    "sd": "Russian Federation",
    "si": "රුසියානු සංගමය",
    "sk": "Ruská federácia",
    "sl": "Ruska federacija",
    "so": "Ruush",
    "sq": "Federata Ruse",
    "sr": "Руска Федерација",
    "sv": "Ryssland",
    "sw": "Russian Federation",
    "ta": "ரஷ்யன் கூட்டமைப்பு",
    "te": "రష్యన్ ఫెడరేషన్",
    "tg": "Федератсияи Россия",
    "th": "สหพันธรัฐรัสเซีย",
    "ti": "Russian Federation",
    "tk": "Russiýa federasiýasy",
    "tl": "Pederasyong Ruso",
    "tr": "Rusya Federasyonu",
    "tt": "Урыс Патшаһлык",
    "ug": "رۇسىيە فېدېراتسىيەسى",
    "uk": "Російська Федерація",
    "ur": "Russian Federation",
    "uz": "Russian Federation",
    "ve": "Russian Federation",
    "vi": "Liên Bang Nga",
    "wa": "Rûsseye",
    "wo": "Federaasioŋ bu Riisi",
    "xh": "Russian Federation",
    "yo": "Russian Federation",
    "zh_CN": "俄罗斯",
    "zh_HK": "俄羅斯聯邦",
    "zh_TW": "俄羅斯聯邦",
    "zu": "Russian Federation"
  },
);
