import '../country.dart';

const countrySLV = Country(
  alpha2: 'SV',
  alpha3: 'SLV',
  continent: Continent.northAmerica,
  countryCode: '503',
  currencyCode: 'USD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'ES',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 13.794185,
      longitude: -88.89653,
    ),
    maxCoordinate: Coordinate(
      latitude: 14.4505567,
      longitude: -87.6682,
    ),
    minCoordinate: Coordinate(
      latitude: 13.0473999,
      longitude: -90.19229999999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 14.4505567,
        longitude: -87.6682,
      ),
      southwest: Coordinate(
        latitude: 13.0473999,
        longitude: -90.19229999999999,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ESA',
  isoLongName: 'The Republic of El Salvador',
  isoShortName: 'El Salvador',
  isoShortNameLowerCase: null,
  languagesOfficial: ['es'],
  languagesSpoken: ['es'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Salvadoran',
  number: '222',
  postalCode: true,
  postalCodeFormat: r'CP [1-3][1-7][0-2]\d',
  region: Region.americas,
  startOfWeek: Week.monday,
  subregion: 'Central America',
  unLocode: 'SV',
  unMember: true,
  unofficialNames: ['El Salvador', 'Salvador', 'エルサルバドル'],
  vehicleRegistrationCode: 'ES',
  worldRegion: WorldRegion.amer,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "El Salvador",
    "af": "El Salvador",
    "ak": "El Salvador",
    "am": "ኤል ሳልቫዶር",
    "an": "El Salvador",
    "ar": "السّلفادور",
    "as": "এল ছেলভেড'ৰ",
    "ay": "El Salvador",
    "az": "Elsalvador",
    "ba": "El Salvador",
    "be": "Эль-Сальвадор",
    "bg": "Ел Салвадор",
    "bi": "El Salvador",
    "bn": "এল সালভাডোর",
    "bn_IN": "এল সালভাডোর",
    "br": "Salvador",
    "bs": "El Salvador",
    "ca": "El Salvador",
    "ce": "Сальвадор",
    "ch": "El Salvador",
    "cs": "Salvador",
    "cv": "Сальвадор",
    "cy": "El Salvador",
    "da": "El Salvador",
    "de": "El Salvador",
    "dv": "އެލްސެލްވަޑޯރު",
    "dz": "ཨེལ་ སཱལ་བེ་ཌོར།",
    "ee": "El Salvador",
    "el": "Ελ Σαλβαδόρ",
    "en": "El Salvador",
    "eo": "Salvadoro",
    "es": "El Salvador",
    "et": "El Salvador",
    "eu": "El Salvador",
    "fa": "السالوادور",
    "ff": "El Salvador",
    "fi": "El Salvador",
    "fo": "El Salvador",
    "fr": "Salvador",
    "fy": "El Salvador",
    "ga": "An tSalvadóir",
    "gl": "O Salvador",
    "gn": "El Salvador",
    "gu": "અલ સાલ્વાડોર",
    "gv": "Yn Salvador",
    "ha": "El Salvador",
    "he": "אל סלוודור",
    "hi": "अल साल्वाडोर",
    "hr": "Salvador",
    "ht": "Salvadò",
    "hu": "El Salvador",
    "hy": "Սալվադոր",
    "ia": "El Salvador",
    "id": "El Salvador",
    "io": "Salvador",
    "is": "El Salvador",
    "it": "El Salvador",
    "iu": "El Salvador",
    "ja": "エルサルバドル",
    "ka": "სალვადორი",
    "ki": "El Salvador",
    "kk": "Сальвадор",
    "kl": "El Salvador",
    "km": "អែលសាល់វ៉ាឌ័រ",
    "kn": "ಎಲ್ ಸಾಲ್ವಡಾರ್‍",
    "ko": "엘살바도르",
    "ku": "El Salvador",
    "kv": "Сальвадор",
    "kw": "El Salvador",
    "ky": "Сальвадор",
    "lo": "El Salvador",
    "lt": "Salvadoras",
    "lv": "Salvadora",
    "mi": "El Salvador",
    "mk": "Ел Салвадор",
    "ml": "എല്‍ സാല്‍വഡോര്‍",
    "mn": "Эл салвадор",
    "mr": "अल साल्वॅडॉर",
    "ms": "El Salvador",
    "mt": "El Salvador",
    "my": "အယ်ဆာဗေဒိုနိုင်ငံ",
    "na": "Ersarbador",
    "nb": "El Salvador",
    "ne": "इल साल्भाडोर",
    "nl": "El Salvador",
    "nn": "El Salvador",
    "nv": "El Salvador",
    "oc": "El Salvador",
    "or": "ଅଲ ସଲ୍ଭାଡୋର",
    "pa": "ਈਲ ਸਾਲੇਵਡੋਰ",
    "pi": "एल-साल्वाडोर",
    "pl": "Salwador",
    "ps": "سالوېډور",
    "pt": "El Salvador",
    "pt_BR": "El Salvador",
    "ro": "El Salvador",
    "ru": "Сальвадор",
    "rw": "Eli Saluvadoro",
    "sc": "El Salvador",
    "sd": "El Salvador",
    "si": "එල් සැල්වදෝරය",
    "sk": "Salvádor",
    "sl": "Salvador",
    "so": "El Salvador",
    "sq": "Salvador",
    "sr": "Ел Салвадор",
    "sv": "El Salvador",
    "sw": "El Salvador",
    "ta": "எல் சால்வடார்",
    "te": "అల సాల్వడార్",
    "tg": "Ал-Салвадор",
    "th": "เอลซัลวาดอร์",
    "ti": "ኤል ሳልቫዶር",
    "tk": "Salwador",
    "tl": "El Salvador",
    "tr": "El Salvador",
    "tt": "Ел Салвадор",
    "ug": "سالۋادور",
    "uk": "Сальвадор",
    "ur": "ایل سیلواڈور",
    "uz": "El Salvador",
    "ve": "El Salvador",
    "vi": "En-xan-va-đoa",
    "wa": "El Salvador",
    "wo": "Salbadoor",
    "xh": "El Salvador",
    "yo": "El Salfador",
    "zh_CN": "萨尔瓦多",
    "zh_HK": "薩爾瓦多",
    "zh_TW": "薩爾瓦多",
    "zu": "El Salvador"
  },
);
