import '../country.dart';

const countrySOM = Country(
  alpha2: 'SO',
  alpha3: 'SOM',
  continent: Continent.africa,
  countryCode: '252',
  currencyCode: 'SOS',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'SO',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 5.152149,
      longitude: 46.199616,
    ),
    maxCoordinate: Coordinate(
      latitude: 12.3615,
      longitude: 51.6138,
    ),
    minCoordinate: Coordinate(
      latitude: -1.8673,
      longitude: 40.994373,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 12.3615,
        longitude: 51.6138,
      ),
      southwest: Coordinate(
        latitude: -1.8673,
        longitude: 40.994373,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'SOM',
  isoLongName: 'The Federal Republic of Somalia',
  isoShortName: 'Somalia',
  isoShortNameLowerCase: null,
  languagesOfficial: ['so', 'ar'],
  languagesSpoken: ['so', 'ar'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8],
  nationalPrefix: 'None',
  nationality: 'Somali',
  number: '706',
  postalCode: true,
  postalCodeFormat: '[A-Z]{2} ?\\d{5}',
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Eastern Africa',
  unLocode: 'SO',
  unMember: true,
  unofficialNames: ['Somalia', 'الصومال', 'ソマリア', 'Somalië'],
  vehicleRegistrationCode: 'SO',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Somalia',
    'af': 'Somalië',
    'ak': 'Somalia',
    'am': 'ሱሢሓ',
    'an': 'Somalia',
    'ar': 'الصومال',
    'as': 'ছোমালিয়া',
    'ay': 'Somalia',
    'az': 'Somali',
    'ba': 'Somalia',
    'be': 'Самалі',
    'bg': 'Сомалия',
    'bi': 'Somalia',
    'bn': 'সোমালিয়া',
    'bn_IN': 'সোমালিয়া',
    'br': 'Somalia',
    'bs': 'Somalija',
    'ca': 'Somàlia',
    'ce': 'Сомали',
    'ch': 'Somalia',
    'cs': 'Somálsko',
    'cv': 'Сомали',
    'cy': 'Somalia',
    'da': 'Somalia',
    'de': 'Somalia',
    'dv': 'ސޯމާލިއާ',
    'dz': 'སོ་མ་ལི་ཡ།',
    'ee': 'Somalia',
    'el': 'Σομαλία',
    'en': 'Somalia',
    'eo': 'Somalio',
    'es': 'Somalia',
    'et': 'Somaalia',
    'eu': 'Somalia',
    'fa': 'سومالی',
    'ff': 'Somaaliya',
    'fi': 'Somalia',
    'fo': 'Somalia',
    'fr': 'Somalie',
    'fy': 'Somaalje',
    'ga': 'An tSomáil',
    'gl': 'Somalia',
    'gn': 'Somalia',
    'gu': 'સોમાલિયા',
    'gv': 'Yn Tomaal',
    'ha': 'Somaliya',
    'he': 'סומליה',
    'hi': 'सोमालिया',
    'hr': 'Somalija',
    'ht': 'Somali',
    'hu': 'Szomália',
    'hy': 'Սոմալի',
    'ia': 'Somalia',
    'id': 'Somalia',
    'io': 'Somalia',
    'is': 'Sómalía',
    'it': 'Somalia',
    'iu': 'Somalia',
    'ja': 'ソマリア',
    'ka': 'სომალი',
    'ki': 'Somalia',
    'kk': 'Сомали',
    'kl': 'Somalia',
    'km': 'សូម៉ាលី',
    'kn': 'ಸೋಮಾಲಿಯಾ',
    'ko': '소말리아',
    'ku': 'Somalî',
    'kv': 'Somalia',
    'kw': 'Somali',
    'ky': 'Сомали',
    'lo': 'Somalia',
    'lt': 'Somalis',
    'lv': 'Somālija',
    'mi': 'Somalia',
    'mk': 'Сомалија',
    'ml': 'സോമാലിയ',
    'mn': 'Сомали',
    'mr': 'सोमालिया',
    'ms': 'Somalia',
    'mt': 'Somalja',
    'my': 'ဆိုမာလီယာနိုင်ငံ',
    'na': 'Tomariya',
    'nb': 'Somalia',
    'ne': 'सोमालिया',
    'nl': 'Somalië',
    'nn': 'Somalia',
    'nv': 'Soomáálii Bikéyah',
    'oc': 'Somalia',
    'or': 'ସୋମାଲିୟା',
    'pa': 'ਸੋਮਾਲੀਆ',
    'pi': 'सोमालिया',
    'pl': 'Somalia',
    'ps': 'سومالیا',
    'pt': 'Somália',
    'pt_BR': 'Somália',
    'ro': 'Somalia',
    'ru': 'Сомали',
    'rw': 'Somaliya',
    'sc': 'Somàlia',
    'sd': 'صوماليه',
    'si': 'සෝමාලියාව',
    'sk': 'Somálsko',
    'sl': 'Somalija',
    'so': 'Soomaaliya',
    'sq': 'Somali',
    'sr': 'Сомалија',
    'sv': 'Somalia',
    'sw': 'Somalia',
    'ta': 'சோமாலியா',
    'te': 'సోమాలియా',
    'tg': 'Сомалӣ',
    'th': 'โซมาเลีย',
    'ti': 'ሶማልያ',
    'tk': 'Somali',
    'tl': 'Somalia',
    'tr': 'Somali',
    'tt': 'Сомалиа',
    'ug': 'سومالى',
    'uk': 'Сомалі',
    'ur': 'صومالیہ',
    'uz': 'Somali',
    've': 'Somalia',
    'vi': 'Xo-ma-li',
    'wa': 'Somaleye',
    'wo': 'Somaali',
    'xh': 'Somalia',
    'yo': 'Sòmálíà',
    'zh_CN': '索马里',
    'zh_HK': '索馬里',
    'zh_TW': '索馬利亞',
    'zu': 'ISomalia'
  },
);
