import '../country.dart';

const countryTHA = Country(
  alpha2: 'TH',
  alpha3: 'THA',
  continent: Continent.asia,
  countryCode: '66',
  currencyCode: 'THB',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'TH',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 15.870032,
      longitude: 100.992541,
    ),
    maxCoordinate: Coordinate(
      latitude: 20.465143,
      longitude: 105.636812,
    ),
    minCoordinate: Coordinate(
      latitude: 5.613038,
      longitude: 97.343396,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 20.465143,
        longitude: 105.636812,
      ),
      southwest: Coordinate(
        latitude: 5.613038,
        longitude: 97.343396,
      ),
    ),
  ),
  internationalPrefix: '001',
  ioc: 'THA',
  isoLongName: 'The Kingdom of Thailand',
  isoShortName: 'Thailand',
  isoShortNameLowerCase: null,
  languagesOfficial: ['th'],
  languagesSpoken: ['th'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9, 10],
  nationalPrefix: '0',
  nationality: 'Thai',
  number: '764',
  postalCode: true,
  postalCodeFormat: r'\d{5}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'South-Eastern Asia',
  unLocode: 'TH',
  unMember: true,
  unofficialNames: ['Thailand', 'Thaïlande', 'Tailandia', 'タイ', 'ประเทศไทย'],
  vehicleRegistrationCode: 'T',
  worldRegion: WorldRegion.apac,
  addressFormat: null,
  vatRates: VatRates(
    standard: 7.0,
    reduced: [0.0],
    superReduced: null,
    parking: null,
  ),
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Thailand",
    "af": "Thailand",
    "ak": "Thailand",
    "am": "ታ፤ሒን፥",
    "an": "Thailand",
    "ar": "تايلاند",
    "as": "থাইলেণ্ড",
    "ay": "Thailand",
    "az": "Tayland",
    "ba": "Thailand",
    "be": "Тайланд",
    "bg": "Тайланд",
    "bi": "Thailand",
    "bn": "থাইল্যান্ড",
    "bn_IN": "থাইল্যান্ড",
    "br": "Thailand",
    "bs": "Tajland",
    "ca": "Tailàndia",
    "ce": "Таиланд",
    "ch": "Thailand",
    "cs": "Thajsko",
    "cv": "Таиланд",
    "cy": "Gwlad Thai",
    "da": "Thailand",
    "de": "Thailand",
    "dv": "ސިޔާމު",
    "dz": "ཐཱའི་ལེནཌི།",
    "ee": "Thailand",
    "el": "Ταϊλάνδη",
    "en": "Thailand",
    "eo": "Tajlando",
    "es": "Tailandia",
    "et": "Tai",
    "eu": "Tailandia",
    "fa": "تایلند",
    "ff": "Tailannde",
    "fi": "Thaimaa",
    "fo": "Thailand",
    "fr": "Thaïlande",
    "fy": "Tailân",
    "ga": "An Téalainn",
    "gl": "Tailandia",
    "gn": "Thailand",
    "gu": "થાઇલેન્ડ",
    "gv": "Yn Çheer Thai",
    "ha": "Thailand",
    "he": "תאילנד",
    "hi": "थाईलैण्ड",
    "hr": "Tajland",
    "ht": "Tayilann",
    "hu": "Thaiföld",
    "hy": "Թաիլանդ",
    "ia": "Thailandia",
    "id": "Thailand",
    "io": "Tailando",
    "is": "Tæland",
    "it": "Thailandia",
    "iu": "Thailand",
    "ja": "タイ",
    "ka": "ტაილანდი",
    "ki": "Thailand",
    "kk": "Тайланд",
    "kl": "Thailand",
    "km": "ថៃ",
    "kn": "ಥಾಯ್‍ಲ್ಯಾಂಡ್",
    "ko": "태국",
    "ku": "Tayland",
    "kv": "Таиланд",
    "kw": "Pow Tay",
    "ky": "Таиланд",
    "lo": "ປະເທດໄທ",
    "lt": "Tailandas",
    "lv": "Taizeme",
    "mi": "Thailand",
    "mk": "Тајланд",
    "ml": "തായ്‌ലന്‍ഡ്",
    "mn": "Тайланд",
    "mr": "थायलंड",
    "ms": "Thailand",
    "mt": "Tajlandja",
    "my": "ထိုင်းနိုင်ငံ",
    "na": "Thailand",
    "nb": "Thailand",
    "ne": "थाइल्याण्ड",
    "nl": "Thailand",
    "nn": "Thailand",
    "nv": "Thailand",
    "oc": "Tailàndia",
    "or": "ଥାଇଲ୍ଯାଣ୍ଡ",
    "pa": "ਥਾਈਲੈਂਡ",
    "pi": "थाइलैंड",
    "pl": "Tajlandia",
    "ps": "تايلنډ",
    "pt": "Tailândia",
    "pt_BR": "Tailândia",
    "ro": "Tailanda",
    "ru": "Таиланд",
    "rw": "Tayilande",
    "sc": "Thailàndia",
    "sd": "ٿائيلينڊ",
    "si": "තායිලන්තය",
    "sk": "Thajsko",
    "sl": "Tajska",
    "so": "Taylaand",
    "sq": "Tajlandë",
    "sr": "Тајланд",
    "sv": "Thailand",
    "sw": "Thailand",
    "ta": "தாய்லாந்து",
    "te": "థాయ్‌లాండ్",
    "tg": "Тайланд",
    "th": "ไทย",
    "ti": "ታይላንድ",
    "tk": "Taýland",
    "tl": "Thailand",
    "tr": "Tayland",
    "tt": "Тайланд",
    "ug": "تايلاند",
    "uk": "Таїланд",
    "ur": "تھائی لینڈ",
    "uz": "Tailand",
    "ve": "Thailand",
    "vi": "Thái Lan",
    "wa": "Taylande",
    "wo": "Taaylaand",
    "xh": "Thailand",
    "yo": "Tháílàndì",
    "zh_CN": "泰国",
    "zh_HK": "泰國",
    "zh_TW": "泰國",
    "zu": "I-Thayilandi"
  },
);
