import '../country.dart';

const countryTJK = Country(
  alpha2: 'TJ',
  alpha3: 'TJK',
  continent: Continent.asia,
  countryCode: '992',
  currencyCode: 'TJS',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'TI',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 38.861034,
      longitude: 71.276093,
    ),
    maxCoordinate: Coordinate(
      latitude: 41.044367,
      longitude: 75.1539564,
    ),
    minCoordinate: Coordinate(
      latitude: 36.6719898,
      longitude: 67.34201209999999,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 41.044367,
        longitude: 75.1539564,
      ),
      southwest: Coordinate(
        latitude: 36.6719898,
        longitude: 67.34201209999999,
      ),
    ),
  ),
  internationalPrefix: '810',
  ioc: 'TJK',
  isoLongName: 'The Republic of Tajikistan',
  isoShortName: 'Tajikistan',
  isoShortNameLowerCase: null,
  languagesOfficial: ['tg', 'ru'],
  languagesSpoken: ['tg', 'ru'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [9],
  nationalPrefix: '8',
  nationality: 'Tadzhik',
  number: '762',
  postalCode: true,
  postalCodeFormat: '\\d{6}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Central Asia',
  unLocode: 'TJ',
  unMember: true,
  unofficialNames: [
    'Tajikistan',
    'Tadschikistan',
    'Tayikistán',
    'タジキスタン',
    'Tadzjikistan',
    'Tajikstan'
  ],
  vehicleRegistrationCode: 'TJ',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: 'RUB',
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Tajikistan',
    'af': 'Tadjikistan',
    'ak': 'Tajikistan',
    'am': 'ታጃጡስታን',
    'an': 'Tajikistan',
    'ar': 'طاجيكستان',
    'as': 'তাজিকিস্তান',
    'ay': 'Tajikistan',
    'az': 'Tacikistan',
    'ba': 'Tajikistan',
    'be': 'Таджыкістан',
    'bg': 'Таджикистан',
    'bi': 'Tajikistan',
    'bn': 'তাজিকিস্তান',
    'bn_IN': 'তাজিকিস্তান',
    'br': 'Tadjikistan',
    'bs': 'Tadžikistan',
    'ca': 'Tadjikistan',
    'ce': 'Таджики',
    'ch': 'Tajikistan',
    'cs': 'Tádžikistán',
    'cv': 'Таджики',
    'cy': 'Tajikistan',
    'da': 'Tadsjikistan',
    'de': 'Tadschikistan',
    'dv': 'ތަޖިކިސްތާން',
    'dz': 'ཏ་ཇི་ཀིསི་ཏཱན།',
    'ee': 'Tajikistan',
    'el': 'Τατζικιστάν',
    'en': 'Tajikistan',
    'eo': 'Taĝikio',
    'es': 'Tayikistán',
    'et': 'Tadžikistan',
    'eu': 'Tajikistan',
    'fa': 'تاجیکستان',
    'ff': 'Tajikistan',
    'fi': 'Tadžikistan',
    'fo': 'Tadsjikistan',
    'fr': 'Tadjikistan',
    'fy': 'Tadzjikistan',
    'ga': 'An Táidsíceastáin',
    'gl': 'Taxiquistán',
    'gn': 'Tajikistan',
    'gu': 'તાજીકિસ્તાન',
    'gv': 'Yn Tajikistaan',
    'ha': 'Tajikistan',
    'he': 'טג׳יקיסטן',
    'hi': 'ताजिकिस्तान',
    'hr': 'Tadžikistan',
    'ht': 'Tadjikistan',
    'hu': 'Tádzsikisztán',
    'hy': 'Տաճիկստան',
    'ia': 'Tajikistan',
    'id': 'Tajikistan',
    'io': 'Tajikistan',
    'is': 'Tadsíkistan',
    'it': 'Tagikistan',
    'iu': 'Tajikistan',
    'ja': 'タジキスタン',
    'ka': 'ტაჯიკეთი',
    'ki': 'Tajikistan',
    'kk': 'Тәжікстан',
    'kl': 'Tajikistan',
    'km': 'តាហ្ស៊ីគីស្តង់',
    'kn': 'ತಾಜಿಕಿಸ್ತಾನ್',
    'ko': '타지키스탄',
    'ku': 'Tacîkistan',
    'kv': 'Таджикистан',
    'kw': 'Pow Tajik',
    'ky': 'Тажикстан',
    'lo': 'Tajikistan',
    'lt': 'Tadžikistanas',
    'lv': 'Tadžikistāna',
    'mi': 'Tajikistan',
    'mk': 'Таџикистан',
    'ml': 'താജികിസ്താന്‍',
    'mn': 'Тажикстан',
    'mr': 'ताजिकिस्तान',
    'ms': 'Tadjikistan',
    'mt': 'Tajikistan',
    'my': 'တာဂျစ်ကစ္စတန်နိုင်ငံ',
    'na': 'Tadjikitan',
    'nb': 'Tadsjikistan',
    'ne': 'ताजिकिस्तान',
    'nl': 'Tadzjikistan',
    'nn': 'Tadsjikistan',
    'nv': 'Tʼajiʼ Bikéyah',
    'oc': 'Tatgiquistan',
    'or': 'ତାଜୀକିସ୍ତାନ',
    'pa': 'ਤਜ਼ਾਕਸਤਾਨ',
    'pi': 'ताजिकिस्थान',
    'pl': 'Tadżykistan',
    'ps': 'تاجکستان',
    'pt': 'Tajiquistão',
    'pt_BR': 'Tadjiquistão',
    'ro': 'Tajikistan',
    'ru': 'Таджикистан',
    'rw': 'Tajikisitani',
    'sc': 'Tagìkistan',
    'sd': 'تاجڪستان',
    'si': 'ටජිකිස්තානය',
    'sk': 'Tadžikistan',
    'sl': 'Tadžikistan',
    'so': 'Tajikistan',
    'sq': 'Taxhikistan',
    'sr': 'Таџикистан',
    'sv': 'Tadzjikistan',
    'sw': 'Tajikistan',
    'ta': 'தசிக்கிசுதான்',
    'te': 'తజికిస్తాన్',
    'tg': 'Тоҷикистон',
    'th': 'ทาจิกิสถาน',
    'ti': 'ታጃኪስታን',
    'tk': 'Täjigistan',
    'tl': 'Tajikistan',
    'tr': 'Tacikistan',
    'tt': 'Тажыкстан',
    'ug': 'تاجىكىستان',
    'uk': 'Таджикистан',
    'ur': 'تاجکستان',
    'uz': 'Tojikiston',
    've': 'Tajikistan',
    'vi': 'Tha-gi-ki-xthanh',
    'wa': 'Tadjikistan',
    'wo': 'Taajikistaan',
    'xh': 'Tajikistan',
    'yo': 'Tajikistan',
    'zh_CN': '塔吉克斯坦',
    'zh_HK': '塔吉克斯坦',
    'zh_TW': '塔吉克',
    'zu': 'Tajikistan'
  },
);
