import '../country.dart';

const countryTLS = Country(
  alpha2: 'TL',
  alpha3: 'TLS',
  continent: Continent.asia,
  countryCode: '670',
  currencyCode: 'IDR',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'TT',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -8.874217,
      longitude: 125.727539,
    ),
    maxCoordinate: Coordinate(
      latitude: -8.048399999999999,
      longitude: 127.4249,
    ),
    minCoordinate: Coordinate(
      latitude: -9.5303001,
      longitude: 124.0332,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: -8.048399999999999,
        longitude: 127.4249,
      ),
      southwest: Coordinate(
        latitude: -9.5303001,
        longitude: 124.0332,
      ),
    ),
  ),
  internationalPrefix: 'None',
  ioc: 'TLS',
  isoLongName: 'The Democratic Republic of Timor-Leste',
  isoShortName: 'Timor-Leste',
  isoShortNameLowerCase: null,
  languagesOfficial: ['pt'],
  languagesSpoken: ['pt'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7],
  nationalPrefix: 'None',
  nationality: 'East Timorese',
  number: '626',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'South-Eastern Asia',
  unLocode: 'TL',
  unMember: true,
  unofficialNames: [
    'East Timor',
    'Timor-Leste',
    'Timor oriental',
    'Timor Oriental',
    '東ティモール',
    'Oost-Timor'
  ],
  vehicleRegistrationCode: 'TL',
  worldRegion: WorldRegion.apac,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Timor-Leste',
    'af': 'Oos-Timor',
    'ak': 'Timor-Leste',
    'am': 'ሤስሲቅ ቲሥሴ',
    'an': 'Timor-Leste',
    'ar': 'تيمور-ليستي',
    'as': 'টিমোৰ-লেস্তে',
    'ay': 'Timor-Leste',
    'az': 'Timor-Leste',
    'ba': 'Timor-Leste',
    'be': 'Усходні Тымор',
    'bg': 'Тимор-Лест',
    'bi': 'Timor-Leste',
    'bn': 'টিমোর-লেস্তে',
    'bn_IN': 'টিমোর-লেস্তে',
    'br': 'Timor-Leste',
    'bs': 'Istočni Timor',
    'ca': 'Timor Oriental',
    'ce': 'Timor-Leste',
    'ch': 'Timor-Leste',
    'cs': 'Východní Timor',
    'cv': 'Timor-Leste',
    'cy': 'Timor-Leste',
    'da': 'Timor-Leste',
    'de': 'Timor-Leste',
    'dv': 'Timor-Leste',
    'dz': 'ཊི་མོར་-ལིསི་ཏི།',
    'ee': 'Timor-Leste',
    'el': 'Τιμόρ-Λέστε',
    'en': 'Timor-Leste',
    'eo': 'Orienta Timoro',
    'es': 'Timor Oriental',
    'et': 'Ida-Timor (Timor-Leste)',
    'eu': 'Ekialdeko Timor',
    'fa': 'تیمور شرقی',
    'ff': 'Timor-Leste',
    'fi': 'Itä-Timor',
    'fo': 'Timor-Leste',
    'fr': 'Timor oriental',
    'fy': 'Timor-Leste',
    'ga': 'Tíomór Thoir',
    'gl': 'Timor Leste',
    'gn': 'Timor-Leste',
    'gu': 'તિમોર-લેસ્ટે',
    'gv': 'Timor-Leste',
    'ha': 'Timor-Leste',
    'he': 'טימור מזרח',
    'hi': 'तिमोर-लेस्टे',
    'hr': 'Istočni Timor',
    'ht': 'Timò oryantal',
    'hu': 'Kelet-Timor',
    'hy': 'Թիմոր - Լեստե',
    'ia': 'Timor Oriental',
    'id': 'Timor Timur',
    'io': 'Timor-Leste',
    'is': 'Tímor-Leste',
    'it': 'Timor Est',
    'iu': 'Timor-Leste',
    'ja': '東ティモール',
    'ka': 'აღმოსავლეთი ტიმორი',
    'ki': 'Timor-Leste',
    'kk': 'Тимор-Лесте',
    'kl': 'Timor-Leste',
    'km': 'ទីម័រ',
    'kn': 'Timor-Leste',
    'ko': '동티모르',
    'ku': 'Tîmora Rojhilat',
    'kv': 'Timor-Leste',
    'kw': 'Timor-Leste',
    'ky': 'Тимор-Лесте',
    'lo': 'Timor-Leste',
    'lt': 'Rytų Timoras',
    'lv': 'Austrumtimora',
    'mi': 'Timor-Leste',
    'mk': 'Тимор-Лесте',
    'ml': 'തിമൂര്‍-ലെസ്തെ',
    'mn': 'Timor-Leste',
    'mr': 'तिमोर-लेस्ते',
    'ms': 'Timor-Leste',
    'mt': 'Timor tal-Lvant',
    'my': 'Timor-Leste',
    'na': 'Timor-Leste',
    'nb': 'Øst-Timor',
    'ne': 'टिमोर-लेस्टे',
    'nl': 'Oost-Timor',
    'nn': 'Aust-Timor',
    'nv': 'Timor-Leste',
    'oc': 'Timor-Leste',
    'or': 'ତିମୋର-ଲେଷ୍ଟେ',
    'pa': 'ਟੀਮੁਰ-ਲੀਸਟੀ',
    'pi': 'Timor-Leste',
    'pl': 'Timor Wschodni',
    'ps': 'Timor-Leste',
    'pt': 'Timor-Leste',
    'pt_BR': 'Timor Leste',
    'ro': 'Timorul de Est',
    'ru': 'Восточный Тимор',
    'rw': 'Timoro-Lesite',
    'sc': 'Timor Orientale',
    'sd': 'Timor-Leste',
    'si': 'ටිමෝර්-ලෙස්ටේ',
    'sk': 'Východný Timor',
    'sl': 'Vzhodni Timor',
    'so': 'Timor-Leste',
    'sq': 'Timori Lindor-Leste',
    'sr': 'Источни Тимор',
    'sv': 'Östtimor',
    'sw': 'Timor-Leste',
    'ta': 'திமோர்-லெஸ்டி',
    'te': 'తిమోర్-లేస్తే',
    'tg': 'Темур-Лесте',
    'th': 'ติมอร์-เลสเต',
    'ti': 'ምስራቅ ቲሞር',
    'tk': 'Timor-Leste',
    'tl': 'Timor-Leste',
    'tr': 'Timor-Leste',
    'tt': 'Тимор-Лесте',
    'ug': 'شەرقىي تىمور',
    'uk': 'Східний Тимор',
    'ur': 'Timor-Leste',
    'uz': 'Timor-Leste',
    've': 'Timor-Leste',
    'vi': 'Thi-moa Le-xợ-te',
    'wa': 'Timor Ess',
    'wo': 'Timor-Leste',
    'xh': 'Timor-Leste',
    'yo': 'Timor-Leste',
    'zh_CN': '东帝汶',
    'zh_HK': '東帝汶',
    'zh_TW': '東帝汶',
    'zu': 'Timor-Leste'
  },
);
