import '../country.dart';

const countryTUN = Country(
  alpha2: 'TN',
  alpha3: 'TUN',
  continent: Continent.africa,
  countryCode: '216',
  currencyCode: 'TND',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'TS',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 33.886917,
      longitude: 9.537499,
    ),
    maxCoordinate: Coordinate(
      latitude: 37.5359,
      longitude: 11.599217,
    ),
    minCoordinate: Coordinate(
      latitude: 30.2280339,
      longitude: 7.522311,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 37.5359,
        longitude: 11.599217,
      ),
      southwest: Coordinate(
        latitude: 30.2280339,
        longitude: 7.522311,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'TUN',
  isoLongName: 'The Republic of Tunisia',
  isoShortName: 'Tunisia',
  isoShortNameLowerCase: null,
  languagesOfficial: ['ar', 'fr'],
  languagesSpoken: ['ar', 'fr'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8],
  nationalPrefix: 'None',
  nationality: 'Tunisian',
  number: '788',
  postalCode: true,
  postalCodeFormat: '\\d{4}',
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Northern Africa',
  unLocode: 'TN',
  unMember: true,
  unofficialNames: [
    'Tunisia',
    'تونس',
    'Tunesien',
    'Tunisie',
    'Túnez',
    'チュニジア',
    'Tunesië'
  ],
  vehicleRegistrationCode: 'TN',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    'ab': 'Tunisia',
    'af': 'Tunisië',
    'ak': 'Tunisia',
    'am': 'ቱኒፑ።',
    'an': 'Tunisia',
    'ar': 'تونس',
    'as': 'টিউনিছিয়া',
    'ay': 'Tunisia',
    'az': 'Tunis',
    'ba': 'Tunisia',
    'be': 'Туніс',
    'bg': 'Тунис',
    'bi': 'Tunisia',
    'bn': 'টিউনিশিয়া',
    'bn_IN': 'টিউনিশিয়া',
    'br': 'Tunizia',
    'bs': 'Tunis',
    'ca': 'Tunísia',
    'ce': 'Тунис',
    'ch': 'Tunisia',
    'cs': 'Tunisko',
    'cv': 'Тунис',
    'cy': 'Twnisia',
    'da': 'Tunesien',
    'de': 'Tunesien',
    'dv': 'ތޫނިސް',
    'dz': 'ཊུ་ནི་སི་ཡ།',
    'ee': 'Tunisia',
    'el': 'Τυνησία',
    'en': 'Tunisia',
    'eo': 'Tunizio',
    'es': 'Tunez',
    'et': 'Tuneesia',
    'eu': 'Tunisia',
    'fa': 'تونس',
    'ff': 'Tunisia',
    'fi': 'Tunisia',
    'fo': 'Tunesia',
    'fr': 'Tunisie',
    'fy': 'Tuneezje',
    'ga': 'An Túinéis',
    'gl': 'Tunicia',
    'gn': 'Tunisia',
    'gu': 'ટ્યુનિશિયા',
    'gv': 'Yn Tooneesh',
    'ha': 'Tunisia',
    'he': 'תוניסיה',
    'hi': 'ट्यूनिशिया',
    'hr': 'Tunis',
    'ht': 'Tinizi',
    'hu': 'Tunézia',
    'hy': 'Թունիս',
    'ia': 'Tunisia',
    'id': 'Tunisia',
    'io': 'Tunizia',
    'is': 'Túnis',
    'it': 'Tunisia',
    'iu': 'Tunisia',
    'ja': 'チュニジア',
    'ka': 'ტუნისი',
    'ki': 'Tunisia',
    'kk': 'Тунис',
    'kl': 'Tunisia',
    'km': 'ទុយណេស៊ី',
    'kn': 'ತುನಿಸಿಯ',
    'ko': '튀니지',
    'ku': 'Tûnis',
    'kv': 'Tunisia',
    'kw': 'Tunisi',
    'ky': 'Тунис',
    'lo': 'Tunisia',
    'lt': 'Tunisas',
    'lv': 'Tunisija',
    'mi': 'Tūnihia',
    'mk': 'Тунис',
    'ml': 'ടുണീഷ്യ',
    'mn': 'Тунгус',
    'mr': 'ट्युनिशिया',
    'ms': 'Tunisia',
    'mt': 'Tunisia',
    'my': 'တူနီးရှားနိုင်ငံ',
    'na': 'Tunisia',
    'nb': 'Tunisia',
    'ne': 'टुनिसिया',
    'nl': 'Tunesië',
    'nn': 'Tunisia',
    'nv': 'Tunisia',
    'oc': 'Tunisia',
    'or': 'ଟ୍ଯୁନୀଶିୟା',
    'pa': 'ਟਿਊਨੀਸ਼ੀਆ',
    'pi': 'टुनिशिया',
    'pl': 'Tunezja',
    'ps': 'تونس',
    'pt': 'Tunísia',
    'pt_BR': 'Tunísia',
    'ro': 'Tunisia',
    'ru': 'Тунис',
    'rw': 'Tunisiya',
    'sc': 'Tunisia',
    'sd': 'Tunisia',
    'si': 'ටියුනීසියා',
    'sk': 'Tunisko',
    'sl': 'Tunizija',
    'so': 'Tuniisiya',
    'sq': 'Tunizi',
    'sr': 'Тунис',
    'sv': 'Tunisien',
    'sw': 'Tunisia',
    'ta': 'துனீசியா',
    'te': 'తునిశియా',
    'tg': 'Тунис',
    'th': 'ตูนิเซีย',
    'ti': 'ቱኒዝያ',
    'tk': 'Tunis',
    'tl': 'Tunisia',
    'tr': 'Tunus',
    'tt': 'Тунисиа',
    'ug': 'تۇنىس',
    'uk': 'Туніс',
    'ur': 'تونس',
    'uz': 'Tunis',
    've': 'Tunisia',
    'vi': 'Tu-ni-xi-a',
    'wa': 'Tunizeye',
    'wo': 'Tiniisi',
    'xh': 'Tunisia',
    'yo': 'Tùnísíà',
    'zh_CN': '突尼斯',
    'zh_HK': '突尼斯',
    'zh_TW': '突尼西亞',
    'zu': 'ITunisia'
  },
);
