import '../country.dart';

const countryTUR = Country(
  alpha2: 'TR',
  alpha3: 'TUR',
  continent: Continent.europe,
  countryCode: '90',
  currencyCode: 'TRY',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'TU',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 38.963745,
      longitude: 35.243322,
    ),
    maxCoordinate: Coordinate(
      latitude: 42.3666999,
      longitude: 44.8178449,
    ),
    minCoordinate: Coordinate(
      latitude: 35.808592,
      longitude: 25.5377,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 42.3666999,
        longitude: 44.8178449,
      ),
      southwest: Coordinate(
        latitude: 35.808592,
        longitude: 25.5377,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'TUR',
  isoLongName: 'The Republic of Türkiye',
  isoShortName: 'Türkiye',
  isoShortNameLowerCase: null,
  languagesOfficial: ['tr'],
  languagesSpoken: ['tr'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [10],
  nationalPrefix: '0',
  nationality: 'Turkish',
  number: '792',
  postalCode: true,
  postalCodeFormat: '\\d{5}',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'Western Asia',
  unLocode: 'TR',
  unMember: true,
  unofficialNames: ['Turkey', 'Türkei', 'Turquie', 'Turquía', 'トルコ', 'Turkije'],
  vehicleRegistrationCode: 'TR',
  worldRegion: WorldRegion.emea,
  addressFormat:
      '{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: true,
  isoShortNameByLocale: {
    'ab': 'Türkiye',
    'af': 'Turkye',
    'ak': 'Türkiye',
    'am': 'ቱሴጤ',
    'an': 'Türkiye',
    'ar': 'تركيّا',
    'as': 'তুৰস্ক',
    'ay': 'Türkiye',
    'az': 'Türkiyə',
    'ba': 'Türkiye',
    'be': 'Турцыя',
    'bg': 'Турция',
    'bi': 'Türkiye',
    'bn': 'তুর্কি',
    'bn_IN': 'তুর্কি',
    'br': 'Turkia',
    'bs': 'Turska',
    'ca': 'Turquia',
    'ce': 'Турци',
    'ch': 'Türkiye',
    'cs': 'Turecko',
    'cv': 'Турци',
    'cy': 'Twrci',
    'da': 'Tyrkiet',
    'de': 'Türkei',
    'dv': 'ތުރުކީވިލާތް',
    'dz': 'ཊར་ཀི།',
    'ee': 'Türkiye',
    'el': 'Τουρκία',
    'en': 'Turkey',
    'eo': 'Turkio',
    'es': 'Turquía',
    'et': 'Türgi',
    'eu': 'Turkia',
    'fa': 'ترکیه',
    'ff': 'Türkiye',
    'fi': 'Turkki',
    'fo': 'Turkaland',
    'fr': 'Turquie',
    'fy': 'Turkije',
    'ga': 'An Tuirc',
    'gl': 'Turquía',
    'gn': 'Türkiye',
    'gu': 'તુર્કી',
    'gv': 'Yn Turkee',
    'ha': 'Turkiyya',
    'he': 'טורקיה',
    'hi': 'तुर्की',
    'hr': 'Turska',
    'ht': 'Tiki',
    'hu': 'Törökország',
    'hy': 'Թուրքիա',
    'ia': 'Turchia',
    'id': 'Turki',
    'io': 'Turkia',
    'is': 'Tyrkland',
    'it': 'Turchia',
    'iu': 'ᑑᕐᑭ',
    'ja': 'トルコ',
    'ka': 'თურქეთი',
    'ki': 'Türkiye',
    'kk': 'Түркия',
    'kl': 'Türkiye',
    'km': 'ទួរគី',
    'kn': 'ಟರ್ಕಿ',
    'ko': '터키',
    'ku': 'Tirkiye',
    'kv': 'Турция',
    'kw': 'Turki',
    'ky': 'Түркия Республикасы',
    'lo': 'ປະເທດຕວກກີ',
    'lt': 'Turkija',
    'lv': 'Turcija',
    'mi': 'Tākei',
    'mk': 'Турција',
    'ml': 'തുര്‍ക്കി',
    'mn': 'Турк',
    'mr': 'तुर्की',
    'ms': 'Turki',
    'mt': 'Turkija',
    'my': 'တူရကီနိုင်ငံ',
    'na': 'Terki',
    'nb': 'Tyrkia',
    'ne': 'टर्की',
    'nl': 'Turkije',
    'nn': 'Tyrkia',
    'nv': 'Tʼóok Bikéyah',
    'oc': 'Turquia',
    'or': 'ତୁର୍କୀ',
    'pa': 'ਤੁਰਕੀ',
    'pi': 'तुर्किये',
    'pl': 'Turcja',
    'ps': 'تورکيه',
    'pt': 'Turquia',
    'pt_BR': 'Turquia',
    'ro': 'Turcia',
    'ru': 'Турция',
    'rw': 'Turukiya',
    'sc': 'Turchia',
    'sd': 'Türkiye',
    'si': 'තුර්කිය',
    'sk': 'Turecko',
    'sl': 'Turčija',
    'so': 'Turki',
    'sq': 'Turqi',
    'sr': 'Турска',
    'sv': 'Turkiet',
    'sw': 'Türkiye',
    'ta': 'துருக்கி',
    'te': 'టర్కీ',
    'tg': 'Туркия',
    'th': 'ตุรกี',
    'ti': 'ቱርኪ',
    'tk': 'Türkiýe',
    'tl': 'Türkiye',
    'tr': 'Türkiye',
    'tt': 'Төркиә',
    'ug': 'تۈركىيە',
    'uk': 'Туреччина',
    'ur': 'ترکی',
    'uz': 'Turkiya',
    've': 'Türkiye',
    'vi': 'Thổ Nhĩ Kỳ',
    'wa': 'Turkeye',
    'wo': 'Turki',
    'xh': 'Türkiye',
    'yo': 'Túrkì',
    'zh_CN': '土耳其',
    'zh_HK': '土耳其',
    'zh_TW': '土耳其',
    'zu': 'ITheki'
  },
);
