import '../country.dart';

const countryUSA = Country(
  alpha2: 'US',
  alpha3: 'USA',
  continent: Continent.northAmerica,
  countryCode: '1',
  currencyCode: 'USD',
  distanceUnit: DistanceUnit.miles,
  gec: 'US',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 37.09024,
      longitude: -95.712891,
    ),
    maxCoordinate: Coordinate(
      latitude: 71.3577635769,
      longitude: -66.96466,
    ),
    minCoordinate: Coordinate(
      latitude: 18.91619,
      longitude: -171.791110603,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 71.3577635769,
        longitude: -66.96466,
      ),
      southwest: Coordinate(
        latitude: 18.91619,
        longitude: -171.791110603,
      ),
    ),
  ),
  internationalPrefix: '011',
  ioc: 'USA',
  isoLongName: 'The United States of America',
  isoShortName: 'United States of America',
  isoShortNameLowerCase: 'United States of America (the)',
  languagesOfficial: ['en'],
  languagesSpoken: ['en'],
  nationalDestinationCodeLengths: [3],
  nationalNumberLengths: [10],
  nationalPrefix: '1',
  nationality: 'American',
  number: '840',
  postalCode: true,
  postalCodeFormat: r'(\d{5})(?:[ \-](\d{4}))?',
  region: Region.americas,
  startOfWeek: Week.sunday,
  subregion: 'Northern America',
  unLocode: 'US',
  unMember: true,
  unofficialNames: [
    'United States',
    'United States of America',
    'USA',
    'Vereinigte Staaten von Amerika',
    'États-Unis',
    'Estados Unidos',
    'アメリカ合衆国',
    'Verenigde Staten',
    'Соединенные Штаты Америки'
  ],
  vehicleRegistrationCode: 'USA',
  worldRegion: WorldRegion.amer,
  addressFormat: '''{{recipient}}
{{street}}
{{city}} {{region_short}} {{postalcode}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: true,
  g20Member: true,
  isoShortNameByLocale: {
    "ab": "United States",
    "af": "Verenigde State",
    "ak": "United States",
    "am": "ጐሣሱጢ",
    "an": "United States",
    "ar": "الولايات المتّحدة",
    "as": "মাৰ্কিন যুক্তৰাষ্ট্ৰ",
    "ay": "United States",
    "az": "Birləşmiş Ştatlar",
    "ba": "United States",
    "be": "Злучаныя Штаты",
    "bg": "Съединени щати",
    "bi": "United States",
    "bn": "মার্কিন যুক্তরাষ্ট্র",
    "bn_IN": "মার্কিন যুক্তরাষ্ট্র",
    "br": "Stadoù Unanet",
    "bs": "SAD",
    "ca": "Estats Units",
    "ce": "United States",
    "ch": "United States",
    "cs": "Spojené státy",
    "cv": "United States",
    "cy": "Yr Unol Daleithiau",
    "da": "USA",
    "de": "Vereinigte Staaten",
    "dv": "United States",
    "dz": "ཡུ་ན་ཡེ་ཊེཊི་ སིཊེཊིསི།",
    "ee": "United States",
    "el": "Ηνωμένες Πολιτείες",
    "en": "United States",
    "eo": "Usono",
    "es": "Estados Unidos",
    "et": "Ameerika Ühendriigid",
    "eu": "Estatu Batuak",
    "fa": "ایالات متحدهٔ آمریکا",
    "ff": "United States",
    "fi": "Yhdysvallat",
    "fo": "Sambandsríki Amerika",
    "fr": "États-Unis",
    "fy": "United States",
    "ga": "Na Stáit Aontaithe",
    "gl": "Estados Unidos de América",
    "gn": "United States",
    "gu": "યુનાઇટેડ સ્ટેટ્સ",
    "gv": "United States",
    "ha": "United States",
    "he": "ארצות הברית",
    "hi": "संयुक्त राज्य",
    "hr": "Sjedinjene Države",
    "ht": "Etazini",
    "hu": "Egyesült Államok",
    "hy": "Ամէրիկայի Միացյալ Նահանգնէր",
    "ia": "Statos Unite",
    "id": "Amerika Serikat",
    "io": "United States",
    "is": "Bandaríkin",
    "it": "Stati Uniti",
    "iu": "United States",
    "ja": "米国",
    "ka": "ამერიკის შეერთებული შტატები",
    "ki": "United States",
    "kk": "АҚШ",
    "kl": "United States",
    "km": "សហរដ្ឋ​អាមេរិក",
    "kn": "ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನಗಳು",
    "ko": "미국",
    "ku": "Dewletên Yekbûyî",
    "kv": "United States",
    "kw": "United States",
    "ky": "АКШ",
    "lo": "United States",
    "lt": "Jungtinės Amerikos Valstijos",
    "lv": "Amerikas Savienotās Valstis",
    "mi": "Amerika",
    "mk": "Соединети држави",
    "ml": "ഐക്യനാടുകള്‍",
    "mn": "Америкын нэгдсэн улс",
    "mr": "युनायटेड स्टेटस्",
    "ms": "Amerika Syarikat",
    "mt": "United States",
    "my": "United States",
    "na": "United States",
    "nb": "USA",
    "ne": "संयुक्त राज्य",
    "nl": "Verenigde Staten",
    "nn": "USA",
    "nv": "United States",
    "oc": "Estats Units",
    "or": "ଯୁକ୍ତରାଷ୍ଟ୍ର",
    "pa": "ਅਮਰੀਕਾ",
    "pi": "United States",
    "pl": "Stany Zjednoczone",
    "ps": "United States",
    "pt": "Estados Unidos",
    "pt_BR": "Estados Unidos",
    "ro": "Statele Unite",
    "ru": "Соединённые штаты",
    "rw": "Leta Zunze Ubumwe",
    "sc": "Istados Unidos",
    "sd": "United States",
    "si": "එක්සත් ජනපද",
    "sk": "Spojené štáty",
    "sl": "Združene države",
    "so": "Qaramada Midoobey ee Maraykanka",
    "sq": "Shtetet e Bashkuara",
    "sr": "Сједињене Државе",
    "sv": "USA",
    "sw": "United States",
    "ta": "ஐக்கிய அமெரிக்கா",
    "te": "యునైటెడ్ స్టేట్స్",
    "tg": "Иёлоти Муттаҳида",
    "th": "สหรัฐ",
    "ti": "ኣመሪካ",
    "tk": "Amerikanyň Birleşen Ştatlary",
    "tl": "Estados Unidos",
    "tr": "Amerika Birleşik Devletleri",
    "tt": "Берләшкән Штатлар",
    "ug": "ئامېرىكا",
    "uk": "США",
    "ur": "United States",
    "uz": "United States",
    "ve": "United States",
    "vi": "Mỹ",
    "wa": "Estats Unis",
    "wo": "Aamerik",
    "xh": "United States",
    "yo": "United States",
    "zh_CN": "美国",
    "zh_HK": "美國",
    "zh_TW": "美國",
    "zu": "United States"
  },
);
