import '../country.dart';

const countryVNM = Country(
  alpha2: 'VN',
  alpha3: 'VNM',
  continent: Continent.asia,
  countryCode: '84',
  currencyCode: 'VND',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'VM',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: 14.058324,
      longitude: 108.277199,
    ),
    maxCoordinate: Coordinate(
      latitude: 23.3926504,
      longitude: 109.6765,
    ),
    minCoordinate: Coordinate(
      latitude: 8.1952001,
      longitude: 102.1439156,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: 23.3926504,
        longitude: 109.6765,
      ),
      southwest: Coordinate(
        latitude: 8.1952001,
        longitude: 102.1439156,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'VIE',
  isoLongName: 'The Socialist Republic of Viet Nam',
  isoShortName: 'Viet Nam',
  isoShortNameLowerCase: null,
  languagesOfficial: ['vi'],
  languagesSpoken: ['vi'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [7, 8, 9, 10],
  nationalPrefix: '0',
  nationality: 'Vietnamese',
  number: '704',
  postalCode: true,
  postalCodeFormat: r'\d{5}\d?',
  region: Region.asia,
  startOfWeek: Week.monday,
  subregion: 'South-Eastern Asia',
  unLocode: 'VN',
  unMember: true,
  unofficialNames: ['Vietnam', 'ベトナム', 'Viet Nam'],
  vehicleRegistrationCode: 'VN',
  worldRegion: WorldRegion.apac,
  addressFormat: '''{{recipient}}
{{street}}
{{city}}
{{region}}
{{country}}''',
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Vietnam",
    "af": "Viëtnam",
    "ak": "Vietnam",
    "am": "ቬት ናም",
    "an": "Vietnam",
    "ar": "الفيتنام",
    "as": "ভিয়েতনাম",
    "ay": "Vietnam",
    "az": "Vietnam",
    "ba": "Vietnam",
    "be": "В'етнам",
    "bg": "Виетнам",
    "bi": "Vietnam",
    "bn": "ভিয়েতনাম",
    "bn_IN": "ভিয়েতনাম",
    "br": "Viêt Nam",
    "bs": "Vijetnam",
    "ca": "Vietnam",
    "ce": "Вьетнам",
    "ch": "Vietnam",
    "cs": "Vietnam",
    "cv": "Вьетнам",
    "cy": "Fietnam",
    "da": "Vietnam",
    "de": "Vietnam",
    "dv": "ވިއެޓުނާމު",
    "dz": "ཝེཊི་ནམ།",
    "ee": "Vietnam",
    "el": "Βιετνάμ",
    "en": "Vietnam",
    "eo": "Vjetnamio",
    "es": "Vietnam",
    "et": "Vietnam",
    "eu": "Vietnam",
    "fa": "ویتنام",
    "ff": "Vietnam",
    "fi": "Vietnam",
    "fo": "Vietnam",
    "fr": "Viêt Nam",
    "fy": "Fjetnam",
    "ga": "Vítneam",
    "gl": "Vietnam",
    "gn": "Vietnam",
    "gu": "વિયેતનામ",
    "gv": "Yn Vietnam",
    "ha": "Vietnam",
    "he": "וייטנאם",
    "hi": "वियतनाम",
    "hr": "Vijetnam",
    "ht": "Vyetnam",
    "hu": "Vietnám",
    "hy": "Վիետնամ",
    "ia": "Vietnam",
    "id": "Vietnam",
    "io": "Vietnam",
    "is": "Víetnam",
    "it": "Vietnam",
    "iu": "Vietnam",
    "ja": "ベトナム",
    "ka": "ვიეტ-ნამი",
    "ki": "Vietnam",
    "kk": "Вьетнам",
    "kl": "Vietnam",
    "km": "វៀតណាម",
    "kn": "ವಿಯೆಟ್ನಾಂ",
    "ko": "베트남",
    "ku": "Viyetnam",
    "kv": "Вьетнам",
    "kw": "Vietnam",
    "ky": "Вьетнам",
    "lo": "ປະເທດຫວຽດນາມ",
    "lt": "Vietnamas",
    "lv": "Vjetnama",
    "mi": "Whitināmu",
    "mk": "Виетнам",
    "ml": "വിയറ്റ്നാം",
    "mn": "Vietnam",
    "mr": "व्हियेतनाम",
    "ms": "Vietnam",
    "mt": "Vjetnam",
    "my": "ဗီယက်နမ်နိုင်ငံ",
    "na": "Bitinam",
    "nb": "Vietnam",
    "ne": "भिएतनाम",
    "nl": "Vietnam",
    "nn": "Vietnam",
    "nv": "Vietnam",
    "oc": "Vietnam",
    "or": "ଭିୟେତନାମ",
    "pa": "ਵੀਅਤਨਾਮ",
    "pi": "वियेतनाम",
    "pl": "Wietnam",
    "ps": "Vietnam",
    "pt": "Vietname",
    "pt_BR": "Vietnã",
    "ro": "Vietnam",
    "ru": "Вьетнам",
    "rw": "Viyetinamu",
    "sc": "Vietnam",
    "sd": "ويٽنام",
    "si": "වියෙට්නාමය",
    "sk": "Vietnam",
    "sl": "Vietnam",
    "so": "Fiyetnaam",
    "sq": "Vietnam",
    "sr": "Вијетнам",
    "sv": "Vietnam",
    "sw": "Vietnam",
    "ta": "வியட்னாம்",
    "te": "వియత్నామ్",
    "tg": "Ветнам",
    "th": "เวียดนาม",
    "ti": "ቬትናም",
    "tk": "Wýetnam",
    "tl": "Viet Nam",
    "tr": "Vietnam",
    "tt": "Виет Нам",
    "ug": "ۋيېتنام",
    "uk": "В'єтнам",
    "ur": "ویتنام",
    "uz": "Vyetnam",
    "ve": "Viëtnam",
    "vi": "Việt Nam",
    "wa": "Vietnam",
    "wo": "Wiyet Naam",
    "xh": "Vietnam",
    "yo": "Fiẹtnám",
    "zh_CN": "越南",
    "zh_HK": "越南",
    "zh_TW": "越南",
    "zu": "IViyetnami"
  },
);
