import '../country.dart';

const countryZWE = Country(
  alpha2: 'ZW',
  alpha3: 'ZWE',
  continent: Continent.africa,
  countryCode: '263',
  currencyCode: 'USD',
  distanceUnit: DistanceUnit.kilometres,
  gec: 'ZI',
  geo: GeoData(
    coordinate: Coordinate(
      latitude: -19.015438,
      longitude: 29.154857,
    ),
    maxCoordinate: Coordinate(
      latitude: -15.6093188,
      longitude: 33.068236,
    ),
    minCoordinate: Coordinate(
      latitude: -22.4219117,
      longitude: 25.237368,
    ),
    boundary: BoundingBox(
      northeast: Coordinate(
        latitude: -15.6093188,
        longitude: 33.068236,
      ),
      southwest: Coordinate(
        latitude: -22.4219117,
        longitude: 25.237368,
      ),
    ),
  ),
  internationalPrefix: '00',
  ioc: 'ZIM',
  isoLongName: 'The Republic of Zimbabwe',
  isoShortName: 'Zimbabwe',
  isoShortNameLowerCase: null,
  languagesOfficial: ['en', 'sn', 'nd'],
  languagesSpoken: ['en', 'sn', 'nd'],
  nationalDestinationCodeLengths: [2],
  nationalNumberLengths: [8, 9, 10, 11],
  nationalPrefix: '0',
  nationality: 'Zimbabwean',
  number: '716',
  postalCode: false,
  postalCodeFormat: null,
  region: Region.africa,
  startOfWeek: Week.monday,
  subregion: 'Eastern Africa',
  unLocode: 'ZW',
  unMember: true,
  unofficialNames: ['Zimbabwe', 'Simbabwe', 'Zimbabue', 'ジンバブエ'],
  vehicleRegistrationCode: 'ZW',
  worldRegion: WorldRegion.emea,
  addressFormat: null,
  vatRates: null,
  nanpPrefix: null,
  eeaMember: false,
  euMember: false,
  esmMember: false,
  altCurrency: null,
  g7Member: false,
  g20Member: false,
  isoShortNameByLocale: {
    "ab": "Zimbabwe",
    "af": "Zimbabwe",
    "ak": "Zimbabwe",
    "am": "ፒሤቢ።",
    "an": "Zimbabwe",
    "ar": "زمبابوي",
    "as": "জিম্বাবোৱে",
    "ay": "Zimbabwe",
    "az": "Zimbabve",
    "ba": "Zimbabwe",
    "be": "Зімбабвэ",
    "bg": "Зимбабве",
    "bi": "Zimbabwe",
    "bn": "জিম্বাবুয়ে",
    "bn_IN": "জিম্বাবুয়ে",
    "br": "Zimbabwe",
    "bs": "Zimbabve",
    "ca": "Zimbabwe",
    "ce": "Зимбабве",
    "ch": "Zimbabwe",
    "cs": "Zimbabwe",
    "cv": "Зимбабве",
    "cy": "Zimbabwe",
    "da": "Zimbabwe",
    "de": "Simbabwe",
    "dv": "ޒިމްބާބުވޭ",
    "dz": "ཛིམ་བབ་ཝི།",
    "ee": "Zimbabwe",
    "el": "Ζιμπάμπουε",
    "en": "Zimbabwe",
    "eo": "Zimbabvo",
    "es": "Zimbabue",
    "et": "Zimbabwe",
    "eu": "Zimbabwe",
    "fa": "زیمبابوه",
    "ff": "Zimbabwe",
    "fi": "Zimbabwe",
    "fo": "Simbabvi",
    "fr": "Zimbabwe",
    "fy": "Simbabwe",
    "ga": "An tSiombáib",
    "gl": "Zimbabue",
    "gn": "Zimbabwe",
    "gu": "ઝીમ્બાબવે",
    "gv": "Yn Çhimbabwe",
    "ha": "Zimbabwe",
    "he": "זימבבואה",
    "hi": "ज़िम्बाब्वे",
    "hr": "Zimbabve",
    "ht": "Zimbabwe",
    "hu": "Zimbabwe",
    "hy": "Զիմբաբվե",
    "ia": "Zimbabwe",
    "id": "Zimbabwe",
    "io": "Zimbabwe",
    "is": "Simbabve",
    "it": "Zimbabwe",
    "iu": "Zimbabwe",
    "ja": "ジンバブエ",
    "ka": "ზიმბაბვე",
    "ki": "Zimbabwe",
    "kk": "Зимбабве",
    "kl": "Zimbabwe",
    "km": "ហ្ស៊ីមបាវ៉េ",
    "kn": "ಝಿಂಬಾಬ್ವೆ",
    "ko": "짐바브웨",
    "ku": "Zimbabwe",
    "kv": "Zimbabwe",
    "kw": "Zimbabwe",
    "ky": "Зимбабве",
    "lo": "Zimbabwe",
    "lt": "Zimbabvė",
    "lv": "Zimbabve",
    "mi": "Zimbabwe",
    "mk": "Зимбабве",
    "ml": "സിംബാബ്‌വേ",
    "mn": "Замбибаби",
    "mr": "झिंबाव्वे",
    "ms": "Zimbabwe",
    "mt": "Żimbabwe",
    "my": "ဇင်ဘာဘွေနိုင်ငံ",
    "na": "Zimbabwe",
    "nb": "Zimbabwe",
    "ne": "जिम्बावे",
    "nl": "Zimbabwe",
    "nn": "Zimbabwe",
    "nv": "Hooghan Tsé Bee Ádaalyaaí Bikéyah",
    "oc": "Zimbabwe",
    "or": "ଜିମ୍ବାଓ୍ବେ",
    "pa": "ਜਿੰਬਾਬਾਵੇ",
    "pi": "जिम्बाबवे",
    "pl": "Zimbabwe",
    "ps": "زېمبابوې",
    "pt": "Zimbabwe",
    "pt_BR": "Zimbábue",
    "ro": "Zimbabwe",
    "ru": "Зимбабве",
    "rw": "Zimbabwe",
    "sc": "Zimbabwe",
    "sd": "زمبابوي",
    "si": "සිම්බාබ්වේ",
    "sk": "Zimbabwe",
    "sl": "Zimbabve",
    "so": "Simbaabwe",
    "sq": "Zimbabve",
    "sr": "Зимбабве",
    "sv": "Zimbabwe",
    "sw": "Zimbabwe",
    "ta": "ஜிம்பாப்வே",
    "te": "జింబాంబ్వే",
    "tg": "Зимбабве",
    "th": "ซิมบับเว",
    "ti": "ዚምባብዌ",
    "tk": "Zimbabwe",
    "tl": "Zimbabwe",
    "tr": "Zimbabve",
    "tt": "Зимбабве",
    "ug": "زىمبابۋې",
    "uk": "Зімбабве",
    "ur": "زمبابوے",
    "uz": "Zimbabve",
    "ve": "Zimbagwe",
    "vi": "Xim-ba-bu-ê",
    "wa": "Zimbabwè",
    "wo": "Simbaabwee",
    "xh": "Zimbabwe",
    "yo": "Sìmbábúè",
    "zh_CN": "津巴布韦",
    "zh_HK": "津巴布韋",
    "zh_TW": "辛巴威",
    "zu": "IZimbabwe"
  },
);
