name: country_generator
description: A generator for generating country object from countries json.
version: 4.1.6
homepage: https://github.com/aaassseee/country
repository: https://github.com/aaassseee/country/tree/master/country_generator
issue_tracker: https://github.com/aaassseee/country/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: '>=2.0.0 <3.0.0'
  yaml: '>=3.0.0 <4.0.0'
  path: '>=1.8.0 <2.0.0'
  collection: '>=1.15.0 <2.0.0'
  country: '>=4.1.10 <5.0.0'

dev_dependencies:
  build_test: '>=2.0.0 <3.0.0'
  flutter_lints: ">=4.0.0 <5.0.0"
  test: '>=1.0.0 <2.0.0'

#dependency_overrides:
#  country:
#    path:
#      ../country